"""v4 batch 2d — 5 more batch-2 categories. 100 questions.
Vape & Hoverboard Disasters, Famous Last Words, Failed Political Campaigns,
Disney Park Disasters, Predictions That Aged Poorly.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH2D_QUESTIONS = [
    # VAPE & HOVERBOARD DISASTERS
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Hoverboards (self-balancing scooters) were briefly banned by what major airline in 2015?", 'question': "Banned by?", 'answers': {'A': "All major US airlines (3 of the big 4 within a week)", 'B': "Just Delta", 'C': "Only international carriers", 'D': "Greyhound bus"}, 'correct': 'A', 'explanation': "December 2015. American, Delta, United, JetBlue all banned hoverboards within days. Lithium-ion fire risk.", 'commentary_correct': 'Correct! Airlines blanket-banned.', 'commentary_wrong': 'All major US airlines.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "The CPSC recalled approximately how many hoverboards in 2016?", 'question': "Approximate?", 'answers': {'A': "~500,000", 'B': "~50,000", 'C': "~5,000", 'D': "~2 million"}, 'correct': 'A', 'explanation': "Half-million hoverboards recalled in 2016. Multiple house fires linked to defective lithium batteries.", 'commentary_correct': 'Correct! Half a million.', 'commentary_wrong': '~500K.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Mike Tyson on a hoverboard in 2015 resulted in?", 'question': "Resulted in?", 'answers': {'A': "Tyson falling and breaking his back (his words)", 'B': "Him winning a race", 'C': "Both A — and his daughter laughing on camera", 'D': "A vine that got 50M views"}, 'correct': 'C', 'explanation': "Tyson posted Instagram video of himself wiping out hard on hoverboard. Daughter laughed. He claimed back injury.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Vape pen explosions caused injuries that the FDA estimated as approximately?", 'question': "Estimated?", 'answers': {'A': "~2,000+ ER visits between 2015-2017", 'B': "Just dozens", 'C': "Over a million", 'D': "None reported"}, 'correct': 'A', 'explanation': "Multiple hospital studies. FDA + CDC tracking. Real injuries to mouth, face, legs (pocket explosions).", 'commentary_correct': 'Correct! ~2K ER visits.', 'commentary_wrong': '~2K ER visits.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "EVALI (e-cigarette/vape lung disease) outbreak peaked in?", 'question': "When?", 'answers': {'A': "Late 2019", 'B': "2015", 'C': "2022", 'D': "2017"}, 'correct': 'A', 'explanation': "EVALI = E-cigarette or Vaping-Associated Lung Injury. ~2,800 cases. Vitamin E acetate in black-market THC carts.", 'commentary_correct': 'Correct! 2019.', 'commentary_wrong': '2019.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Hoverboard fires destroyed homes across?", 'question': "Caused?", 'answers': {'A': "Multiple US states - dozens of house fires reported in 2015-16", 'B': "Just one isolated incident", 'C': "Only in California", 'D': "Both A and several deaths reported"}, 'correct': 'D', 'explanation': "Multiple deaths attributed. Hoverboards left charging caused multiple home losses. CPSC investigations.", 'commentary_correct': 'Correct! Multiple states.', 'commentary_wrong': 'Multiple states. Deaths.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "The brand JUUL faced what in 2022?", 'question': "Faced?", 'answers': {'A': "FDA ordered marketing ban (later put on hold)", 'B': "$1.2B class action settlement", 'C': "Both", 'D': "Acquisition by Big Tobacco"}, 'correct': 'C', 'explanation': "FDA marketing ban + huge settlements over youth marketing. Multiple states + class actions.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Justin Bieber was famously photographed on a hoverboard in?", 'question': "Year?", 'answers': {'A': "2015", 'B': "2018", 'C': "2010", 'D': "Never"}, 'correct': 'A', 'explanation': "Bieber, multiple celebs, all owning hoverboards in 2015 - peak of hoverboard mania.", 'commentary_correct': 'Correct! 2015.', 'commentary_wrong': '2015.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Wisk (one-wheeled self-balancing scooter from China) was?", 'question': "Was?", 'answers': {'A': "Cheaper, more dangerous knockoff of hoverboards", 'B': "An aviation brand", 'C': "Both A and used in viral fail videos", 'D': "FDA-approved"}, 'correct': 'C', 'explanation': "Wisk and other cheap Chinese knockoffs were the biggest fire-risk culprits. Viral fail content.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Vaping nicotine content compared to a cigarette?", 'question': "Comparison?", 'answers': {'A': "1 Juul pod = ~20 cigarettes worth of nicotine", 'B': "Less than a cigarette", 'C': "Same", 'D': "100 cigarettes"}, 'correct': 'A', 'explanation': "Standard JUUL pod = ~20 cigarettes nicotine. High concentration. Major youth-addiction concern.", 'commentary_correct': 'Correct! ~20 cigs.', 'commentary_wrong': '~20 cigs per pod.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Onewheel (one-wheeled e-skateboard) has caused?", 'question': "Has caused?", 'answers': {'A': "Multiple deaths + recalls in 2023", 'B': "Just minor injuries", 'C': "Both A and CPSC investigation", 'D': "Nothing — perfect safety record"}, 'correct': 'C', 'explanation': "Onewheel/Future Motion. CPSC issued warning 2022, full recall 2023. Multiple deaths from sudden stops.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Lithium-ion battery fires generally are caused by?", 'question': "Caused by?", 'answers': {'A': "Thermal runaway from defects, overcharging, or damage", 'B': "Heat alone", 'C': "Cold weather", 'D': "Bluetooth"}, 'correct': 'A', 'explanation': "Thermal runaway. Once it starts, the fire can't be put out by water. Hoverboards/vapes/e-bikes affected.", 'commentary_correct': 'Correct! Thermal runaway.', 'commentary_wrong': 'Thermal runaway.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Solowheel/electric unicycle (EUC) accidents have led to?", 'question': "Have led to?", 'answers': {'A': "Multiple high-profile head injuries", 'B': "Helmet requirements in some cities", 'C': "Both", 'D': "Outright bans in DC and Manhattan"}, 'correct': 'C', 'explanation': "EUC accidents serious. Some cities mandate helmets for these and other e-mobility devices.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Bird and Lime e-scooters launched in?", 'question': "Launched?", 'answers': {'A': "2017 (Santa Monica first)", 'B': "2012", 'C': "2020", 'D': "2010"}, 'correct': 'A', 'explanation': "Bird launched Santa Monica 2017. Caused chaos. Cities scrambled to regulate. Still operating in 100+ cities.", 'commentary_correct': 'Correct! 2017.', 'commentary_wrong': '2017.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Approximately how many vape products did the FDA review in their 2020 deadline?", 'question': "Approximate?", 'answers': {'A': "~6 million products", 'B': "100", 'C': "10,000", 'D': "1 billion"}, 'correct': 'A', 'explanation': "6+ million products had to be reviewed by FDA September 2020 deadline. Backlog massive. Many denied.", 'commentary_correct': 'Correct! 6M+.', 'commentary_wrong': '6M+.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Hoverboards became cheap toys after 2016 because?", 'question': "Because?", 'answers': {'A': "Initial fad died after fire scandals", 'B': "Tech improved", 'C': "Both A and B brought prices from $1000+ down to under $200", 'D': "Government subsidies"}, 'correct': 'C', 'explanation': "Original prices were $1000+. After fire scares + supply glut, prices crashed. UL-certified models now safe.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "JUUL's first viral marketing campaign was criticized for?", 'question': "Criticized for?", 'answers': {'A': "Targeting teens with social media + fruit flavors", 'B': "Boring", 'C': "Both A and FDA banned fruit flavors 2020", 'D': "Pricing"}, 'correct': 'C', 'explanation': "Mint, mango, cucumber flavors. Banned 2020 due to teen appeal. Multiple state lawsuits over teen targeting.", 'commentary_correct': 'Correct! Teen targeting.', 'commentary_wrong': 'Teen targeting.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Russell Westbrook on a hoverboard in 2015 produced?", 'question': "Produced?", 'answers': {'A': "A viral video of him riding through the locker room", 'B': "An injury", 'C': "Both", 'D': "An NBA fine"}, 'correct': 'A', 'explanation': "Westbrook + many NBA players rode hoverboards. Multiple players sustained training-related injuries.", 'commentary_correct': 'Correct! Locker room video.', 'commentary_wrong': 'Locker room video.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Esquire ranked the worst vape ever as?", 'question': "Was?", 'answers': {'A': "Pax-style boutique vape with bad battery life", 'B': "Disposable vapes (multiple brands)", 'C': "Both — disposables proliferated post-Juul ban", 'D': "Mods"}, 'correct': 'C', 'explanation': "Disposable vapes filled the niche after Juul/Pax pod restrictions. Environmental + safety concerns.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Vape & Hoverboard Disasters', 'setup': "Most dangerous e-scooter trend was?", 'question': "Was?", 'answers': {'A': "Lyft/Bird scooters left on sidewalks → trip hazards", 'B': "Riding the wrong direction", 'C': "Both — and underage riders", 'D': "Hacked unlocked rides"}, 'correct': 'C', 'explanation': "Many e-scooter problems. Sidewalk clutter. Underage. Both real issues cities still dealing with.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},

    # FAMOUS LAST WORDS
    {'category': 'Famous Last Words', 'setup': "Oscar Wilde's reported last words were about?", 'question': "About what?", 'answers': {'A': "The wallpaper in his hotel room ('one of us has to go')", 'B': "His writing", 'C': "His son", 'D': "Both A and various comedic variations"}, 'correct': 'A', 'explanation': "'My wallpaper and I are fighting a duel to the death. One or the other of us has to go.' Famous comedic exit.", 'commentary_correct': 'Correct! Wallpaper.', 'commentary_wrong': 'Wallpaper. Wilde\'s style.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "General John Sedgwick's last words at Spotsylvania (1864) were?", 'question': "Last words?", 'answers': {'A': "'They couldn't hit an elephant at this distance.'", 'B': "'Charge!'", 'C': "Nothing recorded", 'D': "'God save the Union.'"}, 'correct': 'A', 'explanation': "Confederate sharpshooter shot him minutes later. Civil War's most famous case of fatal overconfidence.", 'commentary_correct': 'Correct! Elephant.', 'commentary_wrong': 'Famous overconfidence.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Karl Marx's last words to his housekeeper were reportedly?", 'question': "Were?", 'answers': {'A': "'Go on, get out! Last words are for fools who haven't said enough.'", 'B': "'Workers of the world unite.'", 'C': "Nothing", 'D': "Both — multiple reports"}, 'correct': 'A', 'explanation': "1883. Refused to give meaningful last words. Communicated his contempt for the dramatic.", 'commentary_correct': 'Correct! Marx style.', 'commentary_wrong': 'Marx style.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Steve Jobs' reported last words were?", 'question': "Were?", 'answers': {'A': "'Oh wow. Oh wow. Oh wow.'", 'B': "'iPhone is coming.'", 'C': "Nothing recorded", 'D': "'Tim, take care of Apple.'"}, 'correct': 'A', 'explanation': "Sister Mona Simpson's eulogy. Jobs reportedly looked up at his family. Said 'Oh wow' three times.", 'commentary_correct': 'Correct! Oh wow.', 'commentary_wrong': 'Oh wow x3.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Marie Antoinette's last words at the guillotine (1793) were?", 'question': "Were?", 'answers': {'A': "Apology to her executioner for stepping on his foot", 'B': "Defiant statement against the revolution", 'C': "Nothing", 'D': "'Tell my son...'"}, 'correct': 'A', 'explanation': "'Pardon me, monsieur, I did not do it on purpose.' Stepping on Sanson's (executioner's) foot. Tragic etiquette.", 'commentary_correct': 'Correct! Stepped on foot.', 'commentary_wrong': 'Stepped on his foot.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Pancho Villa's last words in 1923 were?", 'question': "Last words?", 'answers': {'A': "'Don't let it end like this. Tell them I said something.'", 'B': "Nothing — he died instantly", 'C': "A religious statement", 'D': "Disputed — multiple accounts"}, 'correct': 'A', 'explanation': "Villa was ambushed in his car. Reportedly said something funny about needing memorable last words.", 'commentary_correct': 'Correct! Tell them.', 'commentary_wrong': 'Tell them I said something.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Voltaire's reported last words about the devil were?", 'question': "Said what?", 'answers': {'A': "'This is no time to make new enemies.'", 'B': "'Burn this!'", 'C': "Nothing", 'D': "'God forgive me.'"}, 'correct': 'A', 'explanation': "Asked by priest to renounce Satan. Voltaire reportedly said 'this is no time to make new enemies.' 1778.", 'commentary_correct': 'Correct! New enemies.', 'commentary_wrong': 'New enemies.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Humphrey Bogart's reported last words were?", 'question': "Were?", 'answers': {'A': "'I should never have switched from Scotch to martinis.'", 'B': "'Here's looking at you, kid.'", 'C': "Nothing", 'D': "'Forget it.'"}, 'correct': 'A', 'explanation': "Bogart's famously witty exit line. Lifelong drinker. Died 1957 of throat cancer.", 'commentary_correct': 'Correct! Scotch to martinis.', 'commentary_wrong': 'Scotch to martinis.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "James Brown's reported last words were?", 'question': "Were?", 'answers': {'A': "'I'm going away tonight.'", 'B': "'I feel good.'", 'C': "Nothing", 'D': "Singing"}, 'correct': 'A', 'explanation': "Brown died Christmas 2006. Said the line to his manager. Calm acknowledgement.", 'commentary_correct': 'Correct! Going away tonight.', 'commentary_wrong': 'Going away tonight.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Salvador Dalí's last words were?", 'question': "Were?", 'answers': {'A': "Asking about clocks", 'B': "Saying 'where is my clock?'", 'C': "Both — and reported by his nurse", 'D': "Nothing memorable"}, 'correct': 'C', 'explanation': "Multiple accounts of clock-related last words. Dalí's clocks obsession to the end. Died 1989.", 'commentary_correct': 'Correct! Clocks.', 'commentary_wrong': 'Clocks. Surrealist to the end.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Bing Crosby's reported last words on a Spanish golf course were?", 'question': "Were?", 'answers': {'A': "'That was a great game of golf, fellas.'", 'B': "Nothing — instant collapse", 'C': "Both A — he collapsed walking off green", 'D': "A song"}, 'correct': 'C', 'explanation': "October 1977. Crosby played 18 holes, walked off, said the line, collapsed from heart attack.", 'commentary_correct': 'Correct! Great game.', 'commentary_wrong': 'Great game of golf.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Frank Sinatra's last words were?", 'question': "Were?", 'answers': {'A': "'I'm losing.'", 'B': "A song", 'C': "Nothing — heart attack", 'D': "'Tell Barbara.'"}, 'correct': 'A', 'explanation': "May 1998. Said 'I'm losing' as final words. Heart attack followed shortly. Tragic and concise.", 'commentary_correct': 'Correct! I\'m losing.', 'commentary_wrong': 'I\'m losing.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Truman Capote's reported last words were?", 'question': "Were?", 'answers': {'A': "Asking for his mother", 'B': "Insulting someone", 'C': "Both A and his Auntie Sook", 'D': "Nothing"}, 'correct': 'C', 'explanation': "1984. Truman called for his mother (long deceased). Tragic full-circle moment.", 'commentary_correct': 'Correct! Mother.', 'commentary_wrong': 'Asking for mother.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Tupac Shakur's reported last words were?", 'question': "Were?", 'answers': {'A': "'Fuck you.'", 'B': "'Tell Mom I love her.'", 'C': "Disputed — multiple accounts", 'D': "Both A — to the cop who asked his name"}, 'correct': 'D', 'explanation': "Tupac reportedly told the responding officer 'Fuck you.' Las Vegas, 1996. Multiple accounts vary.", 'commentary_correct': 'Correct! Tupac style.', 'commentary_wrong': 'Tupac style.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Princess Diana's last reported words were?", 'question': "Were?", 'answers': {'A': "'My God, what's happened?'", 'B': "'Tell my boys...'", 'C': "Nothing recorded", 'D': "'Leave me alone.'"}, 'correct': 'A', 'explanation': "After the August 1997 crash in the Paris tunnel. Multiple witnesses heard 'My God, what's happened?'", 'commentary_correct': 'Correct! What\'s happened.', 'commentary_wrong': 'What\'s happened.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Buddy Holly's reported last words to Waylon Jennings were?", 'question': "Were?", 'answers': {'A': "'Well, I hope your ol' bus freezes up!'", 'B': "Nothing", 'C': "A song lyric", 'D': "'Goodbye, brother.'"}, 'correct': 'A', 'explanation': "Iowa, February 3, 1959. Holly took plane. Jennings stayed on bus. Joke landed darkly when plane crashed.", 'commentary_correct': 'Correct! Bus freeze.', 'commentary_wrong': 'Hope your bus freezes.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Karl Wallenda (high-wire artist) said before his 1978 fall?", 'question': "Said?", 'answers': {'A': "'To be on the wire is life. The rest is waiting.'", 'B': "'I'll be fine.'", 'C': "Disputed", 'D': "Both A — this was years before the fall"}, 'correct': 'D', 'explanation': "Wallenda's life philosophy, said years before. Fell from wire San Juan 1978. The quote became eulogy.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Comedian John Pinette's reported last words were?", 'question': "Were?", 'answers': {'A': "He died alone in a hotel — last words unknown", 'B': "'I'm going to a buffet.'", 'C': "A joke", 'D': "Both A and discovered by housekeeping"}, 'correct': 'D', 'explanation': "Pinette died Pittsburgh hotel 2014. Sad. Discovered by housekeeping. Pulmonary embolism.", 'commentary_correct': 'Correct! Alone in hotel.', 'commentary_wrong': 'Alone in hotel. Sad.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Ned Kelly (Australian outlaw) said before hanging in 1880?", 'question': "Said?", 'answers': {'A': "'Such is life.'", 'B': "Nothing", 'C': "A long speech", 'D': "Both A — and Aussie cultural touchstone"}, 'correct': 'D', 'explanation': "Iconic Aussie outlaw quote. 'Such is life.' Tattoos still common in Australia today.", 'commentary_correct': 'Correct! Such is life.', 'commentary_wrong': 'Such is life.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Famous Last Words', 'setup': "Confucius's reported last words were?", 'question': "Were?", 'answers': {'A': "Lamenting his own teaching wouldn't outlive him (he was wrong)", 'B': "Nothing recorded", 'C': "A proverb", 'D': "Both A and reported in disciple accounts"}, 'correct': 'D', 'explanation': "479 BCE. Reportedly worried about his legacy. 2500+ years later, still influential. Got it wrong.", 'commentary_correct': 'Correct! Worried about legacy.', 'commentary_wrong': 'Worried for nothing.', 'difficulty': 'medium', 'time_limit': 15},

    # FAILED POLITICAL CAMPAIGNS
    {'category': 'Failed Political Campaigns', 'setup': "Ross Perot won what percentage of the popular vote in 1992?", 'question': "Approximate?", 'answers': {'A': "~19% — strong third-party showing", 'B': "Less than 1%", 'C': "~45%", 'D': "~30%"}, 'correct': 'A', 'explanation': "Perot won 18.9%. No electoral votes. Third-party highwater mark since Teddy Roosevelt 1912.", 'commentary_correct': 'Correct! ~19%.', 'commentary_wrong': '~19%.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Howard Dean's 2004 campaign was undone by?", 'question': "Undone by?", 'answers': {'A': "The 'Dean Scream' in Iowa", 'B': "A spending scandal", 'C': "Both A and B", 'D': "Lack of funds"}, 'correct': 'A', 'explanation': "January 2004 Iowa concession speech. Dean's 'YEAAARGH' scream. Played 600+ times on TV. Career-ending.", 'commentary_correct': 'Correct! The Scream.', 'commentary_wrong': 'The Scream.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Jeb Bush's 2016 campaign spent how much per primary vote?", 'question': "Approximate per vote?", 'answers': {'A': "~$1,200+ per vote", 'B': "$50 per vote", 'C': "$10 per vote", 'D': "$5,000 per vote"}, 'correct': 'A', 'explanation': "Right to Rise PAC + campaign spent $130M for tiny primary returns. ~$1,200+ per Iowa caucus vote.", 'commentary_correct': 'Correct! $1,200+.', 'commentary_wrong': '$1,200+ per vote.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Andrew Yang's 2020 'Yang Gang' was famous for?", 'question': "Famous for?", 'answers': {'A': "$1000/month UBI proposal", 'B': "Math hats", 'C': "Both A and B", 'D': "Crowd surfing"}, 'correct': 'C', 'explanation': "Universal Basic Income proposal + 'Math' hats. Cult-like online following. Dropped out after NH 2020.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Marianne Williamson's 2020 debate moment was?", 'question': "Famous for?", 'answers': {'A': "'I'm going to harness love for political purposes.'", 'B': "Nothing — she didn't qualify", 'C': "Both A — and she became viral meme", 'D': "Attacking another candidate"}, 'correct': 'C', 'explanation': "July 2019 debate. Williamson's spiritual approach went viral. Mocked widely. Dropped out Jan 2020.", 'commentary_correct': 'Correct! Love and harnessing.', 'commentary_wrong': 'Love quote.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Michael Bloomberg's 2020 campaign spent how much before dropping out?", 'question': "Approximate?", 'answers': {'A': "~$1 billion", 'B': "$100M", 'C': "$10M", 'D': "$5 billion"}, 'correct': 'A', 'explanation': "Bloomberg spent $1B in 3 months. Won American Samoa. Dropped out after Super Tuesday. Endorsed Biden.", 'commentary_correct': 'Correct! $1 billion.', 'commentary_wrong': '$1 billion.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Gary Hart's 1988 campaign ended over?", 'question': "Ended over?", 'answers': {'A': "Affair with Donna Rice — Monkey Business yacht photo", 'B': "A finance scandal", 'C': "Both A and B", 'D': "Health issues"}, 'correct': 'A', 'explanation': "Hart was Dem frontrunner. National Enquirer published photo. He dropped out. Started modern political-scandal era.", 'commentary_correct': 'Correct! Monkey Business.', 'commentary_wrong': 'Monkey Business yacht.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Vermin Supreme's signature look is?", 'question': "Look?", 'answers': {'A': "A boot as a hat + a 'free ponies' platform", 'B': "Pirate costume", 'C': "Both — and he's run for president multiple times", 'D': "A clown nose"}, 'correct': 'C', 'explanation': "Vermin Supreme. Boot hat. Free ponies platform. Perennial joke candidate since 1986. Always loses.", 'commentary_correct': 'Correct! Boot hat.', 'commentary_wrong': 'Boot + ponies.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Hillary Clinton's 2016 'deplorables' comment was made at?", 'question': "At which event?", 'answers': {'A': "LGBT fundraiser in NYC", 'B': "Press conference", 'C': "Campaign rally", 'D': "Town hall"}, 'correct': 'A', 'explanation': "September 2016 fundraiser. 'Basket of deplorables.' Trump's team weaponized it. Hurt campaign.", 'commentary_correct': 'Correct! NYC fundraiser.', 'commentary_wrong': 'NYC fundraiser.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Mitt Romney's 2012 '47%' comment was?", 'question': "Comment?", 'answers': {'A': "Saying 47% of Americans will vote for Obama because they're dependent on government", 'B': "About taxes", 'C': "Both A and B", 'D': "Misquoted"}, 'correct': 'C', 'explanation': "Florida fundraiser May 2012. Secret recording. Romney saying 47% won't vote for him. Released September.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "John Kasich's 2016 campaign won?", 'question': "Won?", 'answers': {'A': "Just Ohio (his home state)", 'B': "Nothing", 'C': "Multiple primary states", 'D': "California"}, 'correct': 'A', 'explanation': "Kasich won only his home state of Ohio. Stayed in race until May 2016. Distant 4th place finish.", 'commentary_correct': 'Correct! Ohio only.', 'commentary_wrong': 'Ohio only.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Pat Buchanan's 1992 'pitchfork brigade' was about?", 'question': "About what?", 'answers': {'A': "Populist conservatism — culture wars", 'B': "Religious right", 'C': "Both", 'D': "Trade"}, 'correct': 'C', 'explanation': "1992 RNC speech. 'Culture war for the soul of America.' Buchanan's challenge to George H.W. Bush.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Rick Santorum's 2012 'Google problem' was?", 'question': "Was?", 'answers': {'A': "Dan Savage's redefinition of 'santorum' on Google", 'B': "Tech bias", 'C': "Both A — and dominated top results", 'D': "Server crashes"}, 'correct': 'C', 'explanation': "Dan Savage's 2003 redefinition of 'santorum' was top Google result. Persistent campaign embarrassment.", 'commentary_correct': 'Correct! Google bomb.', 'commentary_wrong': 'Dan Savage\'s campaign.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "John Edwards' 2008 campaign collapsed over?", 'question': "Collapsed over?", 'answers': {'A': "Affair with Rielle Hunter while his wife had cancer", 'B': "Lobbyist payments", 'C': "Both", 'D': "Tax issues"}, 'correct': 'A', 'explanation': "Edwards' affair + love child + payments to keep it quiet. Federal indictment 2011. Career ended.", 'commentary_correct': 'Correct! Rielle Hunter.', 'commentary_wrong': 'Rielle Hunter affair.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Herman Cain's 2012 '9-9-9' plan referred to?", 'question': "Was?", 'answers': {'A': "9% personal income, 9% corporate, 9% national sales tax", 'B': "Defense spending", 'C': "Pizza menu", 'D': "Both A and his pizza-CEO background"}, 'correct': 'A', 'explanation': "Tax reform plan: 9-9-9. Cain led polls briefly. Sexual harassment allegations + affair killed campaign.", 'commentary_correct': 'Correct! 9-9-9.', 'commentary_wrong': '9-9-9.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Rick Perry's 2012 'oops' moment was?", 'question': "Was?", 'answers': {'A': "Forgetting the third agency he'd cut in debate", 'B': "Falling off stage", 'C': "Both", 'D': "Misquoting Reagan"}, 'correct': 'A', 'explanation': "November 2011 GOP debate. 'Commerce, Education, and...uh...oops.' Could not remember Energy Dept. Crushed campaign.", 'commentary_correct': 'Correct! The Oops.', 'commentary_wrong': 'The Oops.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Anthony Weiner's 2013 mayoral campaign collapsed because?", 'question': "Because?", 'answers': {'A': "Second sexting scandal under alias 'Carlos Danger'", 'B': "Bad polling", 'C': "Both A and B", 'D': "Endorsement loss"}, 'correct': 'A', 'explanation': "After 2011 sexting, Weiner ran for mayor. Second scandal mid-campaign. Came in 5th. Eventually went to prison.", 'commentary_correct': 'Correct! Carlos Danger.', 'commentary_wrong': 'Carlos Danger.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Carly Fiorina's 2016 campaign best moment was?", 'question': "Best moment?", 'answers': {'A': "The 'main stage' debate after exiting kids' table", 'B': "Iowa victory", 'C': "Both A — and Trump's 'look at that face' jab", 'D': "VP pick"}, 'correct': 'C', 'explanation': "Fiorina earned main-debate spot. Trump mocked her appearance. She responded sharply. Boost then fizzled.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "Bill Clinton's 1988 nominating speech was?", 'question': "Was?", 'answers': {'A': "Famously too long — booed", 'B': "Brilliant", 'C': "Both A — but launched him into 1992 win", 'D': "Cancelled"}, 'correct': 'A', 'explanation': "1988 Dukakis nominating speech. 32 minutes. Booed for length. 'In conclusion' got biggest applause.", 'commentary_correct': 'Correct! Too long.', 'commentary_wrong': 'Too long.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Political Campaigns', 'setup': "George McGovern's 1972 campaign lost how many states?", 'question': "Lost how many?", 'answers': {'A': "49 states (Nixon swept all but MA + DC)", 'B': "30 states", 'C': "10 states", 'D': "All 50"}, 'correct': 'A', 'explanation': "Nixon won 49 states. McGovern won Massachusetts + DC only. Most lopsided electoral loss in modern history.", 'commentary_correct': 'Correct! 49 states.', 'commentary_wrong': '49 states.', 'difficulty': 'medium', 'time_limit': 15},

    # DISNEY PARK DISASTERS
    {'category': 'Disney Park Disasters', 'setup': "Splash Mountain at Disney World was rebranded as?", 'question': "Renamed to?", 'answers': {'A': "Tiana's Bayou Adventure (2024)", 'B': "Stayed the same", 'C': "Removed entirely", 'D': "Frozen Mountain"}, 'correct': 'A', 'explanation': "Removed Song of the South-themed ride. Reopened as Princess and the Frog themed Tiana's Bayou Adventure June 2024.", 'commentary_correct': 'Correct! Tiana\'s Bayou.', 'commentary_wrong': 'Tiana\'s Bayou.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Walt Disney World's saddest record involves?", 'question': "Involves?", 'answers': {'A': "Body-of-water lawsuits", 'B': "Alligator attack on 2-year-old (2016) at Grand Floridian", 'C': "Both — Disney now fences water features", 'D': "Disappearing visitors"}, 'correct': 'C', 'explanation': "June 2016. Lane Graves killed by alligator. Disney installed fences/signs at all water features in response.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Tragic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disneyland's animatronic Lincoln has historically?", 'question': "Has historically?", 'answers': {'A': "Suffered multiple high-profile malfunctions", 'B': "Always worked perfectly", 'C': "Both A and B", 'D': "Been replaced multiple times"}, 'correct': 'A', 'explanation': "Mr. Lincoln Hall of Presidents has long history of fits and starts. Walt's original 1965 animatronic. Often shut down.", 'commentary_correct': 'Correct! Multiple fails.', 'commentary_wrong': 'Multiple fails.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "It's a Small World ride became famous for?", 'question': "Famous for?", 'answers': {'A': "Being maddeningly catchy with the same loop", 'B': "Multiple ride breakdowns leaving guests stuck", 'C': "Both", 'D': "Disney's first dark ride"}, 'correct': 'C', 'explanation': "Both true. Song loops 7 times for typical ride. Multiple breakdown incidents leave guests trapped with song.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "The 2003 Big Thunder Mountain Disneyland fatality involved?", 'question': "Involved?", 'answers': {'A': "Marcelo Torres killed in derailment", 'B': "Bad maintenance — guard hood missing", 'C': "Both", 'D': "Decommissioning"}, 'correct': 'C', 'explanation': "September 2003. Marcelo Torres died. Cal-OSHA investigation. Maintenance failure. Disney safety overhaul.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disneyland California's first-ever death was?", 'question': "First death?", 'answers': {'A': "1964 — a man fell from the People Mover", 'B': "Never had a death", 'C': "1955 — a child", 'D': "1970s"}, 'correct': 'A', 'explanation': "1964. Mark Maples (15) ignored safety, stood up on Matterhorn, fell out. First Disneyland fatality.", 'commentary_correct': 'Correct! 1964 Matterhorn.', 'commentary_wrong': '1964 Matterhorn.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney's 'Yeti' in Expedition Everest has been?", 'question': "Has been?", 'answers': {'A': "Broken since 2008 — operates as 'disco yeti' with strobe", 'B': "Always working", 'C': "Both — Imagineers can't fix without dismantling mountain", 'D': "Removed"}, 'correct': 'C', 'explanation': "Yeti animatronic broken since shortly after 2006 opening. Structure built around it. Fix would require demolition.", 'commentary_correct': 'Correct! Disco yeti.', 'commentary_wrong': 'Disco yeti since 2008.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney costumed characters break character due to?", 'question': "Break for?", 'answers': {'A': "Aggressive park guests (rare but documented)", 'B': "Heat exhaustion", 'C': "Both — and viral 'character meltdown' videos", 'D': "Sometimes Mickey vs Mickey scuffles"}, 'correct': 'C', 'explanation': "Costumed character meltdowns are a small but consistent issue. Heat, aggressive guests, costume failures.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "The 2010s 'Disney Adults' phenomenon was characterized by?", 'question': "Characterized by?", 'answers': {'A': "Adults without kids visiting parks", 'B': "Mocked on Twitter constantly", 'C': "Both A and B", 'D': "Specifically reviled by Disney"}, 'correct': 'C', 'explanation': "Childless adult Disney enthusiasts became viral discussion topic. Online mockery. Disney embraces them publicly.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney's annual passholder revolts in 2024 were over?", 'question': "Over?", 'answers': {'A': "Pricing + park reservation system + fewer benefits", 'B': "A new ride", 'C': "Both", 'D': "Mascot quality"}, 'correct': 'A', 'explanation': "Disney's blackout dates + reservation requirements + price hikes alienated longtime passholders. Multiple lawsuits.", 'commentary_correct': 'Correct! Pricing/system.', 'commentary_wrong': 'Pricing complaints.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "The original Pirates of the Caribbean ride included?", 'question': "Included?", 'answers': {'A': "Bride auction scene (changed 2018)", 'B': "Pirate prisoner scene", 'C': "Both A — bride auction scene was controversial", 'D': "Just pirates and rum"}, 'correct': 'C', 'explanation': "Original 1967 ride included bride-auction scene. Updated 2018 to be less problematic. POC adventure.", 'commentary_correct': 'Correct! Bride auction.', 'commentary_wrong': 'Bride auction.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney's 'Star Wars Hotel' (Galactic Starcruiser) was killed in?", 'question': "Killed when?", 'answers': {'A': "September 2023 (just 18 months after opening)", 'B': "Still operating", 'C': "2019", 'D': "Never built"}, 'correct': 'A', 'explanation': "Galactic Starcruiser opened March 2022. Closed September 2023. $$5K+ for 2 nights. Too expensive.", 'commentary_correct': 'Correct! Sept 2023.', 'commentary_wrong': 'Sept 2023.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Pop Century / All-Star Music resort dolphins are technically?", 'question': "Technically?", 'answers': {'A': "Just decorations, not real dolphins", 'B': "Trained performers", 'C': "Both", 'D': "Ducks"}, 'correct': 'A', 'explanation': "Resort theming, not real dolphins. Disney has no captive dolphins. EPCOT's Sea has manatees, not dolphins.", 'commentary_correct': 'Correct! Decoration.', 'commentary_wrong': 'Decoration only.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney World 'snake hat' incident was?", 'question': "Was?", 'answers': {'A': "Snakes found in a hat shop souvenir", 'B': "A guest's hat", 'C': "An urban legend (more or less)", 'D': "Both A — and Disney denied it"}, 'correct': 'D', 'explanation': "Various park 'creature in souvenir' urban legends. Disney denies. Snopes-debunked stories persist.", 'commentary_correct': 'Correct! Urban legend.', 'commentary_wrong': 'Urban legend.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disneyland Paris (originally Euro Disney) lost?", 'question': "Lost?", 'answers': {'A': "$1B+ in first 2 years", 'B': "Wine wars (had to allow wine sales)", 'C': "Both", 'D': "Was an immediate hit"}, 'correct': 'C', 'explanation': "Euro Disney opened 1992. Massive losses. Cultural friction. Had to add wine, breaks for French workers. Recovered slowly.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "The 2024 'It's A Small World' boat sinking happened where?", 'question': "Happened where?", 'answers': {'A': "Disneyland Anaheim (yes, boats periodically sink)", 'B': "Disneyland Tokyo", 'C': "Both A and other parks", 'D': "Never happened"}, 'correct': 'C', 'explanation': "Disney boats occasionally take on water. Small World incidents documented at multiple parks. Boats are evacuated.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Boats do sink.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney's wand-waving 'gate fall' viral video showed?", 'question': "Showed?", 'answers': {'A': "Disney castle wall falling apart in 2024 during storm", 'B': "A guest brawl", 'C': "Both — Disney admitted weather damage", 'D': "Ride evacuation"}, 'correct': 'A', 'explanation': "January 2024. Wall fell at Disneyland during storm. Viral footage. Disney repaired immediately.", 'commentary_correct': 'Correct! Wall fail.', 'commentary_wrong': 'Wall fall.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Most expensive Disney park experience as of 2024?", 'question': "Most expensive?", 'answers': {'A': "Star Wars Galactic Starcruiser (~$5,000 for 2 nights)", 'B': "Club 33 ($25-50K membership initiation)", 'C': "Both — among top-end Disney experiences", 'D': "Disney's Steakhouse 71"}, 'correct': 'C', 'explanation': "Club 33 + Starcruiser were top-tier. Starcruiser closed. Club 33 still active with long waitlists.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "Disney's MagicBand+ replaced what payment system?", 'question': "Replaced what?", 'answers': {'A': "Original MagicBands + room keys + tickets", 'B': "Just cash", 'C': "Both A and B", 'D': "Lanyards"}, 'correct': 'A', 'explanation': "MagicBand+ launched 2022. Replaced original MagicBands. RFID + interactive features. $35-50 each.", 'commentary_correct': 'Correct! Old bands.', 'commentary_wrong': 'Old MagicBands.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Disney Park Disasters', 'setup': "EPCOT's Frozen Ever After ride was originally?", 'question': "Originally?", 'answers': {'A': "Maelstrom (Norwegian/Viking-themed)", 'B': "Always Frozen", 'C': "A coaster", 'D': "Eiffel Tower attraction"}, 'correct': 'A', 'explanation': "Maelstrom ran 1988-2014. Replaced by Frozen Ever After (2016). Controversial swap by Norway fans.", 'commentary_correct': 'Correct! Maelstrom.', 'commentary_wrong': 'Maelstrom Vikings.', 'difficulty': 'hard', 'time_limit': 15},

    # PREDICTIONS THAT AGED POORLY
    {'category': 'Predictions That Aged Poorly', 'setup': "IBM's Thomas Watson reportedly said in 1943?", 'question': "Said?", 'answers': {'A': "'I think there is a world market for maybe five computers.'", 'B': "'Computers will rule the world.'", 'C': "Nothing of the sort", 'D': "Both A and B"}, 'correct': 'A', 'explanation': "Famous quote, disputed sourcing. Whatever the exact words, IBM did underestimate the personal computer market.", 'commentary_correct': 'Correct! 5 computers.', 'commentary_wrong': '5 computers.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Decca Records rejected the Beatles in 1962 saying?", 'question': "Said?", 'answers': {'A': "'Guitar groups are on the way out, Mr. Epstein.'", 'B': "'Too commercial.'", 'C': "Nothing — it's a myth", 'D': "Both A — Dick Rowe said it"}, 'correct': 'D', 'explanation': "Dick Rowe rejected Beatles January 1962. The Beatles signed with Parlophone. Rowe spent rest of career living it down.", 'commentary_correct': 'Correct! Rowe.', 'commentary_wrong': 'Dick Rowe.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Ken Olsen (DEC founder) said in 1977 about home computers?", 'question': "Said?", 'answers': {'A': "'There is no reason for any individual to have a computer in his home.'", 'B': "'Everyone will have a computer.'", 'C': "Nothing", 'D': "He invented Mac"}, 'correct': 'A', 'explanation': "1977. World Future Society. Just before Apple II's launch. Reportedly meant in industrial context.", 'commentary_correct': 'Correct! Ken Olsen.', 'commentary_wrong': 'Ken Olsen quote.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Bill Gates' famous (probably misattributed) 1981 quote was?", 'question': "Was?", 'answers': {'A': "'640K ought to be enough for anybody.'", 'B': "Misattributed, never actually said", 'C': "Both A — quote is real but disputed", 'D': "Said by Steve Jobs"}, 'correct': 'C', 'explanation': "Quote attributed to Gates 1981. Gates denies ever saying it. Famous prediction-fail anecdote regardless.", 'commentary_correct': 'Correct! 640K.', 'commentary_wrong': '640K. Disputed origin.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Newsweek's 1995 'Why the Internet Will Fail' article was by?", 'question': "Author?", 'answers': {'A': "Clifford Stoll", 'B': "Bill Gates", 'C': "Walt Mossberg", 'D': "Someone made-up"}, 'correct': 'A', 'explanation': "Clifford Stoll, February 1995 Newsweek piece. Predicted Internet wouldn't catch on. Particularly humbling.", 'commentary_correct': 'Correct! Stoll.', 'commentary_wrong': 'Cliff Stoll.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Variety in 1955 said about television's future?", 'question': "Said?", 'answers': {'A': "It would replace movies entirely", 'B': "It was a fad that wouldn't last", 'C': "Both — multiple TV predictions failed", 'D': "Color TV would never work"}, 'correct': 'C', 'explanation': "Variety + others made multiple TV-related predictions that failed. TV killed neither movies nor radio.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Time Magazine 2006 'Person of the Year' was?", 'question': "Was?", 'answers': {'A': "You (Web 2.0 users)", 'B': "Steve Jobs", 'C': "Mark Zuckerberg", 'D': "Albert Gore"}, 'correct': 'A', 'explanation': "'You' was 2006 POTY. Web 2.0 era. UGC celebrated. Widely mocked since for naive optimism about user content.", 'commentary_correct': 'Correct! You.', 'commentary_wrong': 'You.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Y2K predictions in 1999 included?", 'question': "Included?", 'answers': {'A': "Plane crashes, bank failures, infrastructure collapse", 'B': "Nothing actually happened", 'C': "Both — minimal real impact", 'D': "Three Mile Island scale disaster"}, 'correct': 'C', 'explanation': "Y2K predictions widely exaggerated. Massive remediation spending. Few real issues materialized.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Paul Krugman in 1998 said about Internet?", 'question': "Said?", 'answers': {'A': "Its impact would be no greater than fax machines", 'B': "It would change everything", 'C': "Both — he later acknowledged the prediction was wrong", 'D': "He never made tech predictions"}, 'correct': 'C', 'explanation': "Nobel economist Krugman wrote it. Later acknowledged the prediction was wrong. Used as cautionary tale.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Fax-level impact.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The 1962 World's Fair predicted by 2000 we'd have?", 'question': "Predicted?", 'answers': {'A': "Flying cars and undersea cities", 'B': "Personal computers in every home", 'C': "Both A and B", 'D': "Spaceship vacations"}, 'correct': 'A', 'explanation': "Multiple Seattle 1962 predictions: flying cars, undersea hotels, atomic power. Mostly didn't happen.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The 2000s 'Peak Oil' prediction said oil would run out by?", 'question': "By when?", 'answers': {'A': "Various predictions ranging 2010-2030", 'B': "1990", 'C': "2050", 'D': "Never made"}, 'correct': 'A', 'explanation': "Peak Oil theories dominated 2000s discourse. Fracking + new reserves blew up predictions.", 'commentary_correct': 'Correct! Various.', 'commentary_wrong': 'Various — all wrong.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The 1900s prediction about humans was that we'd?", 'question': "Predicted?", 'answers': {'A': "Develop telepathy by 2000 via brain-wave radio", 'B': "Stop using cars", 'C': "Both A — typical pseudo-scientific projection", 'D': "Live underwater"}, 'correct': 'A', 'explanation': "Multiple 1900s predictions about brain-wave telepathy, mass-mind-reading. None materialized.", 'commentary_correct': 'Correct! Telepathy.', 'commentary_wrong': 'Telepathy.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Steve Ballmer in 2007 said about iPhone?", 'question': "Said?", 'answers': {'A': "'No chance the iPhone is going to get any significant market share.'", 'B': "Praised it", 'C': "Said nothing", 'D': "Bought one"}, 'correct': 'A', 'explanation': "Microsoft CEO Ballmer dismissed iPhone. 'Most expensive phone in the world.' Aged poorly.", 'commentary_correct': 'Correct! Ballmer fail.', 'commentary_wrong': 'Ballmer\'s laugh.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The 1920s 'cars are a fad' prediction was?", 'question': "By whom?", 'answers': {'A': "President of Michigan Savings Bank advising client against Ford investment", 'B': "Multiple bankers and economists", 'C': "Both", 'D': "An urban legend"}, 'correct': 'C', 'explanation': "1903 advice to Henry Ford investor: 'horse is here to stay, automobile is only a novelty.' Real anecdote.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Movie critics' worst-ever predictions about future hits?", 'question': "Examples?", 'answers': {'A': "Roger Ebert hating multiple Tarantino films", 'B': "Star Wars 'wouldn't make money'", 'C': "Both A and B", 'D': "Anything about Marvel"}, 'correct': 'C', 'explanation': "Multiple wrong predictions in film history. Star Wars marketed as guaranteed flop pre-release. Spectacular hit.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Albert Einstein in 1932 said about nuclear power?", 'question': "Said?", 'answers': {'A': "'There is not the slightest indication that nuclear energy will ever be obtainable.'", 'B': "Predicted Hiroshima", 'C': "Nothing", 'D': "It would be peaceful only"}, 'correct': 'A', 'explanation': "Einstein 1932 prediction. 13 years later Hiroshima. Most spectacularly wrong scientific prediction.", 'commentary_correct': 'Correct! Einstein wrong.', 'commentary_wrong': 'Einstein wrong.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The 1980s 'Year 2000 ozone hole' predictions were?", 'question': "Were?", 'answers': {'A': "Largely accurate (Montreal Protocol prevented worst)", 'B': "Wildly wrong", 'C': "Both — predicted disaster, action prevented it", 'D': "Misunderstood"}, 'correct': 'C', 'explanation': "Ozone hole was real. 1987 Montreal Protocol banned CFCs. Now slowly healing. Rare prediction-success story.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Lord Kelvin (1895) said about heavier-than-air flight?", 'question': "Said?", 'answers': {'A': "'Impossible.'", 'B': "Predicted it correctly", 'C': "Both — and 8 years before Wright Brothers", 'D': "Said only birds could"}, 'correct': 'C', 'explanation': "Kelvin 1895: 'Heavier-than-air flying machines are impossible.' Wright Brothers 1903 proved him wrong.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "The Onion's 2009 prediction headline 'Last Newspaper Reader Dies' said?", 'question': "Said?", 'answers': {'A': "Joked that no one would read newspapers by 2030", 'B': "Predicted exact year", 'C': "Was correct so far", 'D': "Both A — and parody"}, 'correct': 'D', 'explanation': "The Onion's satire often becomes uncomfortably accurate. Newspaper decline real but slower than joked.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Predictions That Aged Poorly', 'setup': "Crypto bro 'Bitcoin to $1M by 2025' predictions were?", 'question': "Were?", 'answers': {'A': "Common in 2021 bull run", 'B': "Mostly wrong by 2025", 'C': "Both", 'D': "Right on time"}, 'correct': 'C', 'explanation': "Multiple 2021 predictions of BTC $1M by 2025. Reality: ~$95K-100K range. Wrong predictions, common.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
]


def seed_v4_batch2d():
    ph = get_placeholder()
    added = 0
    for q in V4_BATCH2D_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (cat['id'], q['question'], q.get('setup','') or '',
                  q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                  q['correct'], q.get('difficulty','medium'), q.get('time_limit',15),
                  q.get('explanation',''), q.get('commentary_correct',''), q.get('commentary_wrong','')))
            added += 1
        except Exception as e:
            print(f"[v4-b2d] {e}")
    print(f"✅ v4 batch2d added {added} ({len(V4_BATCH2D_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch2d()
