"""v4 batch 2a — 5 of the 25 batch-2 categories. 20 questions each.
Categories: Failed Music Festivals, Lottery Winners Who Lost Everything,
Pizza Crimes, One-Hit Wonders Who Vanished, Tattoo Regrets of the Famous.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH2A_QUESTIONS = [
    # FAILED MUSIC FESTIVALS
    {'category': 'Failed Music Festivals', 'setup': 'Fyre Festival (2017) was promoted by Billy McFarland and which rapper?', 'question': 'Co-promoter?', 'answers': {'A': 'Ja Rule', 'B': '50 Cent', 'C': 'Kanye West', 'D': 'Drake'}, 'correct': 'A', 'explanation': 'Ja Rule co-founded with McFarland. McFarland got 6 years prison. Ja Rule walked.', 'commentary_correct': 'Correct! Ja Rule.', 'commentary_wrong': 'Ja Rule. Walked free.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Fyre attendees famously received what infamous meal?', 'question': 'Meal was?', 'answers': {'A': 'Cheese sandwich and salad in a styrofoam box', 'B': 'Lobster and champagne', 'C': 'Nothing for 12 hours', 'D': 'Fast food drive-thru'}, 'correct': 'A', 'explanation': 'Tweet photo of sad cheese sandwich went viral. Promoted as "gourmet."', 'commentary_correct': 'Correct! Sad cheese sandwich.', 'commentary_wrong': 'Cheese sandwich. Iconic.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Woodstock \'99 ended in?', 'question': 'Ended in?', 'answers': {'A': 'Riots, fires, and sexual assault reports', 'B': 'Peaceful celebration', 'C': 'A Beatles reunion', 'D': 'A surprise Dylan appearance'}, 'correct': 'A', 'explanation': 'Limp Bizkit-fueled chaos. $4 water. Trash fires. Multiple assault reports. Documentary on Netflix.', 'commentary_correct': 'Correct! Chaos.', 'commentary_wrong': 'Total chaos.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'DashCon (2014) was a Tumblr fan convention famous for?', 'question': 'Famous for?', 'answers': {'A': 'A sad ball pit with one inflatable child pool', 'B': 'A celebrity no-show', 'C': 'Both A and B', 'D': 'A successful event'}, 'correct': 'C', 'explanation': 'Pittsburgh 2014. Welch Pavilion ball pit was tiny. Speakers canceled. Iconic Tumblr fail.', 'commentary_correct': 'Correct! Both. Sad ball pit.', 'commentary_wrong': 'Both. The ball pit.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Altamont Free Concert (1969) had Rolling Stones playing as?', 'question': 'What happened?', 'answers': {'A': 'A man was stabbed to death by Hells Angels security', 'B': 'A power outage', 'C': 'A blizzard', 'D': 'A police raid'}, 'correct': 'A', 'explanation': 'Hells Angels hired as security. Meredith Hunter stabbed during Stones set. Captured in Gimme Shelter doc.', 'commentary_correct': 'Correct! Stabbing.', 'commentary_wrong': 'Stabbing. Hells Angels.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Pukkelpop 2011 (Belgium) was hit by what?', 'question': 'Hit by?', 'answers': {'A': 'A sudden severe thunderstorm killing 5', 'B': 'A riot', 'C': 'A fire', 'D': 'Nothing'}, 'correct': 'A', 'explanation': 'Severe storm collapsed stage rigging. 5 dead, 140 injured. Festival canceled.', 'commentary_correct': 'Correct! Storm.', 'commentary_wrong': 'Severe storm.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Cancun-based "Tomorrowland Mexico" was canceled in 2014 because?', 'question': 'Why?', 'answers': {'A': 'Tomorrowland never licensed it — pure scam', 'B': 'Weather', 'C': 'Government refusal', 'D': 'No tickets sold'}, 'correct': 'A', 'explanation': 'Fake festival used Tomorrowland branding without permission. Promoters disappeared with ticket money.', 'commentary_correct': 'Correct! Scam.', 'commentary_wrong': 'Scam. Fake brand.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Astroworld Festival (2021) ended with how many crowd-crush deaths?', 'question': 'Deaths?', 'answers': {'A': '10', 'B': '1', 'C': '3', 'D': '25'}, 'correct': 'A', 'explanation': 'November 2021. Travis Scott concert. 10 killed in crowd crush. Multiple lawsuits.', 'commentary_correct': 'Correct! 10.', 'commentary_wrong': '10. Tragic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Glastonbury 2005 was famously flooded after how many inches of rain?', 'question': 'Approximate rainfall?', 'answers': {'A': '~3 inches in 1 hour', 'B': '~1 inch in a day', 'C': '~10 inches', 'D': '~0.5 inches'}, 'correct': 'A', 'explanation': 'Flash flood. Tents swept away. Festival continued in mud. Glastonbury\'s "mudbath" year.', 'commentary_correct': 'Correct! ~3 inches.', 'commentary_wrong': '~3 inches. Famous mud year.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Lollapalooza was originally a?', 'question': 'Originally a what?', 'answers': {'A': 'Touring festival, then became Chicago-based', 'B': 'Single-city festival', 'C': 'Online-only event', 'D': 'Reality show'}, 'correct': 'A', 'explanation': 'Started 1991 as traveling tour. Restarted 2005 as Chicago festival. Now multiple international locations.', 'commentary_correct': 'Correct! Touring originally.', 'commentary_wrong': 'Touring originally.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'TomorrowWorld 2015 (Georgia, US) was canceled mid-festival because?', 'question': 'Why?', 'answers': {'A': 'Heavy rain made site unreachable; thousands stranded', 'B': 'Police shut it down', 'C': 'A fire', 'D': 'A musician quit'}, 'correct': 'A', 'explanation': 'Day 3 canceled. Thousands stranded with no transport, no food. Never returned to US.', 'commentary_correct': 'Correct! Rain stranding.', 'commentary_wrong': 'Rain. Thousands stranded.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Roskilde 2000 (Denmark) Pearl Jam set had what tragedy?', 'question': 'What happened?', 'answers': {'A': '9 fans died in a crowd crush', 'B': 'A stage collapse', 'C': 'Equipment fire', 'D': 'Nothing'}, 'correct': 'A', 'explanation': 'June 30, 2000. 9 fans crushed during Pearl Jam performance. Major reforms in crowd management.', 'commentary_correct': 'Correct! 9 deaths.', 'commentary_wrong': '9 deaths. Crowd crush.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'The Roo (Bonnaroo) name comes from?', 'question': 'Comes from?', 'answers': {'A': 'A Lil Wayne album', 'B': 'A Dr. John album', 'C': 'A Stevie Wonder song', 'D': 'A made-up word'}, 'correct': 'B', 'explanation': '"Desitively Bonnaroo" — 1974 Dr. John album. Means "really good" in Cajun.', 'commentary_correct': 'Correct! Dr. John.', 'commentary_wrong': 'Dr. John album.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Ultra Music Festival 2019 moved to Virginia Key and was?', 'question': 'Was?', 'answers': {'A': 'Logistically disastrous; ferry/bus chaos', 'B': 'A success', 'C': 'Canceled', 'D': 'Combined with Lollapalooza'}, 'correct': 'A', 'explanation': 'Forced move from Bayfront Park. Transport to Virginia Key was a mess. Multi-hour waits. Festival apologized.', 'commentary_correct': 'Correct! Logistical mess.', 'commentary_wrong': 'Transport disaster.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'The "Magnolia Music Festival" of 2018 was based in?', 'question': 'Where?', 'answers': {'A': 'Mississippi (and was a scam)', 'B': 'New Orleans', 'C': 'Memphis', 'D': 'Nashville'}, 'correct': 'A', 'explanation': 'Mississippi-based ticketing scam. Lineup never confirmed. Promoter disappeared with funds.', 'commentary_correct': 'Correct! Mississippi scam.', 'commentary_wrong': 'Mississippi scam.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Bloomberg estimated Fyre Festival\'s losses to attendees and investors at approximately?', 'question': 'How much?', 'answers': {'A': '$26 million in losses', 'B': '$1 million', 'C': '$100 million', 'D': 'Just ticket refunds'}, 'correct': 'A', 'explanation': '$26M from investors plus ticket holders\' losses. Class action lawsuits ongoing.', 'commentary_correct': 'Correct! ~$26M.', 'commentary_wrong': '~$26M.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Hella Mega Tour was supposed to feature Green Day, Weezer, and?', 'question': 'And who?', 'answers': {'A': 'Fall Out Boy', 'B': 'Blink-182', 'C': 'Panic! at the Disco', 'D': 'My Chemical Romance'}, 'correct': 'A', 'explanation': 'Green Day + Weezer + Fall Out Boy. Postponed due to COVID, eventually toured 2021-22.', 'commentary_correct': 'Correct! Fall Out Boy.', 'commentary_wrong': 'Fall Out Boy.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Vans Warped Tour ended in?', 'question': 'When?', 'answers': {'A': '2018 (as cross-country tour)', 'B': '2012', 'C': '2020', 'D': 'Still active'}, 'correct': 'A', 'explanation': 'Final cross-country Warped Tour was 2018. 25th anniversary one-offs followed.', 'commentary_correct': 'Correct! 2018.', 'commentary_wrong': '2018. End of an era.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'Burning Man\'s 2023 disaster was caused by?', 'question': 'By what?', 'answers': {'A': 'Heavy rain turning playa to mud, stranding 73,000', 'B': 'Wildfire', 'C': 'Government shutdown', 'D': 'Riots'}, 'correct': 'A', 'explanation': 'September 2023. Rain made playa impassable mud. Tens of thousands stranded for days.', 'commentary_correct': 'Correct! Mud.', 'commentary_wrong': 'Mud. 73K stranded.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Failed Music Festivals', 'setup': 'The infamous "Cult of the Dead Cow" hacker group prank-streamed at what festival?', 'question': 'Which fest?', 'answers': {'A': 'DEF CON (annually a tradition)', 'B': 'Lollapalooza', 'C': 'SXSW', 'D': 'Coachella'}, 'correct': 'A', 'explanation': 'DEF CON hacker convention. cDc has made annual appearances. Not really a music festival but tradition.', 'commentary_correct': 'Correct! DEF CON.', 'commentary_wrong': 'DEF CON.', 'difficulty': 'hard', 'time_limit': 15},

    # LOTTERY WINNERS WHO LOST EVERYTHING
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Jack Whittaker won $314 million in 2002. By 2007?', 'question': 'By 2007?', 'answers': {'A': 'Bankrupt, grandkids dead from drugs, multiple lawsuits', 'B': 'Doubled his fortune', 'C': 'Donated it all', 'D': 'Still rich'}, 'correct': 'A', 'explanation': 'Jack Whittaker. Multiple tragedies. Granddaughter Brandi died of overdose. Robbed multiple times. Lawsuits.', 'commentary_correct': 'Correct! Tragic decline.', 'commentary_wrong': 'Tragic decline.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Michael Carroll (UK, 2002) won £9.7M and is famous for?', 'question': 'Famous for?', 'answers': {'A': 'Calling himself "King of Chavs"', 'B': 'Building a museum', 'C': 'Donating to charity', 'D': 'Hiding his identity'}, 'correct': 'A', 'explanation': 'Self-styled "King of Chavs." Lost everything by 2012. Worked in coal yard.', 'commentary_correct': 'Correct! King of Chavs.', 'commentary_wrong': 'King of Chavs.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'William "Bud" Post won $16.2M in 1988. He died in?', 'question': 'When?', 'answers': {'A': '2006, bankrupt and on food stamps', 'B': 'Wealthy', 'C': 'Donating to charity', 'D': '1990 (drug overdose)'}, 'correct': 'A', 'explanation': 'Bankrupt by 2006. Brother hired hitman. Multiple lawsuits. Died penniless.', 'commentary_correct': 'Correct! 2006, broke.', 'commentary_wrong': '2006, broke.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Evelyn Adams won the NJ lottery twice (1985 and 1986). By 2001?', 'question': 'Status?', 'answers': {'A': 'Lived in a trailer; she had gambled it all away', 'B': 'Tripled it', 'C': 'Donated everything', 'D': 'Both A and gambling addiction'}, 'correct': 'D', 'explanation': '$5.4M total. Gambled in Atlantic City. By 2001 lived in trailer. Heartbreaking story.', 'commentary_correct': 'Correct! Gambled it.', 'commentary_wrong': 'Gambled it. Trailer.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Lara Wills won £1M in 1996 but became famous when?', 'question': 'What happened?', 'answers': {'A': 'She kept her clerical job because she liked it', 'B': 'She got divorced', 'C': 'She vanished', 'D': 'A and the press hounded her'}, 'correct': 'D', 'explanation': 'She stayed at her old job. Press attention drove her to retire and emigrate. UK media frenzy.', 'commentary_correct': 'Correct! Kept job, hounded.', 'commentary_wrong': 'Kept her job.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Andrew Whittaker\'s lottery curse continued when?', 'question': 'What also happened?', 'answers': {'A': 'A bag of $545,000 cash was stolen from his SUV at a strip club', 'B': 'His house burned down', 'C': 'His helicopter crashed', 'D': 'His son committed fraud'}, 'correct': 'A', 'explanation': 'Stolen from inside Pink Pony strip club. 2003. Recovered most. Still lost millions over years.', 'commentary_correct': 'Correct! Strip club theft.', 'commentary_wrong': 'Strip club theft.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Sharon Tirabassi won $10M in 2004. By 2013?', 'question': 'Status?', 'answers': {'A': 'Riding the bus to work, broke', 'B': 'Wealthy', 'C': 'Property investor', 'D': 'Married to royalty'}, 'correct': 'A', 'explanation': 'Ontario, Canada. Lost it all in 9 years on cars, homes, friends. Back to bus rides.', 'commentary_correct': 'Correct! On the bus.', 'commentary_wrong': 'Back to the bus.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'A 2002 study by Camelot (UK lottery operator) found what?', 'question': 'Found what?', 'answers': {'A': '~44% of winners are broke within 5 years', 'B': 'Winners are mostly happy', 'C': 'No effect on finances', 'D': 'Most win again'}, 'correct': 'A', 'explanation': 'Multiple studies show 30-70% of winners go broke. Lack of financial planning, family demands.', 'commentary_correct': 'Correct! ~44%.', 'commentary_wrong': '~44% broke in 5 years.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Vivian Nicholson won £152K in 1961 UK pools. Famous for?', 'question': 'Famous for?', 'answers': {'A': 'Telling press she planned to "spend, spend, spend!"', 'B': 'Donating everything', 'C': 'Hiding her win', 'D': 'Becoming a Member of Parliament'}, 'correct': 'A', 'explanation': '£152K = millions today. By 1965 she was broke. Her words became a UK catchphrase. Wrote a memoir.', 'commentary_correct': 'Correct! Spend, spend, spend!', 'commentary_wrong': 'Spend, spend, spend!', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Cuong "Charlie" Kim Truong won $13M in 1986. He?', 'question': 'He?', 'answers': {'A': 'Was murdered for the money by associates', 'B': 'Donated everything', 'C': 'Disappeared with all money', 'D': 'Wisely invested'}, 'correct': 'A', 'explanation': 'Murdered in 1987 by associates. The lottery curse claimed many.', 'commentary_correct': 'Correct! Murdered.', 'commentary_wrong': 'Murdered. Tragic.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Abraham Shakespeare won $30M in 2006 Florida lottery. He was found?', 'question': 'Found?', 'answers': {'A': 'Dead, buried under concrete by Dee Dee Moore who managed his money', 'B': 'Healthy', 'C': 'Living abroad', 'D': 'Just retired'}, 'correct': 'A', 'explanation': '2010. "Friend" Dorice Moore convicted of murder. Found buried under his property in concrete.', 'commentary_correct': 'Correct! Murdered, buried.', 'commentary_wrong': 'Murdered. Concrete.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'A typical financial advice book recommends what after winning a lottery?', 'question': 'What\'s suggested?', 'answers': {'A': 'Take lump sum and forget the rest', 'B': 'Stay anonymous if state allows; hire team of advisors immediately', 'C': 'Spend it fast before you change your mind', 'D': 'Donate everything'}, 'correct': 'B', 'explanation': 'Standard advice: anonymity + advisors + cooling-off period. Many states require public identification.', 'commentary_correct': 'Correct! Anonymity + team.', 'commentary_wrong': 'Anonymity + advisors.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Joe Johnson won $10K weekly for life in 1988. He spent it on?', 'question': 'Spent on?', 'answers': {'A': 'A mansion, then bankruptcy', 'B': 'A racing team', 'C': 'A failed restaurant chain', 'D': 'All of the above'}, 'correct': 'D', 'explanation': 'Multiple failed businesses. Bankruptcy. Common lottery winner pattern.', 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three. Common pattern.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Tonda Lynn Dickerson, a Waffle House waitress, won the lottery from a tip in?', 'question': 'When did this happen?', 'answers': {'A': '1999 — and was sued by her coworkers for the share', 'B': '2005', 'C': '2012', 'D': '1995'}, 'correct': 'A', 'explanation': 'Customer gave winning ticket as tip. Coworkers sued, claiming shared agreement. Tonda won the legal battle.', 'commentary_correct': 'Correct! Waffle House drama.', 'commentary_wrong': 'Waffle House. Legal battle.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'A 2018 Connecticut winner kept her identity secret using?', 'question': 'Using what?', 'answers': {'A': 'A trust', 'B': 'Her husband', 'C': 'A fake name', 'D': 'Her dog'}, 'correct': 'A', 'explanation': 'Trusts allow lottery winners to remain anonymous in states that permit. Many wealthy winners use them.', 'commentary_correct': 'Correct! Trust.', 'commentary_wrong': 'Trust setup.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'A 1998 Illinois winner was murdered by his sister-in-law for the money. He?', 'question': 'He?', 'answers': {'A': 'Was poisoned in his home — found dead within months of winning', 'B': 'Survived', 'C': 'Donated all winnings before death', 'D': 'Was a fictional case'}, 'correct': 'A', 'explanation': 'Real case. Family members killed lottery winners is a recurring tragedy. Multiple documented cases.', 'commentary_correct': 'Correct! Family murder.', 'commentary_wrong': 'Family murder.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'The lump-sum vs annuity payment choice is roughly?', 'question': 'Typical ratio?', 'answers': {'A': 'Lump sum is ~60% of advertised value before taxes', 'B': 'Lump sum is 100%', 'C': 'Lump sum is 25%', 'D': 'Both pay the same'}, 'correct': 'A', 'explanation': '~50-70% of "jackpot" value. Then federal/state taxes. The "billion-dollar jackpot" is much less in hand.', 'commentary_correct': 'Correct! ~60% before tax.', 'commentary_wrong': '~60%. Then taxes.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Lottery winners are most likely to be sued by?', 'question': 'Most likely sued by?', 'answers': {'A': 'Estranged family members claiming share', 'B': 'The government', 'C': 'Banks', 'D': 'Lottery commission'}, 'correct': 'A', 'explanation': 'Long-lost relatives commonly emerge with claims. Sometimes legitimate. Often not.', 'commentary_correct': 'Correct! Estranged family.', 'commentary_wrong': 'Family lawsuits.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'Donna Mikkin won $34.5M in 2007. She wrote a book called?', 'question': 'Book?', 'answers': {'A': 'How Winning the Lottery Led to Emotional Bankruptcy', 'B': 'Easy Money', 'C': 'Lottery Mom', 'D': 'I Got Mine'}, 'correct': 'A', 'explanation': 'Real book. Mikkin described depression after winning. Lottery winners often face mental health struggles.', 'commentary_correct': 'Correct! Emotional Bankruptcy.', 'commentary_wrong': 'Emotional Bankruptcy. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Lottery Winners Who Lost Everything', 'setup': 'A 2018 study found lottery winners tend to be?', 'question': 'Tend to be?', 'answers': {'A': 'Less satisfied with life 5+ years out', 'B': 'Always happier', 'C': 'Both A and have higher suicide rates', 'D': 'A and divorce rates spike'}, 'correct': 'D', 'explanation': 'Lottery winners often report decreased life satisfaction long-term. Divorce rates spike. Family rifts.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real research.', 'difficulty': 'medium', 'time_limit': 15},

    # PIZZA CRIMES
    {'category': 'Pizza Crimes', 'setup': 'In 2007, a man robbed a bank with a fake bomb. He had what taped to him?', 'question': 'Taped to him?', 'answers': {'A': 'A pizza delivery uniform', 'B': 'A real bomb (locked on by a kidnapper)', 'C': 'A note', 'D': 'A GPS tracker'}, 'correct': 'B', 'explanation': 'Brian Wells, pizza delivery man. 2003 collar bomb death. Forced by accomplices to rob bank. Bomb exploded killing him.', 'commentary_correct': 'Correct! Real bomb.', 'commentary_wrong': 'Real bomb. Tragic case.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A Domino\'s delivery man in 2017 famously did what?', 'question': 'Did what?', 'answers': {'A': 'Robbed his own customers using the uniform', 'B': 'Stole pizzas from other drivers', 'C': 'Both A and B happen repeatedly', 'D': 'Won a Pulitzer'}, 'correct': 'C', 'explanation': 'Multiple cases of pizza-uniform robberies. Domino\'s has investigated countless incidents.', 'commentary_correct': 'Correct! Both. Common.', 'commentary_wrong': 'Both. Common.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'Papa John founder John Schnatter was forced out of his own company because of?', 'question': 'Because?', 'answers': {'A': 'Racial slur on a conference call (2018)', 'B': 'Embezzlement', 'C': 'Tax fraud', 'D': 'Selling secrets'}, 'correct': 'A', 'explanation': 'Schnatter used a racial slur in 2018 conference call. Forced to resign as chairman. Years of controversy followed.', 'commentary_correct': 'Correct! Slur on call.', 'commentary_wrong': 'Slur. Out as chairman.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2011 pizza fraud was perpetrated by what?', 'question': 'What scam?', 'answers': {'A': 'Fake "Domino\'s" website redirecting payments', 'B': 'Pizza delivery man stealing tips', 'C': 'A fake pizza shop in Mafia movie set', 'D': 'All happened in real cases'}, 'correct': 'D', 'explanation': 'Pizza-related fraud is varied. Fake websites, employee theft, organized crime fronts.', 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'New York City Mafia controlled pizza shops as fronts. Famous "Pizza Connection" case found what?', 'question': 'Found what?', 'answers': {'A': 'Heroin distributed through pizzeria-network', 'B': 'Counterfeit bills', 'C': 'Tax evasion', 'D': 'Bookmaking'}, 'correct': 'A', 'explanation': '1980s "Pizza Connection." Heroin trafficked through Italian-American pizzerias. Major federal case.', 'commentary_correct': 'Correct! Heroin.', 'commentary_wrong': 'Heroin. Pizzeria fronts.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A robber demanded what at a Domino\'s in 2014?', 'question': 'Demanded what?', 'answers': {'A': 'Free pizza for life (in writing)', 'B': 'A specific topping', 'C': 'The CEO\'s home address', 'D': 'A delivery scooter'}, 'correct': 'A', 'explanation': 'Real case. Robber demanded free pizza for life. Refused. Caught quickly.', 'commentary_correct': 'Correct! Lifetime pizza.', 'commentary_wrong': 'Lifetime pizza.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2018 customer-fraud case involved someone using what to steal pizzas?', 'question': 'Tool?', 'answers': {'A': 'Stolen credit card numbers', 'B': 'Fake delivery accounts', 'C': 'Both', 'D': 'A printed coupon'}, 'correct': 'C', 'explanation': 'Online pizza fraud is rampant. Stolen credit cards used for delivery orders. Massive losses to chains.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A pizza chain employee in 2008 went viral for putting?', 'question': 'For putting what on pizza?', 'answers': {'A': 'Cheese up his nose, then on a pizza for delivery', 'B': 'Toothpaste', 'C': 'Pepper spray', 'D': 'Both A and B (different incidents)'}, 'correct': 'A', 'explanation': 'Domino\'s 2009 video. Employees fired and prosecuted. Caused major PR crisis for Domino\'s.', 'commentary_correct': 'Correct! Nose cheese.', 'commentary_wrong': 'Nose cheese.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'Little Caesars in 2013 won a famous lawsuit against?', 'question': 'Won against?', 'answers': {'A': 'A pizza chain knocking off "Hot-N-Ready"', 'B': 'Domino\'s', 'C': 'Pizza Hut', 'D': 'Papa John\'s'}, 'correct': 'A', 'explanation': 'Little Caesars vigorously defends "Hot-N-Ready" trademark. Multiple suits against competitors.', 'commentary_correct': 'Correct! Trademark.', 'commentary_wrong': 'Trademark suit.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'In 2017, a Domino\'s driver was assaulted because?', 'question': 'Because?', 'answers': {'A': 'A customer didn\'t want to pay', 'B': 'The pizza was cold', 'C': 'Both A and B in different incidents', 'D': 'For wearing a specific color'}, 'correct': 'C', 'explanation': 'Delivery driver assaults are common. Multiple cases per year. Many chains now require delivery in pairs.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'Pizza Hut\'s 2018 driver in the Bronx famously?', 'question': 'Did what?', 'answers': {'A': 'Saved a kidnapping victim by leaving a note in the pizza box', 'B': 'Got robbed by the customer', 'C': 'Knocked over a building', 'D': 'Both A and the customer was charged'}, 'correct': 'A', 'explanation': 'Florida driver noticed something off. Customer wrote "PLEASE HELP" inside the pizza box. Driver called police.', 'commentary_correct': 'Correct! Saved a life.', 'commentary_wrong': 'Saved a life. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2015 pizza delivery prank gone wrong involved?', 'question': 'What happened?', 'answers': {'A': 'A "swatting" by ordering pizza to neighbor', 'B': 'Pizza thrown at house', 'C': 'Both A and B as real incidents', 'D': 'A bridge collapse'}, 'correct': 'C', 'explanation': 'Pizza-related pranks (and crimes) include "swatting" via false pizza orders, and pizza-throwing assaults.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'Dean Norris\'s "Better Call Saul" lawyer character was based on?', 'question': 'Based on?', 'answers': {'A': 'A real Albuquerque attorney', 'B': 'Fictional', 'C': 'A Hollywood lawyer', 'D': 'Saul Goodman is real'}, 'correct': 'B', 'explanation': 'Trick — Saul Goodman is fictional. But pizza-themed criminal lawyer characters in fiction are inspired by real cases.', 'commentary_correct': 'Correct! Fictional.', 'commentary_wrong': 'Fictional. Surprise.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2016 pizzeria employee in Tampa was robbed at gunpoint for?', 'question': 'For what?', 'answers': {'A': 'One single pizza', 'B': 'The cash register', 'C': 'The delivery scooter', 'D': 'All three across different incidents'}, 'correct': 'A', 'explanation': 'Multiple cases of robbery for individual pizzas. One Florida man held up driver for one pie.', 'commentary_correct': 'Correct! One pizza.', 'commentary_wrong': 'One pizza.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2014 New Jersey criminal case found?', 'question': 'Found what?', 'answers': {'A': 'Restaurant skimming credit cards through pizza orders', 'B': 'A money-laundering pizza chain', 'C': 'Both', 'D': 'Tax fraud only'}, 'correct': 'C', 'explanation': 'Multiple cases. Card skimming through restaurants is widespread. Pizza chains and their financial transactions occasionally laundering vehicles.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2019 pizza-related TikTok challenge resulted in?', 'question': 'In what?', 'answers': {'A': 'Multiple arrests for licking food before "putting it back"', 'B': 'Health code violations', 'C': 'Both', 'D': 'A new dance trend'}, 'correct': 'C', 'explanation': 'Food-tampering "challenges" became real legal issues. Several arrests. Health code action.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2018 Pizza Hut promotion accidentally became what?', 'question': 'What?', 'answers': {'A': 'A counterfeit coupon problem (millions of fake codes generated)', 'B': 'A free-pizza disaster', 'C': 'Both', 'D': 'A successful campaign'}, 'correct': 'C', 'explanation': 'Many pizza promotions have triggered viral coupon fraud. Chains have taken massive hits.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'In Italy, pizzeria fronts have been linked to which crime organization?', 'question': 'Which?', 'answers': {'A': 'Camorra (Naples)', 'B': 'Cosa Nostra (Sicily)', 'C': 'Ndrangheta (Calabria)', 'D': 'All have used pizzeria fronts in different cases'}, 'correct': 'D', 'explanation': 'All three major Italian mafia groups have used food businesses (including pizzerias) for money laundering.', 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'A 2020 pizza scam targeted who?', 'question': 'Targeted whom?', 'answers': {'A': 'Elderly buying "free pizza-for-seniors" with stolen card information', 'B': 'Children', 'C': 'Tourists', 'D': 'All — phone-based pizza fraud is common'}, 'correct': 'D', 'explanation': 'Phone-based scams targeting elderly are common. Pizza-themed scams included.', 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pizza Crimes', 'setup': 'In a 2016 incident, a customer threw what at a pizza driver?', 'question': 'Threw what?', 'answers': {'A': 'A pizza box back', 'B': 'A pizza slice', 'C': 'Both A and B happen often', 'D': 'A frying pan'}, 'correct': 'C', 'explanation': 'Pizza-throwing assaults on delivery drivers are sadly common.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},

    # ONE-HIT WONDERS WHO VANISHED
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Lou Bega\'s 1999 hit "Mambo No. 5" reached what chart position?', 'question': 'Position?', 'answers': {'A': '#3 US, #1 in Germany and many countries', 'B': '#1 US', 'C': '#50 US', 'D': 'Never charted'}, 'correct': 'A', 'explanation': '#1 in Germany, France, UK. #3 US. Where is Lou Bega now? Mostly Germany.', 'commentary_correct': 'Correct! #3 US.', 'commentary_wrong': '#3 US.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Aqua\'s "Barbie Girl" came out in?', 'question': 'When?', 'answers': {'A': '1997', 'B': '1995', 'C': '2000', 'D': '1993'}, 'correct': 'A', 'explanation': 'Danish-Norwegian group. Hit #1 in UK. Mattel sued unsuccessfully.', 'commentary_correct': 'Correct! 1997.', 'commentary_wrong': '1997.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Tag Team\'s "Whoomp! (There It Is)" came out in?', 'question': 'When?', 'answers': {'A': '1993', 'B': '1990', 'C': '1997', 'D': '2000'}, 'correct': 'A', 'explanation': 'Atlanta duo. Reached #2 Billboard Hot 100. Still works retail jobs.', 'commentary_correct': 'Correct! 1993.', 'commentary_wrong': '1993.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Crazytown\'s "Butterfly" hit #1 in?', 'question': 'When?', 'answers': {'A': '2001', 'B': '1998', 'C': '2005', 'D': '2010'}, 'correct': 'A', 'explanation': '"Come my lady..." 2001 #1. Lead singer Shifty Shellshock had multiple addiction struggles.', 'commentary_correct': 'Correct! 2001.', 'commentary_wrong': '2001.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Dexy\'s Midnight Runners had "Come On Eileen" in 1982. The lead singer\'s latest work?', 'question': 'Recent activity?', 'answers': {'A': 'Kevin Rowland still tours but no new hits', 'B': 'Won an Oscar', 'C': 'Disappeared', 'D': 'Joined a political party'}, 'correct': 'A', 'explanation': 'Rowland leads a reformed Dexys. No new #1 hits.', 'commentary_correct': 'Correct! Still around.', 'commentary_wrong': 'Still touring.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Right Said Fred ("I\'m Too Sexy", 1991) are?', 'question': 'Still active?', 'answers': {'A': 'Yes — still touring', 'B': 'Disappeared', 'C': 'Joined a cult', 'D': 'Won a Grammy'}, 'correct': 'A', 'explanation': 'Richard and Fred Fairbrass. Still tour. The "Too Sexy" royalties never stopped.', 'commentary_correct': 'Correct! Still touring.', 'commentary_wrong': 'Still touring.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Vanilla Ice ("Ice Ice Baby", 1990) now does what?', 'question': 'Now?', 'answers': {'A': 'Home renovation TV show', 'B': 'Music exclusively', 'C': 'Politics', 'D': 'Disappeared'}, 'correct': 'A', 'explanation': '"The Vanilla Ice Project" on DIY Network. Renovates homes. Still tours occasionally.', 'commentary_correct': 'Correct! Renovation TV.', 'commentary_wrong': 'Home reno.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'A-ha\'s "Take On Me" (1985) was actually preceded by?', 'question': 'Preceded by?', 'answers': {'A': 'An earlier failed version', 'B': 'A completely different band', 'C': 'A Bowie cover', 'D': 'Nothing'}, 'correct': 'A', 'explanation': 'Original 1984 version flopped. Re-recorded version with the iconic video took off in 1985.', 'commentary_correct': 'Correct! Earlier flop.', 'commentary_wrong': 'Earlier flop.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Nena\'s "99 Luftballons" (1983) was sung in?', 'question': 'What language originally?', 'answers': {'A': 'German', 'B': 'English', 'C': 'Both — different versions for different markets', 'D': 'French'}, 'correct': 'C', 'explanation': 'Original German "99 Luftballons" and English "99 Red Balloons" both released. Both hit.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. German and English.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Toni Basil\'s "Mickey" (1981) was originally?', 'question': 'Originally?', 'answers': {'A': 'A song called "Kitty"', 'B': 'A different artist', 'C': 'A jingle', 'D': 'A poem'}, 'correct': 'A', 'explanation': '"Kitty" by Racey (1979). Basil changed gender and added the cheerleader chant.', 'commentary_correct': 'Correct! "Kitty."', 'commentary_wrong': '"Kitty" originally.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Daniel Powter\'s "Bad Day" (2005) was famously used for?', 'question': 'Used for?', 'answers': {'A': 'American Idol elimination song', 'B': 'NFL Sunday', 'C': 'A Coke ad', 'D': 'A Pixar trailer'}, 'correct': 'A', 'explanation': 'Idol used it weekly for elimination montage. Made it a hit. Powter never had another.', 'commentary_correct': 'Correct! Idol.', 'commentary_wrong': 'Idol elimination.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Chumbawamba\'s "Tubthumping" (1997) topped what genre?', 'question': 'Genre?', 'answers': {'A': 'Multiple — pop punk crossover', 'B': 'Country', 'C': 'Classical', 'D': 'Jazz'}, 'correct': 'A', 'explanation': '#6 US, #2 UK. Band was anarchist-punk activists who hated their pop success. Disbanded 2012.', 'commentary_correct': 'Correct! Pop punk.', 'commentary_wrong': 'Pop punk crossover.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Soulja Boy\'s "Crank That" (2007) launched what?', 'question': 'Launched?', 'answers': {'A': 'A viral dance', 'B': 'A clothing line', 'C': 'A console', 'D': 'All of the above eventually'}, 'correct': 'A', 'explanation': 'Viral dance was pioneering for YouTube era. Soulja Boy then declared a console business (didn\'t go well).', 'commentary_correct': 'Correct! Dance.', 'commentary_wrong': 'Dance.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Eiffel 65\'s "Blue (Da Ba Dee)" (1999) members are now from where?', 'question': 'From?', 'answers': {'A': 'Italy (they were always Italian)', 'B': 'France', 'C': 'Germany', 'D': 'America'}, 'correct': 'A', 'explanation': 'Italian band. Despite the French name. "Eiffel 65" was a random Macintosh-generated name.', 'commentary_correct': 'Correct! Italian.', 'commentary_wrong': 'Italian.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Macarena (Los del Río, 1996) topped Billboard for how many weeks?', 'question': 'How long?', 'answers': {'A': '14 weeks', 'B': '4 weeks', 'C': '1 week', 'D': '30 weeks'}, 'correct': 'A', 'explanation': '14 consecutive weeks at #1 — one of the longest runs ever. Two middle-aged Spanish guys.', 'commentary_correct': 'Correct! 14 weeks.', 'commentary_wrong': '14 weeks.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'The Knack\'s "My Sharona" (1979) inspired what later?', 'question': 'Inspired?', 'answers': {'A': 'The Reality Bites soundtrack revival (1994)', 'B': 'A Beyoncé sample', 'C': 'A Madonna remix', 'D': 'A Backstreet Boys cover'}, 'correct': 'A', 'explanation': '1994 Reality Bites used it. Re-charted. Band had broken up but reunited briefly.', 'commentary_correct': 'Correct! Reality Bites.', 'commentary_wrong': 'Reality Bites.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Cher\'s "Believe" (1998) was famous for using what new effect?', 'question': 'New effect?', 'answers': {'A': 'Auto-Tune as audible effect', 'B': 'Reverb', 'C': 'Synthesizer', 'D': 'Echo'}, 'correct': 'A', 'explanation': 'Auto-Tune used artistically for the first time as a noticeable effect. Started a genre.', 'commentary_correct': 'Correct! Auto-Tune.', 'commentary_wrong': 'Auto-Tune. Started a genre.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Lou Reed\'s "Walk on the Wild Side" (1972) was unusual for?', 'question': 'For?', 'answers': {'A': 'Topics about transgender people (Holly came from Miami)', 'B': 'Production quality', 'C': 'Length', 'D': 'A and other taboo topics'}, 'correct': 'D', 'explanation': 'Lyrics referenced Andy Warhol superstars including transgender Holly Woodlawn. Radio-friendly somehow.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Carl Douglas\'s "Kung Fu Fighting" (1974) was recorded?', 'question': 'How was it recorded?', 'answers': {'A': 'In 10 minutes as a B-side', 'B': 'Carefully over a year', 'C': 'During Bruce Lee\'s death scenes', 'D': 'As an ad jingle'}, 'correct': 'A', 'explanation': 'Quickly recorded as B-side. Producer flipped it. Became massive hit. Douglas became one-hit wonder.', 'commentary_correct': 'Correct! 10 minutes.', 'commentary_wrong': '10 minutes. B-side.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'One-Hit Wonders Who Vanished', 'setup': 'Norman Greenbaum\'s "Spirit in the Sky" (1969) reached what position?', 'question': 'Position?', 'answers': {'A': '#3 US (still earns royalties from movie/TV use)', 'B': '#1 US', 'C': '#50 US', 'D': 'Never charted'}, 'correct': 'A', 'explanation': 'Still gets ~$3K+/year in movie/TV royalties. Greenbaum lives modestly on this single song.', 'commentary_correct': 'Correct! #3.', 'commentary_wrong': '#3. Royalty king.', 'difficulty': 'medium', 'time_limit': 15},

    # TATTOO REGRETS OF THE FAMOUS
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Johnny Depp\'s "Winona Forever" tattoo (for Winona Ryder) was modified to?', 'question': 'Modified to?', 'answers': {'A': '"Wino Forever"', 'B': '"Loner Forever"', 'C': 'Removed entirely', 'D': '"Winnie Forever"'}, 'correct': 'A', 'explanation': '1990 tattoo. Modified after breakup. "Wino Forever" — turning regret into self-deprecation.', 'commentary_correct': 'Correct! Wino Forever.', 'commentary_wrong': 'Wino Forever. Iconic.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Pete Davidson removed how many tattoos?', 'question': 'Approximate?', 'answers': {'A': 'Dozens (he\'s an admitted regret tattoo addict)', 'B': '5', 'C': '0', 'D': '100'}, 'correct': 'A', 'explanation': 'Davidson has removed many, including Ariana Grande-related ones. Treatments span years.', 'commentary_correct': 'Correct! Dozens.', 'commentary_wrong': 'Dozens.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Megan Fox got Marilyn Monroe tattoo removed because?', 'question': 'Reason?', 'answers': {'A': 'Felt it represented negative energy', 'B': 'Got married to Brian Austin Green', 'C': 'Both A and the timing', 'D': 'Got a new Marilyn'}, 'correct': 'A', 'explanation': 'Said she didn\'t want to attract similar energy to Monroe\'s tragic life.', 'commentary_correct': 'Correct! Energy reasons.', 'commentary_wrong': 'Energy reasons.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Angelina Jolie famously had what tattoo removed before marrying Brad Pitt?', 'question': 'Removed what?', 'answers': {'A': '"Billy Bob" — name of ex-husband', 'B': 'A dragon', 'C': 'A wedding date', 'D': 'A photo of herself'}, 'correct': 'A', 'explanation': 'Removed Billy Bob Thornton tattoo. Replaced with kids\' coordinates of birth.', 'commentary_correct': 'Correct! Billy Bob.', 'commentary_wrong': 'Billy Bob. Replaced with kids\' coords.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Khloe Kardashian had what tattoo removed?', 'question': 'Removed?', 'answers': {'A': 'A backpiece and lower-back design', 'B': 'A small wrist tattoo', 'C': 'A name tattoo', 'D': 'A and others — multiple removals'}, 'correct': 'D', 'explanation': 'Multiple Kardashian-sister tattoo removals documented on the show. Standard reality TV.', 'commentary_correct': 'Correct! Multiple.', 'commentary_wrong': 'Multiple removals.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'David Beckham has what tattoo on his neck?', 'question': 'Has what?', 'answers': {'A': 'His wife\'s name "Victoria" in Hindi (misspelled)', 'B': 'A dragon', 'C': 'His kids\' names', 'D': 'Nothing'}, 'correct': 'A', 'explanation': 'Famously the Hindi spelling has an error. Sanskrit/Hindi tattoo errors are common in celebrities.', 'commentary_correct': 'Correct! Misspelled Victoria.', 'commentary_wrong': 'Misspelled. Hindi error.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Britney Spears\'s Hebrew tattoo translates to?', 'question': 'Meaning?', 'answers': {'A': 'Nothing — characters in wrong order', 'B': '"Strength"', 'C': '"Love"', 'D': 'Her name'}, 'correct': 'A', 'explanation': 'Letters not in correct order. Hebrew tattoos on celebrities have a famously high error rate.', 'commentary_correct': 'Correct! Gibberish.', 'commentary_wrong': 'Gibberish. Hebrew error.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'A famous celebrity who removed a Holocaust-themed tattoo was?', 'question': 'Who?', 'answers': {'A': 'Justin Bieber (he had a Korean tattoo people thought was a Holocaust reference, was actually JB)', 'B': 'No one', 'C': 'Liam Gallagher', 'D': 'Bono'}, 'correct': 'A', 'explanation': 'Bieber\'s Korean character tattoo was misinterpreted but caused controversy.', 'commentary_correct': 'Correct! Bieber.', 'commentary_wrong': 'Bieber.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Mike Tyson\'s face tattoo was inspired by?', 'question': 'Inspired by?', 'answers': {'A': 'Maori tribal designs (controversial)', 'B': 'Random doodles', 'C': 'An album cover', 'D': 'A movie'}, 'correct': 'A', 'explanation': 'Maori-inspired design. Tyson appropriated it. Maori people criticized. Hangover used in film.', 'commentary_correct': 'Correct! Maori.', 'commentary_wrong': 'Maori-inspired.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Cara Delevingne\'s tattoo regrets include?', 'question': 'Include?', 'answers': {'A': 'A "Made in England" stamp', 'B': 'A lion on her finger (very public)', 'C': 'Both', 'D': 'A face tattoo'}, 'correct': 'C', 'explanation': 'Cara has many small tattoos. "Made in England" foot tattoo and lion finger are most famous.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Justin Bieber has how many tattoos approximately?', 'question': 'Approximate count?', 'answers': {'A': '60+ total', 'B': '5', 'C': '100+', 'D': '20'}, 'correct': 'A', 'explanation': 'Bieber has 60+ tattoos. Some hidden. Religious themes throughout.', 'commentary_correct': 'Correct! 60+.', 'commentary_wrong': '60+.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Cheryl Cole\'s back tattoo is?', 'question': 'What is it?', 'answers': {'A': 'Two large flowers across whole back', 'B': 'A dragon', 'C': 'A unicorn', 'D': 'Tribal pattern'}, 'correct': 'A', 'explanation': '2013 large back piece. Triggered many "ugly tattoo" debates in UK tabloids.', 'commentary_correct': 'Correct! Big back flowers.', 'commentary_wrong': 'Back flowers.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Pamela Anderson\'s "Tommy" tattoo (for Tommy Lee) was modified to?', 'question': 'Modified to?', 'answers': {'A': '"Mommy"', 'B': '"Tomato"', 'C': 'Removed', 'D': '"Tommy" with Xs through it'}, 'correct': 'A', 'explanation': '"Tommy" turned into "Mommy" after their divorce. Iconic celebrity edit.', 'commentary_correct': 'Correct! Mommy.', 'commentary_wrong': 'Tommy → Mommy.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Heidi Klum\'s "Seal" tattoo (for her husband Seal) was?', 'question': 'After their split?', 'answers': {'A': 'Removed via laser', 'B': 'Modified', 'C': 'Kept', 'D': 'Both A and replaced with a sun'}, 'correct': 'A', 'explanation': 'Laser removal after 2014 divorce. Common celebrity move.', 'commentary_correct': 'Correct! Removed.', 'commentary_wrong': 'Laser-removed.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Eve has a famous what tattooed where?', 'question': 'What/where?', 'answers': {'A': 'Pawprints on her chest', 'B': 'A rose on her face', 'C': 'A barcode on her ankle', 'D': 'Her name on her arm'}, 'correct': 'A', 'explanation': 'Iconic 2000s rapper Eve. Her trademark pawprints. Doesn\'t regret it but talks about it often.', 'commentary_correct': 'Correct! Pawprints.', 'commentary_wrong': 'Pawprints.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Aaron Carter had his face covered in?', 'question': 'Face had?', 'answers': {'A': 'Multiple face tattoos including a Medusa', 'B': 'A small star', 'C': 'A clock', 'D': 'Nothing'}, 'correct': 'A', 'explanation': 'Late singer had multiple face tattoos by his death in 2022. Including the Medusa.', 'commentary_correct': 'Correct! Face tats.', 'commentary_wrong': 'Many face tats.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': '50 Cent\'s "Southside" back tattoo had what done?', 'question': 'Done what?', 'answers': {'A': 'Removed after he found a kid who paid for cancer treatment with his tattoo concert money', 'B': 'Recolored', 'C': 'Made larger', 'D': 'Unchanged'}, 'correct': 'D', 'explanation': 'Kept his Southside tattoo. Some celebrities remove regional/gang ties after image changes.', 'commentary_correct': 'Correct! Kept it.', 'commentary_wrong': 'Kept it.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'A common pattern in celebrity tattoo regret is?', 'question': 'Pattern?', 'answers': {'A': 'Foreign-language tattoos with wrong meanings', 'B': 'Partner names', 'C': 'Both A and B', 'D': 'Face tattoos only'}, 'correct': 'C', 'explanation': 'Both top regret categories. Partner names and translation errors.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Demi Lovato has covered what tattoos?', 'question': 'Covered?', 'answers': {'A': 'Multiple recovery-related tattoos', 'B': 'Boyfriend names', 'C': 'Both A and B', 'D': 'Just one'}, 'correct': 'C', 'explanation': 'Demi has gone through many phases including tattoo cover-ups and removals.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Tattoo Regrets of the Famous', 'setup': 'Travis Barker\'s arms are?', 'question': 'Are?', 'answers': {'A': 'Almost entirely covered in tattoos', 'B': 'Tattoo-free', 'C': 'Only have one', 'D': 'Removed all of them'}, 'correct': 'A', 'explanation': 'Blink-182 drummer. Heavily tattooed. Few regrets reported but constantly evolving.', 'commentary_correct': 'Correct! Covered.', 'commentary_wrong': 'Covered.', 'difficulty': 'easy', 'time_limit': 15},
]


def seed_v4_batch2a():
    ph = get_placeholder()
    added = 0
    for q in V4_BATCH2A_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (cat['id'], q['question'], q.get('setup','') or '',
                  q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                  q['correct'], q.get('difficulty','medium'), q.get('time_limit',15),
                  q.get('explanation',''), q.get('commentary_correct',''), q.get('commentary_wrong','')))
            added += 1
        except Exception as e:
            print(f"[v4-b2a] {e}")
    print(f"✅ v4 batch2a added {added} ({len(V4_BATCH2A_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch2a()
