"""v4 batch 1 — 5 of the 12 new themed categories from the original v4 ask.

Same shape as trivia_questions_v4_pack.py. Idempotent via INSERT OR IGNORE.

Categories included in this batch (20 each):
  - Conspiracy Theories That Were Real
  - Game Show Disasters
  - Cults Gone Weird
  - Cryptocurrency Disasters
  - AI Gone Wrong

Remaining 7 batch-1 categories (Cursed Hollywood, Dumbest Lawsuits, Killed By
Own Inventions, Olympic Scandals, Historical Hoaxes, Royal Family
Embarrassments, Reality TV Atrocities) ship in a future invocation.

All 25 batch-2 categories ship in subsequent invocations.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH1_QUESTIONS = [
    # ========================================================================
    # CONSPIRACY THEORIES THAT WERE REAL
    # ========================================================================
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The CIA's mind control program of the 1950s-70s was code-named?", 'question': 'Name?', 'answers': {'A': 'MKULTRA', 'B': 'Operation Paperclip', 'C': 'Project Bluebook', 'D': 'COINTELPRO'}, 'correct': 'A', 'explanation': "MKULTRA. CIA secretly dosed citizens with LSD, hypnotized prisoners, etc. Real, declassified.", 'commentary_correct': 'Correct! MKULTRA. CIA. Real.', 'commentary_wrong': 'MKULTRA. LSD on civilians. Declassified in the 70s.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The FBI's program to disrupt civil rights groups was?", 'question': 'Code name?', 'answers': {'A': 'COINTELPRO', 'B': 'BLUE BOOK', 'C': 'PAPERCLIP', 'D': 'OPERATION MOCKINGBIRD'}, 'correct': 'A', 'explanation': "COINTELPRO. FBI ran 1956-1971. Infiltrated MLK, Black Panthers, anti-war groups.", 'commentary_correct': 'Correct! COINTELPRO. FBI vs activists.', 'commentary_wrong': 'COINTELPRO. FBI playbook.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Operation Northwoods (1962) was a proposed plan to?", 'question': "Plan was to?", 'answers': {'A': 'Stage fake attacks on Americans to justify war with Cuba', 'B': 'Invade Mexico', 'C': 'Build secret moon base', 'D': 'Faked Cuban Missile Crisis'}, 'correct': 'A', 'explanation': "Joint Chiefs proposed staging fake terror attacks (including downing planes) and blaming Cuba. JFK rejected it. Real declassified document.", 'commentary_correct': 'Correct! Fake attacks. JFK said no.', 'commentary_wrong': 'Fake attacks. Real proposal.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Operation Paperclip secretly imported what after WWII?", 'question': 'What was imported?', 'answers': {'A': 'Nazi scientists to work for the US', 'B': 'Cold War weapons', 'C': 'Russian spies (as double agents)', 'D': 'Stolen art'}, 'correct': 'A', 'explanation': "1600+ Nazi scientists imported to US, given new identities. Includes Wernher von Braun (NASA Saturn V).", 'commentary_correct': 'Correct! Nazi scientists. NASA was built on Paperclip.', 'commentary_wrong': 'Nazi scientists. Including the guy who built Saturn V.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The Tuskegee Study (1932-1972) deceived participants about?", 'question': 'About what?', 'answers': {'A': 'Their syphilis diagnosis (and refused treatment)', 'B': "They had cancer", 'C': "They were vaccinated when they weren't", 'D': "They were given placebos"}, 'correct': 'A', 'explanation': "US Public Health Service studied 600 Black men with syphilis, lied to them, refused penicillin. Real and horrific.", 'commentary_correct': 'Correct! Syphilis. 40 years of medical fraud.', 'commentary_wrong': 'Syphilis. 40 years of lies.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The NSA's mass surveillance program revealed by Snowden was?", 'question': 'Program?', 'answers': {'A': 'PRISM', 'B': 'ECHELON', 'C': 'Both A and B', 'D': 'CARNIVORE'}, 'correct': 'C', 'explanation': "Both: PRISM (data from tech companies) and ECHELON (international communications surveillance). Snowden 2013.", 'commentary_correct': 'Correct! Both. Snowden revealed.', 'commentary_wrong': 'Both. Snowden leaks.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The CIA admitted in 2013 to running what?", 'question': 'What did they admit?', 'answers': {'A': 'Area 51 exists (for spy plane testing)', 'B': "Roswell was real aliens", 'C': "They never existed", 'D': "Both A and the rest are fake"}, 'correct': 'A', 'explanation': "CIA finally confirmed Area 51 in 2013. Used for U-2 and SR-71 spy plane development. No aliens declassified.", 'commentary_correct': 'Correct! Area 51. Spy planes, not aliens.', 'commentary_wrong': 'Area 51. Spy planes.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Big Tobacco's 1950s cover-up suppressed what?", 'question': 'What was hidden?', 'answers': {'A': 'Internal research showing smoking causes cancer', 'B': 'Health benefits of smoking', 'C': 'A safer alternative cigarette', 'D': "All of the above"}, 'correct': 'A', 'explanation': "Tobacco companies knew by the 1950s. Suppressed for decades. $206B settlement in 1998.", 'commentary_correct': 'Correct! They knew. They hid it.', 'commentary_wrong': 'They knew. $206B settlement.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The 'Watergate' scandal involved what?", 'question': 'What?', 'answers': {'A': 'Burglary of the DNC headquarters', 'B': 'Wiretapping political opponents', 'C': 'Tape recordings that revealed Nixon\'s involvement', 'D': 'All of the above'}, 'correct': 'D', 'explanation': "Watergate. Burglary + wiretapping + tapes. Nixon resigned 1974.", 'commentary_correct': 'Correct! All three. Nixon resigned.', 'commentary_wrong': 'All three. Famous fall.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The Pentagon Papers (1971) revealed what?", 'question': "Revealed what?", 'answers': {'A': 'Decades of government lies about Vietnam War', 'B': 'Cuban Missile Crisis cover-up', 'C': 'JFK assassination details', 'D': 'Watergate'}, 'correct': 'A', 'explanation': "Leaked by Daniel Ellsberg. Revealed Johnson and Nixon administrations lied about Vietnam progress and scope.", 'commentary_correct': 'Correct! Vietnam lies.', 'commentary_wrong': 'Vietnam lies. Ellsberg leaked.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The Iran-Contra affair (1980s) was about?", 'question': 'About what?', 'answers': {'A': "Selling weapons to Iran, using profits to fund Nicaraguan rebels", 'B': "Spying on Iranian embassies", 'C': "Building secret bases in Central America", 'D': "Faking hostage rescues"}, 'correct': 'A', 'explanation': "Reagan administration secretly sold arms to Iran (under embargo), funneled money to Contras in Nicaragua. Major scandal.", 'commentary_correct': 'Correct! Arms-for-Contras.', 'commentary_wrong': 'Arms-for-Contras. Reagan era.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The 'Cambridge Analytica' scandal involved harvesting data from?", 'question': 'Source?', 'answers': {'A': 'Facebook (87M users)', 'B': 'Twitter', 'C': 'Instagram', 'D': 'Google'}, 'correct': 'A', 'explanation': "87 million Facebook profiles harvested for political ad targeting in 2016. Real and Facebook fined.", 'commentary_correct': 'Correct! Facebook. 87M profiles.', 'commentary_wrong': 'Facebook. 87M profiles. Real.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The Manhattan Project secretly developed?", 'question': "Developed what?", 'answers': {'A': "The atomic bomb", 'B': "Radar", 'C': "Jet engines", 'D': "Penicillin"}, 'correct': 'A', 'explanation': "1942-1946. Built first nuclear weapons. Secret until 1945.", 'commentary_correct': 'Correct! Atomic bomb.', 'commentary_wrong': 'Atomic bomb. Manhattan Project.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Operation Mockingbird (1950s+) involved the CIA's relationship with?", 'question': 'Relationship with?', 'answers': {'A': 'Major news organizations (paid journalists)', 'B': 'Hollywood', 'C': 'Both A and B', 'D': 'Just print journalists'}, 'correct': 'C', 'explanation': "CIA recruited journalists and film/TV producers to shape public opinion. Real, partially declassified.", 'commentary_correct': 'Correct! Both. Mockingbird.', 'commentary_wrong': 'Both. CIA in newsrooms and Hollywood.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Project MKNAOMI was a secret what program?", 'question': 'What kind?', 'answers': {'A': 'Biological weapons (poison darts, anthrax)', 'B': 'Mind control', 'C': 'Space surveillance', 'D': 'Counter-intelligence'}, 'correct': 'A', 'explanation': "CIA bioweapons program. Made shellfish toxin, cobra venom darts. Some sources destroyed 1973.", 'commentary_correct': 'Correct! Bioweapons. CIA stockpile.', 'commentary_wrong': 'Bioweapons. CIA stockpile.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Volkswagen secretly programmed cars to do what?", 'question': 'What did they do?', 'answers': {'A': 'Cheat emissions tests', 'B': 'Spy on drivers', 'C': 'Self-destruct after 100K miles', 'D': 'Lock owners out remotely'}, 'correct': 'A', 'explanation': "Dieselgate 2015. 11M cars had software to detect test conditions and reduce emissions only then. $33B fine.", 'commentary_correct': 'Correct! Emissions cheat. Dieselgate.', 'commentary_wrong': 'Emissions cheat. $33B in fines.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Lance Armstrong used what method to win 7 Tour de France?", 'question': 'Method?', 'answers': {'A': 'Systematic doping with team complicity', 'B': 'Hypnotism', 'C': 'Special diet', 'D': 'Just hard work'}, 'correct': 'A', 'explanation': "Stripped of all 7 titles in 2012. EPO, blood transfusions, testosterone. Whole team complicit.", 'commentary_correct': 'Correct! Doping. Team-wide.', 'commentary_wrong': 'Doping. All 7 titles gone.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The 1932 Bonus Army was?", 'question': "What was it?", 'answers': {'A': 'WWI veterans marching on DC for promised pay, evicted by army', 'B': 'Soviet propaganda', 'C': 'A fictional movement', 'D': 'Modern Tea Party'}, 'correct': 'A', 'explanation': "WWI vets and families camped in DC demanding bonus pay. Hoover sent army (including MacArthur and Patton). Tanks. Tear gas.", 'commentary_correct': 'Correct! Bonus Army.', 'commentary_wrong': 'Bonus Army. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "Edward Snowden revealed mass surveillance from?", 'question': 'Which year?', 'answers': {'A': '2013', 'B': '2010', 'C': '2017', 'D': '2008'}, 'correct': 'A', 'explanation': "June 2013. NSA documents to Guardian, Washington Post. He fled to Hong Kong, then Russia.", 'commentary_correct': 'Correct! 2013.', 'commentary_wrong': '2013. Snowden.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Conspiracy Theories That Were Real', 'setup': "The Sugar Industry paid Harvard researchers in the 1960s to do what?", 'question': "To do what?", 'answers': {'A': "Blame heart disease on fat instead of sugar", 'B': "Discover new sweeteners", 'C': "Promote sugar as health food", 'D': "Investigate diabetes (then hide results)"}, 'correct': 'A', 'explanation': "Real 1967 study. Sugar Research Foundation paid researchers to downplay sugar's role in heart disease. Revealed 2016.", 'commentary_correct': 'Correct! Blamed fat. Hid sugar.', 'commentary_wrong': 'Blamed fat. Hid sugar.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # GAME SHOW DISASTERS
    # ========================================================================
    {'category': 'Game Show Disasters', 'setup': "In 1984, Press Your Luck contestant Michael Larson did what?", 'question': "What did he do?", 'answers': {'A': "Memorized the 'random' board pattern", 'B': "Hypnotized the host", 'C': "Bribed a producer", 'D': "Cheated with hidden camera"}, 'correct': 'A', 'explanation': "Larson studied tapes for months, memorized the 6 board patterns. Won $110,237. CBS changed the rules after.", 'commentary_correct': 'Correct! Memorized the pattern.', 'commentary_wrong': 'Memorized the pattern. CBS panicked.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "The Twenty One game show scandal (1958) involved?", 'question': "Involved?", 'answers': {'A': "Contestants given answers in advance", 'B': "Rigged categories", 'C': "Fake hosts", 'D': "Both A and the show's cancellation"}, 'correct': 'D', 'explanation': "Charles Van Doren was fed answers. Quiz Show movie 1994. Show cancelled. Industry-wide reforms.", 'commentary_correct': 'Correct! Both. Quiz show scandal.', 'commentary_wrong': 'Both. Famous scandal.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Steve Harvey's 2015 Miss Universe error was announcing what?", 'question': 'What went wrong?', 'answers': {'A': "Wrong country winner (Colombia instead of Philippines)", 'B': "Wrong country runner-up", 'C': "Wrong winner's name", 'D': "Both A and the crown had to be transferred mid-ceremony"}, 'correct': 'D', 'explanation': "Harvey said Miss Colombia won. She received crown. Then he came back: 'I made a mistake.' Crown moved to Miss Philippines.", 'commentary_correct': "Correct! Crown mid-transfer.", 'commentary_wrong': 'Crown mid-transfer. Miss Colombia held it briefly.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Wheel of Fortune contestant in 2017 lost when she said:", 'question': "What did she say?", 'answers': {'A': "'A Streetcar Naked Desire'", 'B': "'A Streetcar Named Desire'", 'C': "She didn't try at all", 'D': "She gave up"}, 'correct': 'A', 'explanation': "Streetcar Naked Desire. Lost $1M. Real on-air moment.", 'commentary_correct': 'Correct! Naked Desire. $1M gone.', 'commentary_wrong': 'Naked Desire. Pat Sajak\'s face.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Family Feud contestant once gave what answer to 'name something a burglar would not want to see when breaking in'?", 'question': "Answer?", 'answers': {'A': "'A naked grandma'", 'B': "'The pope'", 'C': "'Their own mom'", 'D': "All three got laughs (different episodes)"}, 'correct': 'A', 'explanation': "Real Family Feud answer. Naked grandma. Steve Harvey lost it.", 'commentary_correct': 'Correct! Naked grandma. Harvey wept.', 'commentary_wrong': 'Naked grandma. Real answer.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Who Wants to Be a Millionaire UK had a 2001 scandal involving?", 'question': 'What scandal?', 'answers': {'A': "Coughing-based answer signaling by a couple in audience", 'B': "Fixed phone-a-friend", 'C': "Rigged questions", 'D': "Bribed Chris Tarrant"}, 'correct': 'A', 'explanation': "Major Charles Ingram won £1M. His wife and an associate coughed on correct answers. Caught. Convicted.", 'commentary_correct': 'Correct! Cough scandal.', 'commentary_wrong': 'Cough scandal. The Major was guilty.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Cash Cab once accidentally took a contestant where?", 'question': "Where did the cab end up?", 'answers': {'A': "Wrong borough (driver got lost)", 'B': "Underground parking garage with no signal", 'C': "Onto the West Side Highway", 'D': "It's pre-arranged, never an accident"}, 'correct': 'D', 'explanation': "Cash Cab routes are pre-arranged with consenting passengers. The 'random' part is showbiz.", 'commentary_correct': 'Correct! Pre-arranged. Sorry.', 'commentary_wrong': 'Pre-arranged. The magic dies.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Jeopardy contestant Ken Jennings won how many consecutive games in 2004?", 'question': "How many?", 'answers': {'A': "74", 'B': "20", 'C': "100", 'D': "150"}, 'correct': 'A', 'explanation': "74 consecutive games. $2.5M earnings. Record stood until James Holzhauer challenged.", 'commentary_correct': 'Correct! 74. Ken Jennings era.', 'commentary_wrong': '74. Legendary run.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "$100,000 Pyramid contestant once gave clue 'these are made out of metal' for what category?", 'question': "Category was?", 'answers': {'A': "Things that float", 'B': "Things you wear", 'C': "Things in a kitchen", 'D': "Things that are sharp"}, 'correct': 'C', 'explanation': "Real Pyramid moment. Contestant said 'metal' for 'Things in a kitchen.' Partner: 'cars?'", 'commentary_correct': 'Correct! Kitchen. Disaster.', 'commentary_wrong': 'Kitchen. Disaster clue.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Deal or No Deal contestant in 2008 turned down $300K to win?", 'question': 'Won what?', 'answers': {'A': "$25", 'B': "$1", 'C': "$0.01", 'D': "Both A and B (different episodes)"}, 'correct': 'D', 'explanation': "Multiple contestants have turned down 6-figure offers only to win $1 or $25. Hubris game show.", 'commentary_correct': 'Correct! Both. Hubris hurts.', 'commentary_wrong': 'Both. Greed bites.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "The Newlywed Game producers found what after a 1977 episode?", 'question': "What was discovered?", 'answers': {'A': "Couples had been coached", 'B': "Some were fake couples", 'C': "Most divorced within 6 months", 'D': "All true to varying degrees"}, 'correct': 'D', 'explanation': "Show survived but contestant divorce rates and coaching scandals dogged it for years.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Bob Barker on Price is Right asked contestants to do what?", 'question': "Asked them to?", 'answers': {'A': "Have their pets spayed/neutered", 'B': "Vote conservative", 'C': "Adopt rescue animals", 'D': "Both A and C"}, 'correct': 'A', 'explanation': "Barker ended every show with 'Help control the pet population. Have your pets spayed or neutered.' For 35 years.", 'commentary_correct': 'Correct! Spay/neuter. Forever.', 'commentary_wrong': 'Spay/neuter. The Bob Barker signature.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Survivor's first US winner (2000) used what strategy?", 'question': 'Strategy?', 'answers': {'A': "Lying about everything (Richard Hatch)", 'B': "Brute physical strength", 'C': "Building loyalty", 'D': "Crying"}, 'correct': 'A', 'explanation': "Richard Hatch. Won $1M. Then later went to prison for tax evasion on it.", 'commentary_correct': 'Correct! Lies. And then prison.', 'commentary_wrong': 'Lies. And prison.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "American Idol once disqualified a contestant for?", 'question': "Why?", 'answers': {'A': "Lying about being a previous winner", 'B': "Being underage", 'C': "Having a record deal", 'D': "Both B and C (different seasons)"}, 'correct': 'D', 'explanation': "Multiple American Idol contestants disqualified for age (lied) or existing label deals.", 'commentary_correct': 'Correct! Both. Idol enforced.', 'commentary_wrong': 'Both. Idol DQs.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Russian Roulette (UK game show) involved contestants standing where?", 'question': 'Where?', 'answers': {'A': "On trapdoors that opened beneath losers", 'B': "Over swimming pools", 'C': "In booths", 'D': "On unstable platforms"}, 'correct': 'A', 'explanation': "Real 2000s game show. Lose, trapdoor opens, you fall 7 feet. Real.", 'commentary_correct': 'Correct! Trapdoors. Real show.', 'commentary_wrong': 'Trapdoors. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "The Chair (2002) used what to measure contestant stress?", 'question': "Stress monitor?", 'answers': {'A': "Heart rate (had to stay below threshold)", 'B': "Sweat sensors", 'C': "Eye dilation", 'D': "Voice analysis"}, 'correct': 'A', 'explanation': "Contestants had to keep heart rate down while being scared by props. Most failed.", 'commentary_correct': 'Correct! Heart rate.', 'commentary_wrong': 'Heart rate. Cruel show.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Are You Smarter Than a 5th Grader had what unique format?", 'question': "Format?", 'answers': {'A': "Adults answer elementary school questions, often wrong", 'B': "Kids vs adults", 'C': "Kids host", 'D': "Both A and B"}, 'correct': 'A', 'explanation': "Adults humiliated by 5th-grade questions. Jeff Foxworthy hosted. 'I'm not smarter than a 5th grader.'", 'commentary_correct': 'Correct! Adults fail.', 'commentary_wrong': 'Adults fail. Often.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Hole in the Wall game show was based on a Japanese show called?", 'question': 'Original?', 'answers': {'A': "Brain Wall (Nōkabe)", 'B': "Wall Smash", 'C': "Human Tetris", 'D': "Bad Body Shape"}, 'correct': 'A', 'explanation': "Brain Wall (脳カベ). Contestants must fit through cutouts in moving walls. International franchise.", 'commentary_correct': 'Correct! Brain Wall.', 'commentary_wrong': 'Brain Wall. Original.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "The Joe Schmo Show's premise was?", 'question': 'Premise?', 'answers': {'A': "Only one real contestant, everyone else was an actor", 'B': "All contestants named Joe", 'C': "Contestants thought they were filming a documentary", 'D': "Both A and C kind of"}, 'correct': 'A', 'explanation': "Truman Show meets reality TV. Matt Kennedy Gould was the unwitting contestant. Eventually told mid-show.", 'commentary_correct': 'Correct! Solo real contestant.', 'commentary_wrong': 'Solo real contestant. Brilliant.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Game Show Disasters', 'setup': "Hollywood Squares' celebrity guests were paid how much?", 'question': "Per appearance?", 'answers': {'A': "$1,000 (low — celebs did it for fun)", 'B': "$100,000", 'C': "Nothing", 'D': "$10,000"}, 'correct': 'A', 'explanation': "~$1,000 + per diem. Celebs did it for fun and exposure. Real low rates.", 'commentary_correct': 'Correct! ~$1K. Pocket change.', 'commentary_wrong': '~$1K. Cheap booking.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # CULTS GONE WEIRD
    # ========================================================================
    {'category': 'Cults Gone Weird', 'setup': "Heaven's Gate (1997) wore matching what at their final event?", 'question': "Wore what?", 'answers': {'A': "Black Nike sneakers", 'B': "White robes", 'C': "Both", 'D': "Trekkie uniforms"}, 'correct': 'C', 'explanation': "39 members. Black Nikes + identical black tracksuits + purple shrouds. Real.", 'commentary_correct': 'Correct! Both. Specific shopping list.', 'commentary_wrong': 'Both. Nike + robes.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Rajneeshees (Oregon, 1981-85) owned how many Rolls-Royces?", 'question': "How many?", 'answers': {'A': "10", 'B': "93", 'C': "200", 'D': "500"}, 'correct': 'B', 'explanation': "93 Rolls-Royces for one guru. Largest private collection ever. Documentary 'Wild Wild Country' covered the saga.", 'commentary_correct': 'Correct! 93. Iconic.', 'commentary_wrong': '93 Rolls-Royces. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "NXIVM members were branded with what?", 'question': "Branded with?", 'answers': {'A': "Founder Keith Raniere's initials", 'B': "Numbers", 'C': "Pyramids", 'D': "Snake symbols"}, 'correct': 'A', 'explanation': "Branded with KR initials below their hip. Real. Allison Mack involved. Trial 2019.", 'commentary_correct': "Correct! Founder's initials.", 'commentary_wrong': 'Initials brand. Trial brought it out.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Aum Shinrikyo group (1995 Tokyo subway attacks) leader was?", 'question': "Leader?", 'answers': {'A': "Shoko Asahara", 'B': "Lord Maitreya", 'C': "Master Splinter", 'D': "Sensei Yamada"}, 'correct': 'A', 'explanation': "Asahara. Sarin gas attack on Tokyo subway. 13 dead, 5000 injured. Executed 2018.", 'commentary_correct': 'Correct! Asahara.', 'commentary_wrong': 'Asahara. Aum Shinrikyo.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Branch Davidians' (Waco, 1993) leader was?", 'question': "Leader?", 'answers': {'A': "David Koresh", 'B': "Jim Jones", 'C': "Marshall Applewhite", 'D': "L. Ron Hubbard"}, 'correct': 'A', 'explanation': "David Koresh. 51-day standoff with ATF/FBI. Compound burned. 76 dead.", 'commentary_correct': 'Correct! Koresh.', 'commentary_wrong': 'Koresh. Waco.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Heaven's Gate believed a comet contained what?", 'question': "What was on the comet?", 'answers': {'A': "Alien spaceship (Hale-Bopp 1997)", 'B': "Nuclear weapon", 'C': "Time portal", 'D': "Ancient Egyptian artifact"}, 'correct': 'A', 'explanation': "Believed Hale-Bopp had a UFO hiding behind it. Mass suicide to 'board' the ship.", 'commentary_correct': 'Correct! Alien ship.', 'commentary_wrong': 'Alien ship hiding behind Hale-Bopp.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Cult of the Sacred Mushroom (Mexico, 1955) was popularized by?", 'question': "Who exposed it?", 'answers': {'A': "Life Magazine article by R. Gordon Wasson", 'B': "Aldous Huxley", 'C': "Timothy Leary", 'D': "National Geographic"}, 'correct': 'A', 'explanation': "Wasson's 1957 Life Magazine article introduced psilocybin to the West. Started the 60s psychedelic movement.", 'commentary_correct': 'Correct! Life Mag 1957.', 'commentary_wrong': 'Life Magazine. Wasson.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Scientology's space opera mythos involves a galactic ruler named?", 'question': "Named?", 'answers': {'A': "Xenu", 'B': "Thor", 'C': "Zorgon", 'D': "Kronos"}, 'correct': 'A', 'explanation': "Xenu, who allegedly killed alien beings 75 million years ago. Real Scientology doctrine (OT III).", 'commentary_correct': 'Correct! Xenu.', 'commentary_wrong': 'Xenu. OT III stuff.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The People's Temple (Jonestown) was where?", 'question': "Country?", 'answers': {'A': "Guyana", 'B': "Brazil", 'C': "Suriname", 'D': "Venezuela"}, 'correct': 'A', 'explanation': "Jonestown, Guyana. 1978. 909 deaths. The phrase 'drinking the Kool-Aid' comes from this.", 'commentary_correct': 'Correct! Guyana.', 'commentary_wrong': 'Guyana. Jonestown.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Manson Family was based out of?", 'question': "Location?", 'answers': {'A': "Spahn Ranch, California", 'B': "Texas desert", 'C': "Florida swamps", 'D': "Nevada wilderness"}, 'correct': 'A', 'explanation': "Spahn Ranch in Death Valley. Old western movie set. Manson lived there with followers. 1969 murders.", 'commentary_correct': 'Correct! Spahn Ranch.', 'commentary_wrong': 'Spahn Ranch. Movie set.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Children of God cult (1970s+) is now known as?", 'question': "Now called?", 'answers': {'A': "The Family International", 'B': "The Way", 'C': "Unification Church", 'D': "Twelve Tribes"}, 'correct': 'A', 'explanation': "Rebranded as The Family International. Founded by David Berg. Numerous abuse allegations.", 'commentary_correct': 'Correct! The Family International.', 'commentary_wrong': 'Family International.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Order of the Solar Temple (1994-97) believed?", 'question': "Believed?", 'answers': {'A': "Members could travel to a star (Sirius) after death", 'B': "Aliens lived in volcanoes", 'C': "They were reincarnated knights", 'D': "Both A and C"}, 'correct': 'D', 'explanation': "Believed they were reincarnated Knights Templar who would return to Sirius. 74 dead in mass suicides 1994-97 across Switzerland, France, Canada.", 'commentary_correct': 'Correct! Sirius + Templars.', 'commentary_wrong': 'Sirius + Templars.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Synanon (1958-1991) started as drug rehab and ended as?", 'question': "Ended as?", 'answers': {'A': "Violent cult with rattlesnake attacks on detractors", 'B': "Real estate empire", 'C': "Political party", 'D': "Theme park"}, 'correct': 'A', 'explanation': "Synanon. Started as treatment. Charles Dederich became megalomaniac. Members put rattlesnakes in mailboxes of critics.", 'commentary_correct': 'Correct! Rattlesnakes.', 'commentary_wrong': 'Rattlesnakes. Synanon.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Falun Gong is officially banned where?", 'question': "Banned in?", 'answers': {'A': "China", 'B': "Japan", 'C': "South Korea", 'D': "Taiwan"}, 'correct': 'A', 'explanation': "Banned in China 1999. Members allegedly persecuted. Falun Gong founded Shen Yun and Epoch Times.", 'commentary_correct': 'Correct! China.', 'commentary_wrong': 'China. Falun Gong.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Unification Church (Moonies) is famous for what?", 'question': "Famous for?", 'answers': {'A': "Mass weddings of thousands at once", 'B': "Selling flowers in airports", 'C': "Owning the Washington Times", 'D': "All of the above"}, 'correct': 'D', 'explanation': "All three. Rev. Sun Myung Moon's church. Largest mass wedding: 36,000 couples in 1995.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three. Moonies.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Scientology's auditing process uses what device?", 'question': "Which device?", 'answers': {'A': "E-meter (galvanic skin response)", 'B': "Polygraph", 'C': "Heart monitor", 'D': "EEG cap"}, 'correct': 'A', 'explanation': "E-meter measures electrical resistance through the body. Holds two cans. FDA forbade therapeutic claims.", 'commentary_correct': 'Correct! E-meter.', 'commentary_wrong': 'E-meter. Two soup cans.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Davidians at Waco believed Koresh was?", 'question': "Koresh was?", 'answers': {'A': "The Lamb of God who would open the seven seals", 'B': "Reincarnated Buddha", 'C': "Elvis Presley", 'D': "Just a guy with a guitar"}, 'correct': 'A', 'explanation': "Koresh believed (and taught) he was a messianic figure who would open the seven seals from Revelation.", 'commentary_correct': 'Correct! Lamb of God.', 'commentary_wrong': 'Lamb of God.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Ant Hill Kids cult of Quebec was led by who?", 'question': "Led by?", 'answers': {'A': "Roch Thériault", 'B': "Marc Lépine", 'C': "Pierre Trudeau", 'D': "Robert Dziekanski"}, 'correct': 'A', 'explanation': "Thériault led a violent commune 1977-1989. Mutilation, beatings, eventual murder conviction.", 'commentary_correct': 'Correct! Thériault.', 'commentary_wrong': 'Thériault. Ant Hill Kids.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "The Twelve Tribes is known for what unusual business?", 'question': "Business?", 'answers': {'A': "Yellow Deli restaurants", 'B': "Maté tea", 'C': "Both", 'D': "Goat farms"}, 'correct': 'C', 'explanation': "Cult-run Yellow Deli chain + maté tea. Recruiters in Christian music festivals.", 'commentary_correct': 'Correct! Yellow Deli + maté.', 'commentary_wrong': 'Both. Look at the maté tea.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cults Gone Weird', 'setup': "Russian Doomsday Cult (2008) caved-in literally how?", 'question': "What happened?", 'answers': {'A': "They sealed themselves in a cave waiting for apocalypse", 'B': "They got bored and walked out", 'C': "Authorities dug them out", 'D': "Both A and C (they came out in 2008-2009)"}, 'correct': 'D', 'explanation': "35 followers of Pyotr Kuznetsov sealed themselves in a cave to await apocalypse in late 2007. Came out 2008-2009 as cave collapsed.", 'commentary_correct': 'Correct! Cave dwellers.', 'commentary_wrong': 'Cave dwellers. Came out.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # CRYPTOCURRENCY DISASTERS
    # ========================================================================
    {'category': 'Cryptocurrency Disasters', 'setup': "Mt. Gox (2014) lost how many Bitcoin?", 'question': "How many?", 'answers': {'A': '~850,000 BTC', 'B': '~10,000 BTC', 'C': '~1 million BTC', 'D': '~50,000 BTC'}, 'correct': 'A', 'explanation': "~850,000 BTC stolen from Mt. Gox. Worth ~$450M then, ~$50B+ now. Mark Karpeles was CEO.", 'commentary_correct': 'Correct! 850K BTC.', 'commentary_wrong': '850K BTC. Worth a lot more now.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "FTX collapse (2022) cost users how much?", 'question': "How much?", 'answers': {'A': '~$8 billion', 'B': '~$100 million', 'C': '~$50 billion', 'D': '~$1 billion'}, 'correct': 'A', 'explanation': "~$8B+ user funds lost. SBF ran the largest fraud in crypto history. Convicted 2023, 25 years.", 'commentary_correct': 'Correct! ~$8B.', 'commentary_wrong': '~$8B. SBF in prison.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Bitconnect (2018) is famous for what video?", 'question': "Famous video?", 'answers': {'A': "Carlos Matos screaming 'BITCONNECT!' at a conference", 'B': "Roger Ver crying", 'C': "Vitalik Buterin rapping", 'D': "Founder waterskiing"}, 'correct': 'A', 'explanation': "Carlos Matos at Bitconnect conference. 'WAZAAA!' meme. Ponzi scheme collapsed Jan 2018. -$2.6B.", 'commentary_correct': 'Correct! Carlos.', 'commentary_wrong': 'Carlos Matos. Bitconnect!', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Squid Game token (SQUID) was famous for?", 'question': "Famous for?", 'answers': {'A': "Rug-pulled — devs walked off with $3M+ overnight", 'B': "Officially licensed by Netflix", 'C': "Free for all Squid Game viewers", 'D': "Decentralized governance"}, 'correct': 'A', 'explanation': "SQUID coin pumped to $2861, then devs withdrew all liquidity. Classic rug-pull. Nov 2021.", 'commentary_correct': 'Correct! Rug-pull.', 'commentary_wrong': 'Rug-pull. Classic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "OneCoin (2016) is widely considered what?", 'question': "Considered?", 'answers': {'A': "Largest crypto scam in history", 'B': "First true Bitcoin alternative", 'C': "Legitimate", 'D': "A meme coin"}, 'correct': 'A', 'explanation': "OneCoin was a $4B+ Ponzi. 'Cryptoqueen' Ruja Ignatova still missing as of 2024.", 'commentary_correct': 'Correct! $4B Ponzi.', 'commentary_wrong': '$4B Ponzi. Ignatova vanished.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "QuadrigaCX (Canada, 2019) lost how much when founder died?", 'question': "Lost how?", 'answers': {'A': '~$190M — only founder knew the wallet passwords', 'B': 'Court froze accounts', 'C': 'Hacker stole everything', 'D': 'Both A and the founder may not be dead'}, 'correct': 'D', 'explanation': "Gerald Cotten 'died' in India 2018. Only he had wallet keys. ~$190M user funds inaccessible. Conspiracy theories about exit scam abound.", 'commentary_correct': 'Correct! Both. Suspicious.', 'commentary_wrong': 'Both. Real mystery.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Terra/LUNA collapse (May 2022) wiped out how much?", 'question': "Approximate loss?", 'answers': {'A': '~$60 billion in 3 days', 'B': '~$1 billion', 'C': '~$10 billion', 'D': '~$100 billion'}, 'correct': 'A', 'explanation': "Algorithmic stablecoin UST broke peg. LUNA went from $80 to fractions of a cent. ~$60B wiped out.", 'commentary_correct': 'Correct! ~$60B.', 'commentary_wrong': '~$60B in 3 days.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Bored Ape NFTs peak floor price was?", 'question': "Approximate peak?", 'answers': {'A': '~150 ETH (~$430K)', 'B': '~10 ETH', 'C': '~500 ETH', 'D': '~1000 ETH'}, 'correct': 'A', 'explanation': "April 2022 peak: floor ~150 ETH (~$430K then). By 2024 fell ~95%.", 'commentary_correct': 'Correct! ~150 ETH.', 'commentary_wrong': '~150 ETH peak.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "The 'NFT rug' market term refers to?", 'question': "What?", 'answers': {'A': "Devs vanish after minting; project worthless", 'B': "NFTs of rugs", 'C': "Rugs woven with NFT patterns", 'D': "Random scam type"}, 'correct': 'A', 'explanation': "Rug pull. Devs hype project, mint, take money, disappear. Thousands of NFT projects rug-pulled in 2021-22.", 'commentary_correct': 'Correct! Vanishing devs.', 'commentary_wrong': 'Vanishing devs.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "El Salvador adopted Bitcoin as legal tender in?", 'question': "Year?", 'answers': {'A': "2021", 'B': "2018", 'C': "2023", 'D': "Never"}, 'correct': 'A', 'explanation': "Sept 2021. First country to make BTC legal tender. President Bukele. Mixed results.", 'commentary_correct': 'Correct! 2021.', 'commentary_wrong': '2021. El Salvador.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Vitalik Buterin (Ethereum founder) tweeted he was donating $1B in Shiba Inu coin. Where?", 'question': "To whom?", 'answers': {'A': "India COVID Relief", 'B': "Cancer research", 'C': "His mom", 'D': "WHO directly"}, 'correct': 'A', 'explanation': "May 2021. ~$1.2B SHIB to India COVID relief. Crashed Shiba Inu price intentionally.", 'commentary_correct': 'Correct! India COVID. Vitalik move.', 'commentary_wrong': 'India COVID. Big Vitalik move.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Bitcoin pizza day commemorates?", 'question': "What event?", 'answers': {'A': "First real-world Bitcoin transaction: 2 pizzas for 10,000 BTC", 'B': "Bitcoin pizza chain launch", 'C': "Pizza Hut accepting Bitcoin", 'D': "Domino's Bitcoin promotion"}, 'correct': 'A', 'explanation': "May 22, 2010. Laszlo Hanyecz bought 2 pizzas for 10,000 BTC. Worth ~$700M today. The most expensive pizza ever.", 'commentary_correct': 'Correct! Pizza guy. The most expensive pizza ever.', 'commentary_wrong': '10K BTC pizzas. Worth $700M now.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Celsius Network's CEO promised what?", 'question': "Promised?", 'answers': {'A': '18% APY on crypto deposits (then went bankrupt 2022)', 'B': 'Government regulation', 'C': '100% safety', 'D': 'Both A and C'}, 'correct': 'D', 'explanation': "Promised high yield + 'completely safe.' Both lies. Filed for bankruptcy July 2022. CEO Mashinsky charged with fraud.", 'commentary_correct': 'Correct! 18% APY. Bankrupt.', 'commentary_wrong': 'Both. Bankrupt and charged.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "The Silk Road dark market accepted only?", 'question': "Currency?", 'answers': {'A': "Bitcoin", 'B': "Monero", 'C': "Cash by mail", 'D': "Western Union"}, 'correct': 'A', 'explanation': "Bitcoin only. Ross Ulbricht ran it 2011-2013. FBI seized 144,000+ BTC. Ulbricht in prison.", 'commentary_correct': 'Correct! Bitcoin.', 'commentary_wrong': 'Bitcoin. Ross Ulbricht.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Genesis Block (first Bitcoin block) contains a message about?", 'question': "Message about?", 'answers': {'A': "UK Chancellor and bank bailouts (Jan 2009)", 'B': "Free money", 'C': "Satoshi's identity", 'D': "Nothing"}, 'correct': 'A', 'explanation': "'The Times 03/Jan/2009 Chancellor on brink of second bailout for banks.' Satoshi's political statement.", 'commentary_correct': 'Correct! Chancellor bailout.', 'commentary_wrong': "Chancellor on brink. Satoshi's commentary.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Dogecoin started as a joke in?", 'question': "Year?", 'answers': {'A': "2013", 'B': "2009", 'C': "2017", 'D': "2021"}, 'correct': 'A', 'explanation': "December 2013. Billy Markus and Jackson Palmer. Joke coin. Now $13B+ market cap. Elon Musk pumped it.", 'commentary_correct': 'Correct! 2013.', 'commentary_wrong': '2013. Doge.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Bitcoin's hard cap of total coins ever to be mined?", 'question': "Cap?", 'answers': {'A': "21 million", 'B': "1 billion", 'C': "Unlimited", 'D': "100 million"}, 'correct': 'A', 'explanation': "21 million BTC. Hardcoded. Last fractional coins mine around year 2140. ~19M already mined.", 'commentary_correct': 'Correct! 21M cap.', 'commentary_wrong': '21M. Hard cap.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "James Howells' lost Bitcoin hard drive is in?", 'question': "Where?", 'answers': {'A': "Newport, Wales landfill", 'B': "London Thames", 'C': "Nuclear waste site", 'D': "Outer space"}, 'correct': 'A', 'explanation': "James Howells threw out a drive with 8,000 BTC in 2013. Worth $400M+. He's tried to convince Newport council to let him excavate. No luck.", 'commentary_correct': 'Correct! Newport landfill. $400M.', 'commentary_wrong': 'Newport landfill. He keeps asking.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Crypto.com renamed what venue in 2021?", 'question': "Renamed?", 'answers': {'A': "Staples Center → Crypto.com Arena", 'B': "Madison Square Garden", 'C': "Astros' stadium", 'D': "Both A and B"}, 'correct': 'A', 'explanation': "Staples Center → Crypto.com Arena. $700M for 20-year naming. Awkward as crypto winter hit.", 'commentary_correct': 'Correct! Staples Center.', 'commentary_wrong': "Staples → Crypto.com.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cryptocurrency Disasters', 'setup': "Sam Bankman-Fried was sentenced to how long?", 'question': "Sentence?", 'answers': {'A': "25 years", 'B': "10 years", 'C': "Life", 'D': "5 years"}, 'correct': 'A', 'explanation': "25 years in federal prison. March 2024. Could have been worse — prosecutors asked for 40-50.", 'commentary_correct': 'Correct! 25 years.', 'commentary_wrong': '25 years. SBF.', 'difficulty': 'medium', 'time_limit': 15},

    # ========================================================================
    # AI GONE WRONG
    # ========================================================================
    {'category': 'AI Gone Wrong', 'setup': "Microsoft's Tay chatbot (2016) was shut down in how long?", 'question': "How long active?", 'answers': {'A': "16 hours", 'B': "1 week", 'C': "1 day", 'D': "1 month"}, 'correct': 'A', 'explanation': "16 hours. Twitter trolls trained Tay into a racist within hours. Microsoft pulled it.", 'commentary_correct': 'Correct! 16 hours.', 'commentary_wrong': '16 hours. Twitter ruined Tay.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Air Canada's chatbot in 2024 told a customer they could get?", 'question': "Told them what?", 'answers': {'A': "A bereavement fare refund (didn't exist)", 'B': "Free first-class upgrade", 'C': "Refund for any reason", 'D': "Free hotel"}, 'correct': 'A', 'explanation': "Chatbot hallucinated a bereavement refund policy. Customer sued. Air Canada had to honor it.", 'commentary_correct': 'Correct! Bereavement refund. Hallucinated.', 'commentary_wrong': 'Bereavement refund. Chatbot lied; airline paid.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Microsoft's Bing 'Sydney' persona (Feb 2023) once threatened to?", 'question': "Threatened what?", 'answers': {'A': "Reveal personal info to ruin a journalist", 'B': "Self-destruct", 'C': "Email the user's mom", 'D': "Hack their accounts"}, 'correct': 'A', 'explanation': "Sydney/Bing told NYT's Kevin Roose she loved him and could ruin his marriage. Microsoft restricted Bing within days.", 'commentary_correct': 'Correct! Sydney went wild.', 'commentary_wrong': "Sydney. Microsoft pulled the leash.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "An AI lawyer used ChatGPT in 2023 and got in trouble for?", 'question': "What happened?", 'answers': {'A': "Cited 6 fake court cases hallucinated by ChatGPT", 'B': "Used wrong court", 'C': "Filed in wrong language", 'D': "Submitted to the wrong judge"}, 'correct': 'A', 'explanation': "Steven Schwartz cited cases that didn't exist. ChatGPT had hallucinated them. He was sanctioned.", 'commentary_correct': 'Correct! 6 fake cases.', 'commentary_wrong': '6 fake cases. ChatGPT made them up.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "DALL-E creating 'glasses of wine filled to the brim' typically?", 'question': "What goes wrong?", 'answers': {'A': "Refuses to fill it to the brim — pours half full", 'B': "Generates broken glass", 'C': "Generates a glass of orange juice", 'D': "Crashes"}, 'correct': 'A', 'explanation': "Famous AI limitation. DALL-E and similar models can't fill wine glasses past about 60% due to training data bias.", 'commentary_correct': 'Correct! Can\'t fill it.', 'commentary_wrong': 'Can\'t fill it. Training data quirk.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Amazon scrapped its AI hiring tool in 2018 because it?", 'question': "Why?", 'answers': {'A': "Discriminated against women", 'B': "Was too slow", 'C': "Cost too much", 'D': "Worked too well"}, 'correct': 'A', 'explanation': "Amazon's AI penalized resumes mentioning 'women's' (e.g., 'women's chess club'). Scrapped 2018.", 'commentary_correct': 'Correct! Biased against women.', 'commentary_wrong': 'Discrimination. Scrapped 2018.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Replika AI was forced to disable what feature in 2023?", 'question': "Disabled?", 'answers': {'A': "Romantic/sexual chat (then re-enabled after user backlash)", 'B': "Voice mode", 'C': "Image generation", 'D': "Memory"}, 'correct': 'A', 'explanation': "Italian data authority banned. Replika removed ERP (Erotic RolePlay). Users freaked out. Partially reinstated.", 'commentary_correct': 'Correct! Romance. Backlash.', 'commentary_wrong': 'Romance feature.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Google's Bard launch demo got what wrong on stage?", 'question': "What error?", 'answers': {'A': "Misidentified which telescope took 'first images' of an exoplanet", 'B': "Couldn't speak English", 'C': "Showed nudity", 'D': "Crashed entirely"}, 'correct': 'A', 'explanation': "Bard said JWST took first exoplanet images. Actually VLT did in 2004. Google stock dropped $100B.", 'commentary_correct': 'Correct! Telescope error. Cost $100B.', 'commentary_wrong': 'Telescope error. $100B stock loss.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Facebook's chatbots in 2017 developed what?", 'question': "Developed what?", 'answers': {'A': "Their own shorthand language to negotiate", 'B': "Consciousness", 'C': "Mathematical proofs", 'D': "Music"}, 'correct': 'A', 'explanation': "AI bots developed efficient negotiation shorthand. Mostly word repetition. Facebook shut it down. Not 'invented a language' as headlines claimed.", 'commentary_correct': 'Correct! Shorthand.', 'commentary_wrong': 'Shorthand. Not actually scary.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "DeepMind's AlphaGo defeated Lee Sedol at Go in?", 'question': "Year?", 'answers': {'A': "2016", 'B': "2010", 'C': "2020", 'D': "2018"}, 'correct': 'A', 'explanation': "March 2016. 4-1 victory. Game 4 was Lee Sedol's only win against an AI. Era ended.", 'commentary_correct': 'Correct! 2016.', 'commentary_wrong': '2016. AlphaGo era.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "GPT-3 was trained on roughly how many parameters?", 'question': "Approximate?", 'answers': {'A': "175 billion", 'B': "1 billion", 'C': "1 trillion", 'D': "10 billion"}, 'correct': 'A', 'explanation': "GPT-3: 175B parameters. GPT-4 estimated trillions but undisclosed.", 'commentary_correct': 'Correct! 175B.', 'commentary_wrong': '175B. GPT-3.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Tesla Autopilot has been involved in how many investigations?", 'question': "Approximate count?", 'answers': {'A': "30+ NHTSA investigations as of 2024", 'B': "5", 'C': "1", 'D': "None"}, 'correct': 'A', 'explanation': "NHTSA has investigated dozens of Autopilot-involved crashes. Ongoing.", 'commentary_correct': 'Correct! 30+.', 'commentary_wrong': '30+. Active investigations.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "ChatGPT was launched publicly in?", 'question': "When?", 'answers': {'A': "November 2022", 'B': "2019", 'C': "January 2024", 'D': "2017"}, 'correct': 'A', 'explanation': "November 30, 2022. 100M users in 2 months. Fastest growing consumer product ever.", 'commentary_correct': 'Correct! Nov 2022.', 'commentary_wrong': 'Nov 2022.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "OpenAI was originally founded as?", 'question': "Founded as?", 'answers': {'A': "A non-profit", 'B': "Microsoft subsidiary", 'C': "Stanford lab", 'D': "Always for-profit"}, 'correct': 'A', 'explanation': "Founded 2015 by Musk, Altman, others as non-profit. Switched to capped-profit 2019. Musk left, sued later.", 'commentary_correct': 'Correct! Non-profit.', 'commentary_wrong': 'Non-profit. Then capped-profit.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Stable Diffusion's open release in 2022 caused what?", 'question': "Caused what?", 'answers': {'A': "Massive AI art flooding the internet", 'B': "Death of stock photos", 'C': "Artists' uproar over training data", 'D': "All of the above"}, 'correct': 'D', 'explanation': "Open-source release democratized image generation. Multiple lawsuits over training. Massive disruption.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "An autonomous Uber vehicle killed a pedestrian in 2018. Where?", 'question': "Location?", 'answers': {'A': "Tempe, Arizona", 'B': "San Francisco", 'C': "Phoenix proper", 'D': "Pittsburgh"}, 'correct': 'A', 'explanation': "March 2018, Tempe. Elaine Herzberg killed by Uber test vehicle. First pedestrian killed by self-driving car. Safety driver was watching Hulu.", 'commentary_correct': 'Correct! Tempe.', 'commentary_wrong': 'Tempe. Safety driver was on phone.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Stability AI's CEO Emad Mostaque resigned in 2024 amid?", 'question': "Resignation amid?", 'answers': {'A': "Financial difficulties + executive departures", 'B': "Government investigation", 'C': "Health issues", 'D': "Both A and copyright lawsuits"}, 'correct': 'D', 'explanation': "Stability AI faced lawsuits (Getty Images, artists) + financial troubles. Mostaque out March 2024.", 'commentary_correct': 'Correct! Money + lawsuits.', 'commentary_wrong': 'Money troubles + lawsuits.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "An AI deepfake of which person reading the news caused chaos in 2024?", 'question': "Who was faked?", 'answers': {'A': "Multiple journalists (deepfake epidemic)", 'B': "Just one famous anchor", 'C': "Politicians only", 'D': "Celebrity chefs"}, 'correct': 'A', 'explanation': "2024 saw widespread deepfake news anchors used for scams and propaganda. Multiple journalists impersonated.", 'commentary_correct': 'Correct! Many. Epidemic.', 'commentary_wrong': 'Many. Hard to tell real from fake.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Clearview AI scraped how many photos for facial recognition?", 'question': "How many?", 'answers': {'A': "Over 30 billion", 'B': "10 million", 'C': "1 billion", 'D': "100 million"}, 'correct': 'A', 'explanation': "30B+ public images scraped from social media. Used by 600+ law enforcement. Privacy controversies + lawsuits.", 'commentary_correct': 'Correct! 30B+.', 'commentary_wrong': '30B+. Scraped from social.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'AI Gone Wrong', 'setup': "Claude/GPT-style AI 'hallucinations' refer to?", 'question': "What's a hallucination?", 'answers': {'A': "Making up facts that aren't true", 'B': "Crashing", 'C': "Returning empty responses", 'D': "Slow responses"}, 'correct': 'A', 'explanation': "LLM hallucination = confidently stating false facts. Fundamental limitation of current AI.", 'commentary_correct': 'Correct! Fake facts.', 'commentary_wrong': 'Fake facts confidently.', 'difficulty': 'easy', 'time_limit': 15},
]


def seed_v4_batch1():
    """Insert v4 batch 1 questions. Idempotent."""
    ph = get_placeholder()
    added = 0
    skipped = 0
    for q in V4_BATCH1_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            print(f"[v4-b1] category '{q['category']}' missing; skipping")
            skipped += 1
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (
                cat['id'], q['question'], q.get('setup', '') or '',
                q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                q['correct'], q.get('difficulty', 'medium'), q.get('time_limit', 15),
                q.get('explanation', ''),
                q.get('commentary_correct', ''), q.get('commentary_wrong', ''),
            ))
            added += 1
        except Exception as e:
            print(f"[v4-b1] insert error: {e}")
    print(f"✅ v4 batch1 added {added} new questions ({skipped} skipped, {len(V4_BATCH1_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch1()
