"""v4 batch 2b — 5 more batch-2 categories. 100 questions.
Categories: Award Show Mishaps, Drunk Animal Stories, MLM Pyramid Schemes,
Cooking Show Meltdowns, Movie Sequels Nobody Asked For.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH2B_QUESTIONS = [
    # AWARD SHOW MISHAPS
    {'category': 'Award Show Mishaps', 'setup': "The 2017 Oscars Best Picture envelope mix-up handed the wrong award to?", 'question': "Which film was wrongly announced?", 'answers': {'A': "La La Land (actual winner: Moonlight)", 'B': "Moonlight (actual winner: La La Land)", 'C': "The Shape of Water", 'D': "Manchester by the Sea"}, 'correct': 'A', 'explanation': "Warren Beatty and Faye Dunaway given wrong envelope. Moonlight crew came up mid-speech. PwC apologized.", 'commentary_correct': 'Correct! La La Land called.', 'commentary_wrong': 'La La Land was the wrong one announced.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Will Smith slapped Chris Rock at which awards in 2022?", 'question': "Which ceremony?", 'answers': {'A': "The Oscars", 'B': "The Emmys", 'C': "The Grammys", 'D': "MTV Awards"}, 'correct': 'A', 'explanation': "94th Academy Awards. Smith slapped Rock over a Jada joke. Won Best Actor 30 minutes later. Banned 10 years.", 'commentary_correct': 'Correct! Oscars.', 'commentary_wrong': 'Oscars. The slap heard \'round the world.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Kanye West interrupted whom at the 2009 VMAs?", 'question': "Interrupted whom?", 'answers': {'A': "Taylor Swift", 'B': "Beyoncé", 'C': "Lady Gaga", 'D': "Britney Spears"}, 'correct': 'A', 'explanation': "Taylor Swift won Best Female Video. Kanye grabbed mic: 'Imma let you finish but Beyoncé...' Real cultural moment.", 'commentary_correct': 'Correct! Taylor.', 'commentary_wrong': 'Taylor. Imma let you finish.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Steve Harvey announced the wrong winner at Miss Universe 2015. The mix-up was between?", 'question': "Between?", 'answers': {'A': "Miss Colombia and Miss Philippines", 'B': "Miss USA and Miss Russia", 'C': "Miss Brazil and Miss Italy", 'D': "Miss Spain and Miss Mexico"}, 'correct': 'A', 'explanation': "Harvey crowned Miss Colombia. Came back: 'I made a mistake.' Crown moved to Miss Philippines.", 'commentary_correct': 'Correct! Colombia/Philippines.', 'commentary_wrong': 'Colombia → Philippines mid-ceremony.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "At the 2013 Oscars, what fashion-related thing happened to Jennifer Lawrence?", 'question': "What happened?", 'answers': {'A': "She tripped going up to accept Best Actress", 'B': "She forgot her speech", 'C': "She dropped her statue", 'D': "Her dress tore"}, 'correct': 'A', 'explanation': "Tripped on her Dior gown. Made it relatable. Won anyway. Iconic Jennifer Lawrence moment.", 'commentary_correct': 'Correct! Tripped.', 'commentary_wrong': 'Tripped. Made her more lovable.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "At the 1972 Oscars, Marlon Brando refused his Best Actor award via?", 'question': "Refused via whom?", 'answers': {'A': "Sacheen Littlefeather, a Native American activist", 'B': "A personal letter", 'C': "His son", 'D': "A typed speech read by Liza Minnelli"}, 'correct': 'A', 'explanation': "Sacheen Littlefeather spoke about Hollywood's treatment of Native Americans. Booed. Apology came 50 years later.", 'commentary_correct': 'Correct! Sacheen Littlefeather.', 'commentary_wrong': 'Sacheen Littlefeather.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Bjork wore what unusual outfit to the 2001 Oscars?", 'question': "Wore what?", 'answers': {'A': "A swan dress", 'B': "A garbage bag", 'C': "Nothing", 'D': "A wedding gown"}, 'correct': 'A', 'explanation': "Swan dress by Marjan Pejoski. Iconic and mocked. Still in MoMA now.", 'commentary_correct': 'Correct! Swan dress.', 'commentary_wrong': 'Swan dress.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "John Travolta mangled what name introducing Idina Menzel at the 2014 Oscars?", 'question': "Pronounced as?", 'answers': {'A': "Adele Dazeem", 'B': "Ineeda Menzo", 'C': "Aldona Mensil", 'D': "Idina Mendoza"}, 'correct': 'A', 'explanation': "'Adele Dazeem' became a meme. Menzel embraced it. Travolta apologized.", 'commentary_correct': 'Correct! Adele Dazeem.', 'commentary_wrong': 'Adele Dazeem.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "At the 1973 Oscars, Roger Moore had to do what when Sacheen Littlefeather refused Brando's award?", 'question': "Moore did what?", 'answers': {'A': "Held the unaccepted Oscar awkwardly", 'B': "Walked off stage", 'C': "Took it home", 'D': "Threw it"}, 'correct': 'A', 'explanation': "Moore presented Best Actor. Stuck holding the statue when speech was refused.", 'commentary_correct': 'Correct! Held it.', 'commentary_wrong': 'Held it awkwardly.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Michael Jackson's 1996 Brit Awards performance was interrupted by?", 'question': "Interrupted by?", 'answers': {'A': "Jarvis Cocker (Pulp) running on stage", 'B': "A power outage", 'C': "Madonna", 'D': "Nothing"}, 'correct': 'A', 'explanation': "Cocker ran on, mooned the audience, mocked MJ's messianic performance. Arrested. Cleared. Legendary.", 'commentary_correct': 'Correct! Jarvis Cocker.', 'commentary_wrong': 'Jarvis Cocker.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "What happened at the 2017 Grammys when Adele won over Beyoncé?", 'question': "What did Adele do?", 'answers': {'A': "Broke her award in half to share with Beyoncé", 'B': "Refused the award", 'C': "Hugged Beyoncé", 'D': "Both A and called Beyoncé the rightful winner"}, 'correct': 'D', 'explanation': "Adele literally broke her Album of the Year Grammy in half on stage. Said Beyoncé deserved it.", 'commentary_correct': 'Correct! Broke it.', 'commentary_wrong': 'Broke it. Honored Beyoncé.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "Marshall Mathers (Eminem) won Best Original Song Oscar in 2003 for?", 'question': "For?", 'answers': {'A': "'Lose Yourself' from 8 Mile", 'B': "'Stan'", 'C': "'My Name Is'", 'D': "'The Real Slim Shady'"}, 'correct': 'A', 'explanation': "Eminem skipped the ceremony, asleep at home. Reflects how unexpected it was. First hip-hop song Oscar.", 'commentary_correct': 'Correct! Lose Yourself.', 'commentary_wrong': 'Lose Yourself. Eminem was sleeping.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "A 2003 Grammy lifetime achievement was awarded to whom posthumously?", 'question': "Posthumous award to?", 'answers': {'A': "Aaliyah, who died in plane crash 2001", 'B': "Princess Diana", 'C': "Frank Sinatra", 'D': "Both A and others"}, 'correct': 'A', 'explanation': "Aaliyah died in 2001 Bahamas plane crash. Multiple posthumous awards.", 'commentary_correct': 'Correct! Aaliyah.', 'commentary_wrong': 'Aaliyah.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "The 2014 Oscar telecast featured a famous selfie by?", 'question': "Whose selfie went viral?", 'answers': {'A': "Ellen DeGeneres", 'B': "Jimmy Kimmel", 'C': "Tom Hanks", 'D': "Meryl Streep alone"}, 'correct': 'A', 'explanation': "Ellen's selfie with multiple celebrities crashed Twitter. Most-retweeted at the time.", 'commentary_correct': 'Correct! Ellen.', 'commentary_wrong': 'Ellen. Crashed Twitter.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "At the 1989 Oscars, Rob Lowe sang with whom in a controversial opening?", 'question': "Sang with?", 'answers': {'A': "Snow White (actress not licensed by Disney)", 'B': "Cinderella", 'C': "Donald Duck", 'D': "Mickey Mouse"}, 'correct': 'A', 'explanation': "Lowe sang 'Proud Mary' with a Snow White. Disney sued. Producer Alan Carr was disgraced.", 'commentary_correct': 'Correct! Snow White.', 'commentary_wrong': 'Snow White. Disney sued.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "At the 1974 Oscars, a streaker ran behind David Niven. Niven famously?", 'question': "Niven did what?", 'answers': {'A': "Quipped about 'shortcomings'", 'B': "Was speechless", 'C': "Walked off", 'D': "Got down to streak too"}, 'correct': 'A', 'explanation': "Robert Opel streaked the stage. Niven: 'Probably the only laugh that man will ever get in his life is by stripping off and showing his shortcomings.'", 'commentary_correct': 'Correct! Shortcomings quip.', 'commentary_wrong': 'Shortcomings quip.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "ABBA's Eurovision-winning 1974 song was?", 'question': "Was?", 'answers': {'A': "'Waterloo'", 'B': "'Dancing Queen'", 'C': "'Take a Chance on Me'", 'D': "'Mamma Mia'"}, 'correct': 'A', 'explanation': "'Waterloo' won Eurovision 1974, launching ABBA's career. Sweden's first Eurovision win.", 'commentary_correct': 'Correct! Waterloo.', 'commentary_wrong': 'Waterloo. ABBA\'s launch.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "MTV banned which 1989 video at the VMAs?", 'question': "Which?", 'answers': {'A': "Madonna's 'Like a Prayer'", 'B': "Cher's 'If I Could Turn Back Time'", 'C': "Both A and B faced restrictions", 'D': "No music video has ever been banned"}, 'correct': 'C', 'explanation': "Both faced bans/edits. Madonna's lost her Pepsi deal too. Cher's was restricted to post-9pm.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "What did Sinead O'Connor do on SNL 1992?", 'question': "Did what?", 'answers': {'A': "Tore up a photo of the Pope", 'B': "Read from the Quran", 'C': "Removed all her clothes", 'D': "Stormed off mid-song"}, 'correct': 'A', 'explanation': "October 3, 1992 SNL. Tore up Pope John Paul II's picture during 'War.' Career-altering.", 'commentary_correct': 'Correct! Pope photo.', 'commentary_wrong': 'Tore up the Pope.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Award Show Mishaps', 'setup': "The 2009 VMAs featured Lady Gaga in what infamous outfit?", 'question': "Outfit?", 'answers': {'A': "Meat dress", 'B': "Egg-shell entrance", 'C': "Bubbles", 'D': "Wrong year — meat dress was 2010"}, 'correct': 'D', 'explanation': "Trick — meat dress was 2010 MTV VMAs. Often misremembered as 2009.", 'commentary_correct': 'Correct! 2010, not 2009.', 'commentary_wrong': 'Meat dress was 2010.', 'difficulty': 'hard', 'time_limit': 15},

    # DRUNK ANIMAL STORIES
    {'category': 'Drunk Animal Stories', 'setup': "Swedish moose get drunk on what fruit?", 'question': "What fruit?", 'answers': {'A': "Fermented apples", 'B': "Berries", 'C': "Cherries", 'D': "Both A and B"}, 'correct': 'D', 'explanation': "Fermented fall apples and berries. Moose become aggressive while drunk. Real annual problem in Sweden.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Drunk moose.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "African elephants are famous for getting drunk on?", 'question': "Drunk on what?", 'answers': {'A': "Marula fruit (somewhat disputed)", 'B': "Bamboo shoots", 'C': "Acacia bark", 'D': "Honey wine"}, 'correct': 'A', 'explanation': "Marula fruit. Falls and ferments. Famous BBC clips. Elephants would need enormous amounts to actually get drunk — debate ongoing.", 'commentary_correct': 'Correct! Marula.', 'commentary_wrong': 'Marula fruit. Famous footage.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Bohemian waxwings (Russian birds) famously get drunk on?", 'question': "Drunk on?", 'answers': {'A': "Fermented rowanberries", 'B': "Mountain ash berries", 'C': "Both — they're the same berry", 'D': "Maple sap"}, 'correct': 'C', 'explanation': "Rowan = mountain ash. Berries ferment in winter. Birds eat too many and crash into windows.", 'commentary_correct': 'Correct! Rowanberries.', 'commentary_wrong': 'Rowanberries.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Bees can get drunk on?", 'question': "On what?", 'answers': {'A': "Fermented nectar", 'B': "Pollen", 'C': "Honey", 'D': "Soap"}, 'correct': 'A', 'explanation': "Sun-warmed nectar can ferment. Bees can be denied entry to hive if drunk by guard bees. Real.", 'commentary_correct': 'Correct! Nectar.', 'commentary_wrong': 'Nectar. Guard bees bounce them.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Australian parrots have been known to get drunk by?", 'question': "How?", 'answers': {'A': "Eating fermented mango", 'B': "Drinking from spilled beer", 'C': "Both — Northern Territory has annual 'drunk parrot season'", 'D': "Eating sugar cane"}, 'correct': 'C', 'explanation': "NT vets see drunk parrots routinely in season. Fermented mangoes are the main cause.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Drunk parrots. Real season.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "A 2012 Swedish drunk moose ended up where?", 'question': "Ended up where?", 'answers': {'A': "Stuck in a tree", 'B': "On a highway", 'C': "In someone's pool", 'D': "All happened in different incidents"}, 'correct': 'A', 'explanation': "Drunk moose got stuck in an apple tree in Gothenburg. Picture went global. Local heroes freed it.", 'commentary_correct': 'Correct! Tree-stuck moose.', 'commentary_wrong': 'In the tree.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Vervet monkeys on St. Kitts famously do what?", 'question': "Do what?", 'answers': {'A': "Steal cocktails from beach tourists", 'B': "Sleep on beaches", 'C': "Both A and develop genuine alcoholism", 'D': "Drink coconut water"}, 'correct': 'C', 'explanation': "Vervets steal cocktails. Have been studied for genuine human-like alcohol behaviors — moderate drinkers, binge drinkers, abstainers.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real study.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Tree shrews (Malaysia) drink fermented?", 'question': "Drink what?", 'answers': {'A': "Bertam palm nectar daily without getting drunk", 'B': "Coconut milk", 'C': "Banana wine", 'D': "Rice wine"}, 'correct': 'A', 'explanation': "Pen-tailed tree shrews drink fermented bertam palm nectar daily. Highest alcohol consumption per body mass of any mammal, no apparent drunkenness.", 'commentary_correct': 'Correct! Daily, tolerant.', 'commentary_wrong': 'Tolerant. They\'re alcohol champions.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Reindeer have been observed eating?", 'question': "Eating what for a 'high'?", 'answers': {'A': "Fly agaric mushrooms", 'B': "Pine needles", 'C': "Snow", 'D': "Both A and humans drinking the urine for the high"}, 'correct': 'D', 'explanation': "Sami herders allegedly drank reindeer urine to get the safer high. Reindeer eat Amanita muscaria mushrooms.", 'commentary_correct': 'Correct! Mushrooms + urine.', 'commentary_wrong': 'Mushrooms + Sami tradition.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Brown bears in Slovenia have been caught?", 'question': "Caught doing what?", 'answers': {'A': "Drunk on fermented apples in orchards", 'B': "Stealing beer from campsites", 'C': "Both", 'D': "Drinking from polluted water"}, 'correct': 'C', 'explanation': "Slovenia has annual reports of drunk bears. Orchard fermentation + occasional campsite theft.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Fruit bats are particularly susceptible to?", 'question': "Susceptible to?", 'answers': {'A': "Alcohol intoxication", 'B': "Resistant", 'C': "Both — varies by species", 'D': "Immune"}, 'correct': 'C', 'explanation': "Some fruit bat species are resistant (essentially professional drinkers), others get tipsy easily. Varies.", 'commentary_correct': 'Correct! Both. Species varies.', 'commentary_wrong': 'Both. Species varies.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Squirrels eating fermented pumpkins have been recorded?", 'question': "Recorded?", 'answers': {'A': "Stumbling around in viral videos every fall", 'B': "Mostly fine", 'C': "Both", 'D': "Never"}, 'correct': 'A', 'explanation': "Late October — squirrels stumbling around pumpkin patches. Fermentation hits them hard. Viral every year.", 'commentary_correct': 'Correct! Stumbling.', 'commentary_wrong': 'Drunk squirrels.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Cedar waxwings (American cousin of Bohemian waxwings) sometimes do what?", 'question': "What?", 'answers': {'A': "Die crashing into windows after fermented berries", 'B': "Stay sober", 'C': "Both A happens", 'D': "Drink only morning"}, 'correct': 'C', 'explanation': "Mass cedar waxwing deaths from window crashes after eating fermented berries documented multiple times.", 'commentary_correct': 'Correct! Window crashes.', 'commentary_wrong': 'Window crashes.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "A 2019 \"drunk birds in Gilbert, Minnesota\" incident involved?", 'question': "Involved what?", 'answers': {'A': "Robins eating fermented honeysuckle berries", 'B': "Crows drinking wine", 'C': "Ducks in beer", 'D': "Both A and police got involved"}, 'correct': 'D', 'explanation': "Gilbert PD warned residents about drunk birds flying into windows after eating fermented berries. Real story.", 'commentary_correct': 'Correct! Real news.', 'commentary_wrong': 'Real news. Drunk robins.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Drunk dolphins are claimed to use?", 'question': "Use what for fun?", 'answers': {'A': "Pufferfish toxin (controversial claim)", 'B': "Algae", 'C': "Saltwater", 'D': "Both A and the claim is disputed"}, 'correct': 'D', 'explanation': "BBC documentary suggested dolphins passing puffer fish around for narcotic effect. Researchers since cast doubt.", 'commentary_correct': 'Correct! Both. Disputed.', 'commentary_wrong': 'Both. Disputed claim.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Hedgehogs sometimes ingest?", 'question': "Ingest?", 'answers': {'A': "Slug pellets (poisonous)", 'B': "Beer left out", 'C': "Both — vets warn against both", 'D': "Snail wine"}, 'correct': 'C', 'explanation': "UK hedgehog rehabbers see both regularly. Beer toxic. Slug pellets fatal.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "A 2018 Russian story about a drunk bear involved?", 'question': "Involved what?", 'answers': {'A': "A bear getting drunk on stolen vodka", 'B': "Wandering into a village", 'C': "Both", 'D': "A circus"}, 'correct': 'C', 'explanation': "Russia. Bear broke into rural cabin. Found liquor. Got drunk. Wandered village. Caught.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Russian drunk bear.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Galahs in Australia are famous for what behavior?", 'question': "Behavior?", 'answers': {'A': "Spinning on power lines while drunk", 'B': "Mating dances", 'C': "Migration", 'D': "Cooking"}, 'correct': 'A', 'explanation': "Australian galahs (cockatoos) have been observed spinning around power lines, apparently after fermented seed.", 'commentary_correct': 'Correct! Power line spins.', 'commentary_wrong': 'Power line spins.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Drunk monkeys (vervets) showed similar drinking patterns to?", 'question': "Similar to?", 'answers': {'A': "Humans — moderate drinkers, binge drinkers, abstainers", 'B': "All abstain", 'C': "All become alcoholics", 'D': "All drink moderately"}, 'correct': 'A', 'explanation': "Long-term study showed vervet population mirrors human drinking patterns. ~15% abstainers, ~15% heavy.", 'commentary_correct': 'Correct! Same as humans.', 'commentary_wrong': 'Same as humans.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Drunk Animal Stories', 'setup': "Pet ferrets have been treated by vets for?", 'question': "Treated for?", 'answers': {'A': "Alcohol poisoning from owners offering drinks", 'B': "Beer thievery", 'C': "Both", 'D': "Wine cellar break-ins"}, 'correct': 'C', 'explanation': "Vets warn against pets and alcohol. Multiple ferret cases of intentional and accidental alcohol exposure.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},

    # MLM PYRAMID SCHEMES
    {'category': 'MLM Pyramid Schemes', 'setup': "Herbalife is a multi-level marketing company that?", 'question': "Was famously?", 'answers': {'A': "Battled hedge fund Bill Ackman who shorted it for 5 years", 'B': "Sold burgers", 'C': "Built rockets", 'D': "Was sued for nothing"}, 'correct': 'A', 'explanation': "Ackman shorted Herbalife 2012-17. Carl Icahn took opposite position. Major Wall Street feud. Ackman lost.", 'commentary_correct': 'Correct! Ackman vs Herbalife.', 'commentary_wrong': 'Ackman vs Icahn.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "LuLaRoe's leggings business collapsed because of?", 'question': "Why?", 'answers': {'A': "Defective leggings ripped like wet tissue paper", 'B': "Tax issues", 'C': "Founder scandals", 'D': "All of the above"}, 'correct': 'D', 'explanation': "All three. Famous Amazon Prime documentary. Multiple lawsuits. Distributors went bankrupt.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three. Doc on Amazon.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Mary Kay Cosmetics rewards top sellers with what?", 'question': "Reward?", 'answers': {'A': "Pink Cadillacs", 'B': "Cash bonuses only", 'C': "Houses", 'D': "Cruises"}, 'correct': 'A', 'explanation': "Mary Kay pink Cadillac is iconic. About 6,000 awarded over the company's history.", 'commentary_correct': 'Correct! Pink Cadillac.', 'commentary_wrong': 'Pink Cadillac.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Amway was investigated by the FTC in 1979 and?", 'question': "And?", 'answers': {'A': "Established the 'Amway Safeguards' that defined legal MLM vs pyramid scheme", 'B': "Was shut down", 'C': "Was fined billions", 'D': "Both A and they kept operating"}, 'correct': 'D', 'explanation': "Amway test set legal standard. Companies must show >70% sales to non-distributors. Many MLMs fail this test.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Set the standard.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "What percentage of MLM participants lose money?", 'question': "Approximate?", 'answers': {'A': "Around 99%", 'B': "Around 50%", 'C': "Around 10%", 'D': "Nobody loses"}, 'correct': 'A', 'explanation': "FTC studies suggest 99%+ of MLM participants lose money. The few at top of structure make most.", 'commentary_correct': 'Correct! 99%.', 'commentary_wrong': '99% lose.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Avon's roots go back to?", 'question': "When?", 'answers': {'A': "1886, originally selling perfumes door-to-door", 'B': "1950s, knock-off lipstick", 'C': "1920s, Prohibition era", 'D': "1990s, Walmart era"}, 'correct': 'A', 'explanation': "David H. McConnell founded California Perfume Company in 1886. Rebranded Avon 1939.", 'commentary_correct': 'Correct! 1886.', 'commentary_wrong': '1886. Perfume.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Tupperware filed for bankruptcy in?", 'question': "When?", 'answers': {'A': "2024", 'B': "2010", 'C': "1995", 'D': "Never"}, 'correct': 'A', 'explanation': "September 2024. After decades of decline. Brand acquired by private equity.", 'commentary_correct': 'Correct! 2024.', 'commentary_wrong': '2024.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Vemma (energy drink MLM) was shut down by FTC in?", 'question': "When?", 'answers': {'A': "2015", 'B': "2020", 'C': "2005", 'D': "Still operating"}, 'correct': 'A', 'explanation': "FTC alleged pyramid scheme. Settled $238M judgement. Targeted young people, especially college students.", 'commentary_correct': 'Correct! 2015 FTC.', 'commentary_wrong': '2015. FTC action.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "DoTERRA essential oils has faced criticism for?", 'question': "Criticism?", 'answers': {'A': "Health claims about curing diseases", 'B': "Both A and pricing", 'C': "Distributors making false statements", 'D': "All of the above"}, 'correct': 'D', 'explanation': "FDA warnings about distributor claims. Multiple lawsuits over treating cancer/autism claims. Distributors often run afoul of marketing rules.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "BurnLounge was a music MLM that?", 'question': "Was?", 'answers': {'A': "Shut down by FTC in 2007 as a pyramid scheme", 'B': "Bought by iTunes", 'C': "Still operating", 'D': "Bought by Spotify"}, 'correct': 'A', 'explanation': "Multi-level music streaming MLM. FTC court found it was pyramid scheme. Closed.", 'commentary_correct': 'Correct! FTC closed it.', 'commentary_wrong': 'FTC closed it.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "FTX-style crypto MLMs include?", 'question': "Include?", 'answers': {'A': "OneCoin (~$4B scheme)", 'B': "BitConnect ($2.6B)", 'C': "Both", 'D': "PlusToken ($2B+)"}, 'correct': 'C', 'explanation': "Multiple massive crypto-MLM Ponzi schemes. OneCoin's Ruja Ignatova still missing. PlusToken billions vanished.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. And more.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Mark Hughes (Herbalife founder) died of?", 'question': "Died of?", 'answers': {'A': "Alcohol and antidepressant overdose, age 44", 'B': "Old age", 'C': "Car accident", 'D': "Stroke"}, 'correct': 'A', 'explanation': "2000. Hughes died from alcohol and antidepressants. Aged 44.", 'commentary_correct': 'Correct! Tragic.', 'commentary_wrong': 'Tragic.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Younique was a controversial cosmetics MLM that?", 'question': "Was famous for?", 'answers': {'A': "3D Fiber Lash Mascara that grew lashes 'unbelievably'", 'B': "Tax evasion", 'C': "Both A and lawsuits over results", 'D': "Sold by Coty in 2017"}, 'correct': 'D', 'explanation': "Coty bought 60% in 2017 for $600M. Sold back to founders 2019 at much lower value.", 'commentary_correct': 'Correct! Coty deal.', 'commentary_wrong': 'Coty acquired then divested.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Plexus Worldwide's pink drink is marketed as?", 'question': "Marketed for?", 'answers': {'A': "Weight loss / gut health", 'B': "Hair growth", 'C': "Skin care", 'D': "Energy"}, 'correct': 'A', 'explanation': "Plexus Slim 'Happy Hormones.' Common MLM weight loss / wellness product. Mostly Stevia and other supplements.", 'commentary_correct': 'Correct! Pink drink.', 'commentary_wrong': 'Pink drink. Weight loss.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "The Watkins Company (1868) is one of the oldest what?", 'question': "Oldest what?", 'answers': {'A': "Direct sales / MLM-style companies in US", 'B': "Internet retailers", 'C': "Department stores", 'D': "Catalogues"}, 'correct': 'A', 'explanation': "Watkins started door-to-door sales in 1868. Still operates as MLM today.", 'commentary_correct': 'Correct! 1868.', 'commentary_wrong': '1868. Oldest.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Pampered Chef was founded by Doris Christopher in?", 'question': "Founded?", 'answers': {'A': "1980, from her basement", 'B': "1950s", 'C': "2000s", 'D': "By Warren Buffett"}, 'correct': 'A', 'explanation': "Doris Christopher started in basement 1980. Sold to Berkshire Hathaway in 2002 for $750M.", 'commentary_correct': 'Correct! 1980.', 'commentary_wrong': '1980. Basement to Buffett.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Beachbody (P90X) was a fitness MLM that?", 'question': "Was famous for?", 'answers': {'A': "Insanity, P90X workout programs", 'B': "Shakeology shake", 'C': "Both", 'D': "Wireless headphones"}, 'correct': 'C', 'explanation': "Beachbody combined workouts + supplements + MLM structure. Went public in 2021. Stock collapsed.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Scentsy sells wickless candles via?", 'question': "Via what model?", 'answers': {'A': "Independent consultants in homes (MLM)", 'B': "Retail stores", 'C': "Amazon only", 'D': "Direct online sales"}, 'correct': 'A', 'explanation': "Founded 2004. Classic MLM. Home parties. Top sellers earn six figures; vast majority lose money.", 'commentary_correct': 'Correct! MLM.', 'commentary_wrong': 'MLM.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "Stella & Dot, a jewelry MLM, was founded by?", 'question': "Founded by?", 'answers': {'A': "Jessica Herrin (Stanford MBA)", 'B': "Suzy Welch", 'C': "Sara Blakely", 'D': "Sallie Krawcheck"}, 'correct': 'A', 'explanation': "Founded 2007. Considered a 'sophisticated' MLM. Has had its own controversies.", 'commentary_correct': 'Correct! Jessica Herrin.', 'commentary_wrong': 'Jessica Herrin.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'MLM Pyramid Schemes', 'setup': "AdvoCare was an MLM that the FTC?", 'question': "FTC did what?", 'answers': {'A': "Forced restructure in 2019 (and $150M settlement)", 'B': "Never investigated", 'C': "Endorsed", 'D': "Both A and shut it down"}, 'correct': 'A', 'explanation': "FTC alleged pyramid scheme. AdvoCare restructured to single-level. $150M settlement. Drew Brees was distributor.", 'commentary_correct': 'Correct! Restructured.', 'commentary_wrong': 'Restructured. $150M.', 'difficulty': 'medium', 'time_limit': 15},

    # COOKING SHOW MELTDOWNS
    {'category': 'Cooking Show Meltdowns', 'setup': "Gordon Ramsay's most famous catchphrase about lamb sauce is?", 'question': "Phrase?", 'answers': {'A': "'WHERE'S THE LAMB SAUCE?!'", 'B': "'YOU DONKEY!'", 'C': "'IT'S RAW!'", 'D': "All three are iconic"}, 'correct': 'D', 'explanation': "All three are Ramsay-isms. 'It's raw!' is from chicken cooking. 'You donkey' is signature.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Hell's Kitchen has had how many seasons?", 'question': "How many?", 'answers': {'A': "20+", 'B': "5", 'C': "10", 'D': "30+"}, 'correct': 'A', 'explanation': "20+ seasons of Hell's Kitchen on Fox. Gordon Ramsay still going.", 'commentary_correct': 'Correct! 20+.', 'commentary_wrong': '20+.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Top Chef host Padma Lakshmi was?", 'question': "Previously?", 'answers': {'A': "A model and cookbook author", 'B': "A chef professionally", 'C': "A restaurant critic", 'D': "All of the above"}, 'correct': 'A', 'explanation': "Padma was a model + cookbook author. Not a trained chef. Hosted Top Chef from 2006-2023.", 'commentary_correct': 'Correct! Model + cookbook author.', 'commentary_wrong': 'Model + cookbook.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Iron Chef America's Kitchen Stadium battles were judged on?", 'question': "On?", 'answers': {'A': "Taste, plating, originality", 'B': "Speed", 'C': "Theme ingredient usage", 'D': "All of the above"}, 'correct': 'D', 'explanation': "All four. The 'theme ingredient' had to be in every dish. Famous show ran 2004-2013.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Chopped contestants are given how many ingredients?", 'question': "How many?", 'answers': {'A': "4 mystery basket ingredients per round", 'B': "10", 'C': "1", 'D': "Unlimited"}, 'correct': 'A', 'explanation': "4 ingredients per round. Appetizer, entree, dessert rounds. Time limits.", 'commentary_correct': 'Correct! 4 per round.', 'commentary_wrong': '4 ingredients.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Cake Boss is famous for?", 'question': "For?", 'answers': {'A': "Buddy Valastro's New Jersey bakery and elaborate cakes", 'B': "Cake balls", 'C': "Cake-only flagship restaurants", 'D': "Wedding planning"}, 'correct': 'A', 'explanation': "Buddy Valastro's Carlo's Bakery. Hoboken NJ. Massive engineering cakes. TLC show.", 'commentary_correct': 'Correct! Carlo\'s Bakery.', 'commentary_wrong': 'Carlo\'s Bakery.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Kitchen Nightmares revisited some restaurants. Many?", 'question': "Many what happened?", 'answers': {'A': "Closed within months after the show aired", 'B': "Thrived for decades", 'C': "Became franchises", 'D': "Were demolished"}, 'correct': 'A', 'explanation': "Roughly 60% of Kitchen Nightmares restaurants closed within a year. Ramsay's 'help' was a kiss of death for many.", 'commentary_correct': 'Correct! Many closed.', 'commentary_wrong': 'Many closed fast.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "MasterChef Junior contestants are?", 'question': "What age range?", 'answers': {'A': "8-13 years old", 'B': "5-10", 'C': "13-18", 'D': "Adults only"}, 'correct': 'A', 'explanation': "MasterChef Junior 8-13 years old. Astonishing skill levels. Ramsay notably gentler with kids.", 'commentary_correct': 'Correct! 8-13.', 'commentary_wrong': '8-13.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Anthony Bourdain's first show was?", 'question': "Was?", 'answers': {'A': "A Cook's Tour (Food Network 2002-2003)", 'B': "No Reservations", 'C': "Parts Unknown", 'D': "Top Chef"}, 'correct': 'A', 'explanation': "A Cook's Tour was first. Then No Reservations (Travel Channel) then Parts Unknown (CNN). His career arc.", 'commentary_correct': 'Correct! A Cook\'s Tour.', 'commentary_wrong': 'A Cook\'s Tour.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "The Great British Bake Off / Great British Baking Show moved networks because?", 'question': "Why?", 'answers': {'A': "Channel 4 outbid the BBC", 'B': "Audience numbers", 'C': "Both — and original hosts quit in protest", 'D': "Production costs"}, 'correct': 'C', 'explanation': "2016 move from BBC to Channel 4. Mary Berry, Sue Perkins, Mel Giedroyc all quit. Show changed character.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Joe Bastianich (chef + judge) was business partners with?", 'question': "Partner of?", 'answers': {'A': "Mario Batali (now disgraced)", 'B': "Wolfgang Puck", 'C': "Bobby Flay", 'D': "Emeril Lagasse"}, 'correct': 'A', 'explanation': "Batali / Bastianich Hospitality Group. Multiple high-end restaurants. Batali sexual misconduct allegations 2017. Bastianich bought him out.", 'commentary_correct': 'Correct! Batali.', 'commentary_wrong': 'Batali.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Paula Deen lost her Food Network show in 2013 because?", 'question': "Why?", 'answers': {'A': "Use of racial slurs in deposition revelation", 'B': "Tax issues", 'C': "Diabetes endorsement controversy", 'D': "Recipe theft"}, 'correct': 'A', 'explanation': "Lawsuit deposition revealed past use of racial slurs. Food Network dropped her. She rebuilt brand slowly.", 'commentary_correct': 'Correct! Slurs in deposition.', 'commentary_wrong': 'Slurs in deposition.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "MasterChef Australia had which famous moment?", 'question': "Moment?", 'answers': {'A': "Multiple contestants crying over Jamie Oliver showing up", 'B': "A signature dish fire on TV", 'C': "Both", 'D': "A power outage mid-cook"}, 'correct': 'C', 'explanation': "MasterChef AU has had many memorable moments. Jamie Oliver visits and on-camera fires both happened.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Worst Cooks in America's recruits are?", 'question': "Are?", 'answers': {'A': "Real bad home cooks competing for $25K", 'B': "Trained chefs faking it", 'C': "Both", 'D': "Celebrities"}, 'correct': 'A', 'explanation': "Genuine bad cooks compete. Anne Burrell and other chefs teach them. Hilarious mistakes.", 'commentary_correct': 'Correct! Real bad cooks.', 'commentary_wrong': 'Real bad cooks.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Iron Chef Japan (original) host Chairman Kaga was famous for?", 'question': "Famous for?", 'answers': {'A': "Wild outfits and biting into yellow peppers dramatically", 'B': "Eating raw fish on set", 'C': "Throwing knives", 'D': "Just standing silent"}, 'correct': 'A', 'explanation': "Takeshi Kaga's flamboyant persona. Bell pepper bite became iconic.", 'commentary_correct': 'Correct! Pepper bite.', 'commentary_wrong': 'Bell pepper bite.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Bobby Flay's Throwdown! premise was?", 'question': "Premise?", 'answers': {'A': "Surprise small-business cooks with a Bobby Flay challenge in their specialty", 'B': "Restaurant takeovers", 'C': "Travel cuisine", 'D': "Reality kitchen"}, 'correct': 'A', 'explanation': "Flay challenged home cooks/small businesses to throw down on their specialty dishes. Bobby lost often.", 'commentary_correct': 'Correct! Surprise challenges.', 'commentary_wrong': 'Surprise challenges.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Jamie Oliver was known as 'The Naked Chef' because?", 'question': "Why?", 'answers': {'A': "His simple, stripped-down style — not actual nudity", 'B': "He cooked nude (no, he didn't)", 'C': "His apron caught fire", 'D': "He didn't wear chef whites"}, 'correct': 'A', 'explanation': "'Naked' meant simple/unfussy cooking. He stayed clothed throughout.", 'commentary_correct': 'Correct! Simple style.', 'commentary_wrong': 'Simple, stripped-down style.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Diners, Drive-Ins and Dives host Guy Fieri claims his hair is?", 'question': "His hair is?", 'answers': {'A': "Naturally that bleached spiky look since 2000", 'B': "A wig", 'C': "Bleached daily", 'D': "Implants"}, 'correct': 'A', 'explanation': "Guy keeps it bleached and spiky. His brand. Triple D viral success.", 'commentary_correct': 'Correct! Real hair.', 'commentary_wrong': 'Real hair. Brand.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Top Chef in Houston (2022) faced what controversy?", 'question': "What?", 'answers': {'A': "Pawn shop episode contained reportedly stolen items", 'B': "A judge resigned", 'C': "A contestant was banned", 'D': "Filming halted"}, 'correct': 'A', 'explanation': "Episode at pawn shop later revealed problematic items. Show edited and re-released.", 'commentary_correct': 'Correct! Pawn shop.', 'commentary_wrong': 'Pawn shop edit.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cooking Show Meltdowns', 'setup': "Anne Burrell sadly passed in?", 'question': "When?", 'answers': {'A': "She is still alive (Worst Cooks star)", 'B': "2020", 'C': "2024", 'D': "2018"}, 'correct': 'A', 'explanation': "Anne Burrell continues hosting Worst Cooks in America. No tragedy here.", 'commentary_correct': 'Correct! Still alive.', 'commentary_wrong': 'Still alive.', 'difficulty': 'hard', 'time_limit': 15},

    # MOVIE SEQUELS NOBODY ASKED FOR
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Speed 2: Cruise Control (1997) replaced Keanu Reeves with?", 'question': "Replaced by?", 'answers': {'A': "Jason Patric", 'B': "Tom Cruise", 'C': "Mel Gibson", 'D': "Brad Pitt"}, 'correct': 'A', 'explanation': "Reeves declined. Jason Patric got the role. Movie bombed. Sandra Bullock still there.", 'commentary_correct': 'Correct! Patric.', 'commentary_wrong': 'Jason Patric.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Grease 2 (1982) was reviewed as?", 'question': "Critical reception?", 'answers': {'A': "Box office bomb, terrible reviews", 'B': "Better than the original", 'C': "Best Picture nominee", 'D': "A cult hit immediately"}, 'correct': 'A', 'explanation': "Grease 2 was a disaster. Maxwell Caulfield never recovered. 'Cool Rider' is the only memorable bit.", 'commentary_correct': 'Correct! Bomb.', 'commentary_wrong': 'Bomb.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Caddyshack II (1988) lacked which original star?", 'question': "Lacked?", 'answers': {'A': "Bill Murray", 'B': "Chevy Chase", 'C': "Rodney Dangerfield", 'D': "All except Chase"}, 'correct': 'D', 'explanation': "Only Chevy Chase returned. Bill Murray, Dangerfield, Ted Knight all declined. Sequel flopped.", 'commentary_correct': 'Correct! Only Chase returned.', 'commentary_wrong': 'Only Chase.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Jaws: The Revenge (1987) had what absurd premise?", 'question': "Premise?", 'answers': {'A': "The shark was seeking revenge on the Brody family", 'B': "Sharks evolved feet", 'C': "Multiple sharks", 'D': "A robot shark"}, 'correct': 'A', 'explanation': "Shark personally tracked Brody family across oceans. Universally panned. 0% on Rotten Tomatoes.", 'commentary_correct': 'Correct! Revenge shark.', 'commentary_wrong': 'Revenge-seeking shark.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Highlander II: The Quickening (1991) had what bizarre retcon?", 'question': "Retcon?", 'answers': {'A': "Immortals were actually aliens from planet Zeist", 'B': "Magic was actually genetic", 'C': "Time travel only worked once", 'D': "Highlander Conor was always a robot"}, 'correct': 'A', 'explanation': "Aliens from Zeist. Fans hated. Director's cut later removed alien stuff. Still bad.", 'commentary_correct': 'Correct! Zeist aliens.', 'commentary_wrong': 'Zeist aliens.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Indiana Jones and the Kingdom of the Crystal Skull (2008) had what infamous scene?", 'question': "What scene?", 'answers': {'A': "Indy surviving a nuclear blast in a refrigerator", 'B': "Indy fighting aliens", 'C': "Both A and the aliens were the McGuffin", 'D': "An exorcism"}, 'correct': 'C', 'explanation': "Nuked the fridge. Aliens. Critics called it the worst Indy film. Spielberg has apologized.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Nuke + aliens.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Star Wars: The Rise of Skywalker (2019) was met with?", 'question': "Met with?", 'answers': {'A': "Mixed reviews and lower box office than predecessors", 'B': "Universal praise", 'C': "A Best Picture nomination", 'D': "Banned in 5 countries"}, 'correct': 'A', 'explanation': "Polarizing reception. Made $1.07B but disappointing for SW. Sequel trilogy left fans divided.", 'commentary_correct': 'Correct! Mixed.', 'commentary_wrong': 'Mixed reception.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Son of the Mask (2005) is famous for being?", 'question': "Famous for?", 'answers': {'A': "A box office disaster without Jim Carrey", 'B': "An Oscar nominee", 'C': "A Cannes hit", 'D': "A surprise success"}, 'correct': 'A', 'explanation': "$84M budget. Made $59M. No Jim Carrey. Jamie Kennedy starred. Career-ender for many.", 'commentary_correct': 'Correct! Disaster.', 'commentary_wrong': 'Disaster.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Dumb and Dumber To (2014) was made how many years after the original?", 'question': "How many years?", 'answers': {'A': "20", 'B': "5", 'C': "10", 'D': "30"}, 'correct': 'A', 'explanation': "Original 1994, sequel 2014. Made $169M despite age gap.", 'commentary_correct': 'Correct! 20 years.', 'commentary_wrong': '20 years.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "The Sandlot 3 (2007) went direct to?", 'question': "Direct to?", 'answers': {'A': "DVD", 'B': "Theaters", 'C': "TV", 'D': "Streaming (didn't exist yet)"}, 'correct': 'A', 'explanation': "Direct-to-DVD. Without any original cast members. Painful for fans.", 'commentary_correct': 'Correct! DVD.', 'commentary_wrong': 'DVD.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "American Psycho 2 (2002) starred?", 'question': "Starred?", 'answers': {'A': "Mila Kunis", 'B': "Christian Bale", 'C': "Jared Leto", 'D': "Jennifer Garner"}, 'correct': 'A', 'explanation': "Mila Kunis. She has called it the worst movie she ever made. No connection to original.", 'commentary_correct': 'Correct! Kunis.', 'commentary_wrong': 'Kunis. She disowns it.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Basic Instinct 2 (2006) reunited Sharon Stone with?", 'question': "With?", 'answers': {'A': "Nobody from original (different cast)", 'B': "Michael Douglas", 'C': "Verhoeven", 'D': "Original director"}, 'correct': 'A', 'explanation': "Stone was only returner. 14 years later. Razzie sweep. Career-damaging.", 'commentary_correct': 'Correct! Just Stone.', 'commentary_wrong': 'Just Stone.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Blade Runner 2049 (2017) was?", 'question': "Was?", 'answers': {'A': "Critically acclaimed but commercially disappointing", 'B': "A huge hit", 'C': "Universally hated", 'D': "Both A and Denis Villeneuve directed"}, 'correct': 'D', 'explanation': "Villeneuve. Critically praised. Made $260M on ~$185M budget — disappointing for studio.", 'commentary_correct': 'Correct! Praised but underperformed.', 'commentary_wrong': 'Praised. Underperformed.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Independence Day: Resurgence (2016) returned without?", 'question': "Returned without?", 'answers': {'A': "Will Smith", 'B': "Jeff Goldblum", 'C': "Bill Pullman", 'D': "Roland Emmerich"}, 'correct': 'A', 'explanation': "Will Smith declined to return. Made $389M but expected to launch a trilogy that never happened.", 'commentary_correct': 'Correct! No Will Smith.', 'commentary_wrong': 'No Smith.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Jurassic World Dominion (2022) brought back which original cast?", 'question': "Brought back?", 'answers': {'A': "Sam Neill, Laura Dern, Jeff Goldblum", 'B': "Just Goldblum", 'C': "None", 'D': "Spielberg as actor"}, 'correct': 'A', 'explanation': "All three originals returned. Made $1B but reviews were mixed/negative.", 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Zoolander 2 (2016) was directed by?", 'question': "Directed by?", 'answers': {'A': "Ben Stiller (same as original)", 'B': "Owen Wilson", 'C': "Will Ferrell", 'D': "Judd Apatow"}, 'correct': 'A', 'explanation': "Stiller directed both. 2016 sequel underperformed despite original cast.", 'commentary_correct': 'Correct! Stiller.', 'commentary_wrong': 'Stiller.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Anchorman 2 (2013) followed how many years after first?", 'question': "How many?", 'answers': {'A': "9 years", 'B': "5", 'C': "20", 'D': "15"}, 'correct': 'A', 'explanation': "2004 → 2013 = 9 years. Made $173M. Most agree it was less funny than original.", 'commentary_correct': 'Correct! 9 years.', 'commentary_wrong': '9 years.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Cars 2 (2011) is famously the only Pixar film to?", 'question': "Only Pixar to?", 'answers': {'A': "Have under a 40% Rotten Tomatoes score (originally)", 'B': "Lose money", 'C': "Win zero awards", 'D': "Both A and the spy plot was hated"}, 'correct': 'D', 'explanation': "Cars 2 famously rated below 40% on RT. Spy plot didn't land. First Pixar disappointment.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Cars 2.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "The Matrix Resurrections (2021) returned which original cast?", 'question': "Returning cast?", 'answers': {'A': "Keanu Reeves and Carrie-Anne Moss only (mostly)", 'B': "Full original cast", 'C': "None of the original", 'D': "Just Hugo Weaving"}, 'correct': 'A', 'explanation': "Reeves and Moss returned. Lana Wachowski directed alone. Mixed reception. Made $159M against $190M budget.", 'commentary_correct': 'Correct! Keanu + Carrie-Anne.', 'commentary_wrong': 'Just two leads.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Movie Sequels Nobody Asked For', 'setup': "Battlefield Earth (2000) was based on a novel by?", 'question': "Author?", 'answers': {'A': "L. Ron Hubbard", 'B': "Stephen King", 'C': "Frank Herbert", 'D': "Isaac Asimov"}, 'correct': 'A', 'explanation': "Hubbard, Scientology founder. Tom Cruise refused, John Travolta starred. Razzie winner. Cited as worst movie ever.", 'commentary_correct': 'Correct! Hubbard.', 'commentary_wrong': 'L. Ron Hubbard.', 'difficulty': 'medium', 'time_limit': 15},
]


def seed_v4_batch2b():
    ph = get_placeholder()
    added = 0
    for q in V4_BATCH2B_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (cat['id'], q['question'], q.get('setup','') or '',
                  q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                  q['correct'], q.get('difficulty','medium'), q.get('time_limit',15),
                  q.get('explanation',''), q.get('commentary_correct',''), q.get('commentary_wrong','')))
            added += 1
        except Exception as e:
            print(f"[v4-b2b] {e}")
    print(f"✅ v4 batch2b added {added} ({len(V4_BATCH2B_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch2b()
