"""v4 batch 1b — the 7 remaining themed categories from the original v4 ask.

20 questions each, all YDKJ-styled with setup + commentary.
Same shape and idempotency rules as the other v4 seeders.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH1B_QUESTIONS = [
    # ========================================================================
    # CURSED HOLLYWOOD FILMS
    # ========================================================================
    {'category': 'Cursed Hollywood Films', 'setup': 'The Poltergeist trilogy is famous for cast deaths.', 'question': 'How many cast members died within ~6 years of the first film?', 'answers': {'A': '2', 'B': '4', 'C': '6', 'D': '0'}, 'correct': 'B', 'explanation': 'Four notable cast members died young: Dominique Dunne, Heather O\'Rourke, Julian Beck, Will Sampson.', 'commentary_correct': 'Correct! 4. The Poltergeist curse.', 'commentary_wrong': '4. The reason this category exists.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'On the set of The Crow (1994), the lead actor was killed by what?', 'question': 'How did Brandon Lee die?', 'answers': {'A': 'A prop gun loaded with a real bullet fragment', 'B': 'A car crash', 'C': 'A fall from a building', 'D': 'A sword stunt'}, 'correct': 'A', 'explanation': 'Improperly loaded prop gun. Bullet tip lodged in the barrel, fired by a blank charge.', 'commentary_correct': 'Correct! Prop gun. Real tragedy.', 'commentary_wrong': 'Prop gun + blank charge.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The Exorcist (1973) had a famously cursed production.', 'question': 'What unusual event happened during filming?', 'answers': {'A': 'A fire destroyed the set (except Regan\'s bedroom)', 'B': 'Multiple crew deaths', 'C': 'Both A and B', 'D': 'Lead actress was actually possessed'}, 'correct': 'C', 'explanation': 'Set fire spared the bedroom. Nine cast/crew deaths during/after production.', 'commentary_correct': 'Correct! Both. Spooky stuff.', 'commentary_wrong': 'Both. The set fire spared one room.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'During Twilight Zone: The Movie (1982), three actors died on set.', 'question': 'How did they die?', 'answers': {'A': 'Helicopter crash during a scene', 'B': 'Set collapse', 'C': 'Pyrotechnics accident', 'D': 'Both A and C in the same incident'}, 'correct': 'D', 'explanation': 'Helicopter crash caused by pyrotechnics. Vic Morrow + two children. Led to major safety reforms.', 'commentary_correct': 'Correct! Both. Awful tragedy.', 'commentary_wrong': 'Helicopter + pyrotechnics. Reformed Hollywood safety.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Rust (2021) was halted because of what on-set incident?', 'question': 'What happened?', 'answers': {'A': 'Alec Baldwin discharged a prop gun, killing the cinematographer', 'B': 'A fire', 'C': 'A horse fell', 'D': 'A vehicle crash'}, 'correct': 'A', 'explanation': 'Cinematographer Halyna Hutchins killed. Live round in a prop gun. Major industry investigation.', 'commentary_correct': 'Correct! Prop gun. Industry-shaking.', 'commentary_wrong': 'Prop gun. Halyna Hutchins.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Atuk is a Hollywood "cursed script" that has?', 'question': 'What makes it cursed?', 'answers': {'A': 'Five comedians attached to it have died before filming', 'B': 'It was never written', 'C': 'It was banned globally', 'D': 'It only exists as a rumor'}, 'correct': 'A', 'explanation': 'John Belushi, Sam Kinison, John Candy, Chris Farley, and Phil Hartman were all attached and all died young.', 'commentary_correct': 'Correct! 5 comedians. Real curse.', 'commentary_wrong': '5 comedians. The Atuk curse.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The Conqueror (1956) was filmed near nuclear test sites in Utah.', 'question': 'What happened to the cast and crew?', 'answers': {'A': 'About half developed cancer over the years', 'B': 'Nothing — radiation myth', 'C': 'Everyone died within 10 years', 'D': 'Only John Wayne got cancer'}, 'correct': 'A', 'explanation': '91 of 220 cast/crew got cancer, including John Wayne, Susan Hayward, Agnes Moorehead. Statistical anomaly tied to nuclear fallout.', 'commentary_correct': 'Correct! ~half. Real fallout.', 'commentary_wrong': '~Half got cancer. Real nuclear fallout.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'On the set of Apocalypse Now (1979), Martin Sheen had?', 'question': 'What happened?', 'answers': {'A': 'A heart attack at age 36', 'B': 'A snake bite', 'C': 'A nervous breakdown only', 'D': 'A typhoon nearly killed him'}, 'correct': 'A', 'explanation': 'Heart attack mid-production at 36. Production was already plagued by typhoons, recasting, and budget overruns.', 'commentary_correct': 'Correct! Heart attack at 36.', 'commentary_wrong': 'Heart attack. The whole shoot was cursed.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Superman (1978) and its sequels have a "curse" of?', 'question': 'What is the Superman curse?', 'answers': {'A': 'Lead actors suffer career or personal misfortune', 'B': 'Every Superman dies young', 'C': 'Only the actor playing Lex Luthor stays famous', 'D': 'No one survives Superman'}, 'correct': 'A', 'explanation': 'George Reeves (suicide), Christopher Reeve (paralysis), Margot Kidder (mental health). The "Superman curse" is well-documented.', 'commentary_correct': 'Correct! Career/health misfortune.', 'commentary_wrong': 'Lead-actor curse.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'During Rosemary\'s Baby (1968), the director\'s wife was murdered.', 'question': 'Who was the director?', 'answers': {'A': 'Roman Polanski', 'B': 'Brian De Palma', 'C': 'William Friedkin', 'D': 'Dario Argento'}, 'correct': 'A', 'explanation': 'Polanski. Sharon Tate was murdered by the Manson Family the year after the film\'s release.', 'commentary_correct': 'Correct! Polanski. Sharon Tate.', 'commentary_wrong': 'Polanski.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Heaven\'s Gate (1980) was so bad it?', 'question': 'What did it do to its studio?', 'answers': {'A': 'Bankrupted United Artists', 'B': 'Won Best Picture anyway', 'C': 'Was banned globally', 'D': 'Started a new genre'}, 'correct': 'A', 'explanation': 'Michael Cimino\'s western. Cost $44M, made $3M. United Artists sold to MGM as a result.', 'commentary_correct': 'Correct! Killed UA.', 'commentary_wrong': 'Bankrupted UA.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The Wizard of Oz (1939) set had what infamous safety problems?', 'question': 'Which crew suffered?', 'answers': {'A': 'The original Tin Man poisoned by his makeup', 'B': 'Wicked Witch severely burned in a stunt', 'C': 'Munchkin actors mistreated', 'D': 'All of the above'}, 'correct': 'D', 'explanation': 'Buddy Ebsen poisoned by aluminum makeup (replaced by Jack Haley). Margaret Hamilton burned on set. Munchkin actor stories vary.', 'commentary_correct': 'Correct! All three. Oz was rough.', 'commentary_wrong': 'All three. Oz set was rough.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Ben-Hur (1959) chariot race claimed?', 'question': 'What was the injury rate?', 'answers': {'A': 'One stunt double died (an unconfirmed rumor)', 'B': 'Several stuntmen broke bones', 'C': 'Both — though the death rumor was later debunked', 'D': 'Nobody got hurt'}, 'correct': 'C', 'explanation': 'The famous "death" was a persistent rumor; injuries were real. Chuck Heston broke a horse-handler\'s rib personally.', 'commentary_correct': 'Correct! Both. Rumor + real injuries.', 'commentary_wrong': 'Both. Lots of injuries.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The set of Three Men and a Baby (1987) supposedly featured?', 'question': 'What was the famous claim?', 'answers': {'A': 'A ghost child visible in a scene', 'B': 'A demon doll', 'C': 'Both — debunked as a cardboard cutout', 'D': 'A real haunting documented by paranormal team'}, 'correct': 'C', 'explanation': 'Internet legend said a ghost boy. Was actually a cardboard cutout of Ted Danson left in shot.', 'commentary_correct': 'Correct! Cardboard cutout.', 'commentary_wrong': 'Cardboard cutout of Ted Danson.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Filming of The Lord of the Rings: The Two Towers had?', 'question': 'What injury kept Aragorn limping for real?', 'answers': {'A': 'Viggo Mortensen broke his toe kicking a helmet', 'B': 'A horse stepped on his foot', 'C': 'He twisted his ankle on a rock', 'D': 'He was bitten by a spider'}, 'correct': 'A', 'explanation': 'Viggo broke his toe kicking a helmet in a rage scene. His scream of pain was kept in the final cut.', 'commentary_correct': 'Correct! Toe. His scream was real.', 'commentary_wrong': 'Broke his toe.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The Omen (1976) had what cursed incident with airline?', 'question': 'What plane incident?', 'answers': {'A': 'A plane next to one carrying the cast was hit by lightning', 'B': 'A plane crashed killing the script supervisor', 'C': 'Both A and an animal handler died nearby', 'D': 'No incidents, all rumor'}, 'correct': 'C', 'explanation': 'A plane near star Gregory Peck\'s flight was struck by lightning. A small plane crash killed a special effects man. Animal handler killed by lions in zoo.', 'commentary_correct': 'Correct! Multiple incidents.', 'commentary_wrong': 'Multiple incidents. Documented.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'James Dean\'s death in 1955 happened while?', 'question': 'How did he die?', 'answers': {'A': 'Car crash in his Porsche 550 Spyder', 'B': 'Motorcycle crash', 'C': 'Plane crash', 'D': 'Drug overdose'}, 'correct': 'A', 'explanation': 'Porsche 550 Spyder, dubbed "Little Bastard." Car was infamously associated with later deaths/injuries among owners.', 'commentary_correct': 'Correct! Porsche. The "Little Bastard."', 'commentary_wrong': 'Porsche 550 Spyder. The "Little Bastard."', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'The Passion of the Christ (2004) had Jim Caviezel struck by?', 'question': 'Struck by what?', 'answers': {'A': 'Lightning, twice', 'B': 'A flying camera', 'C': 'A horse', 'D': 'A protester'}, 'correct': 'A', 'explanation': 'Caviezel was hit by lightning during filming (with assistant director Jan Michelini hit twice).', 'commentary_correct': 'Correct! Lightning. Real.', 'commentary_wrong': 'Lightning. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Indiana Jones and the Temple of Doom (1984) caused what regulatory change?', 'question': 'What change?', 'answers': {'A': 'Creation of the PG-13 rating', 'B': 'Banning of cartoon violence', 'C': 'New stunt safety rules', 'D': 'PG ratings tightened only'}, 'correct': 'A', 'explanation': 'Heart-removal scene caused parent outrage. PG-13 rating created in 1984 partly because of this film.', 'commentary_correct': 'Correct! PG-13 was born.', 'commentary_wrong': 'PG-13. Born from this movie.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Cursed Hollywood Films', 'setup': 'Waterworld (1995) went over budget by approximately?', 'question': 'How much?', 'answers': {'A': 'Tripled — from $100M to $175M+', 'B': 'Doubled', 'C': 'Stayed on budget', 'D': 'Was canceled'}, 'correct': 'A', 'explanation': 'Original budget $100M, final ~$175M. Floating set destroyed by storms. Made money eventually via home video.', 'commentary_correct': 'Correct! ~$175M.', 'commentary_wrong': '$175M. Floating set kept sinking.', 'difficulty': 'medium', 'time_limit': 15},

    # ========================================================================
    # DUMBEST LAWSUITS EVER WON
    # ========================================================================
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'Liebeck v. McDonald\'s (1994) was the famous?', 'question': 'What was it about?', 'answers': {'A': 'Hot coffee that caused third-degree burns', 'B': 'Stale fries', 'C': 'Mismatched Happy Meal toys', 'D': 'Cold coffee'}, 'correct': 'A', 'explanation': 'Stella Liebeck. Coffee was 180-190°F. Third-degree burns required skin grafts. $2.86M verdict; reduced on appeal.', 'commentary_correct': 'Correct! Hot coffee. Third-degree burns.', 'commentary_wrong': 'Hot coffee. Real injury.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued Anheuser-Busch in 1991 because?', 'question': 'For what?', 'answers': {'A': 'Bud commercials promised beautiful women that didn\'t appear when he drank Bud', 'B': 'Bottles weren\'t cold enough', 'C': 'Cans weren\'t green', 'D': 'He got drunk too fast'}, 'correct': 'A', 'explanation': 'Richard Overton lost; case dismissed. But it actually went to court. False advertising claim of $10,000.', 'commentary_correct': 'Correct! No supermodels appeared.', 'commentary_wrong': 'No models. Case dismissed eventually.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A burglar sued homeowners after getting trapped where?', 'question': 'Where?', 'answers': {'A': 'In their garage', 'B': 'On the roof of their house', 'C': 'In an attic accessed via a broken window', 'D': 'All happened in different real cases'}, 'correct': 'D', 'explanation': 'Burglars have sued for injuries during their crimes. Most fail; some succeed surprisingly.', 'commentary_correct': 'Correct! All three. Real cases.', 'commentary_wrong': 'All three. Burglar suits.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A psychic sued a hospital because?', 'question': 'Why?', 'answers': {'A': 'A CT scan caused her to lose her psychic powers', 'B': 'They cancelled her appointment', 'C': 'She didn\'t see it coming', 'D': 'Her fortune-telling forecast was wrong'}, 'correct': 'A', 'explanation': 'Judith Haimes, 1986 Philadelphia. Won $986K (later overturned). Claimed CT scan destroyed her gift.', 'commentary_correct': 'Correct! Psychic powers. Won and later overturned.', 'commentary_wrong': 'Psychic powers lost.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued his parents because?', 'question': 'Why?', 'answers': {'A': 'They threw out his porn collection', 'B': 'They wouldn\'t adopt him back', 'C': 'They embarrassed him', 'D': 'All real cases from different years'}, 'correct': 'A', 'explanation': '2016 Michigan case. David Werking won $30K against his parents who threw out his 12 boxes of porn.', 'commentary_correct': 'Correct! Porn collection. He won.', 'commentary_wrong': 'Porn. $30K.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'Pearson v. Chung (2005) is the case where a judge sued a dry cleaner over?', 'question': 'Over what?', 'answers': {'A': 'A lost pair of pants — for $54 million', 'B': 'A stain on a tie', 'C': 'A wrong cleaning chemical', 'D': 'A returned shirt with missing buttons'}, 'correct': 'A', 'explanation': 'Judge Roy Pearson sued for $54M over lost pants. Lost. Lost his judgeship too eventually.', 'commentary_correct': 'Correct! $54M pants.', 'commentary_wrong': '$54M pants. The judge lost.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A woman sued Universal Studios over?', 'question': 'What injury?', 'answers': {'A': 'A "haunted house" scare ride gave her too much of a scare', 'B': 'She tripped on a roller coaster line', 'C': 'A character was rude to her', 'D': 'Food poisoning'}, 'correct': 'A', 'explanation': 'Real 1998 case. Woman claimed psychological injury from a haunted house attraction. Case dismissed.', 'commentary_correct': 'Correct! Haunted house. Dismissed.', 'commentary_wrong': 'Haunted house. Too scary.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A robber sued his victim because?', 'question': 'Why?', 'answers': {'A': 'The victim shot him during the robbery', 'B': 'The victim called him a bad name', 'C': 'The victim\'s alarm hurt his ears', 'D': 'Both A and C have happened'}, 'correct': 'D', 'explanation': 'Multiple real cases of robbers suing victims for injuries. Most fail. Many states have changed laws to prevent this.', 'commentary_correct': 'Correct! Both. Real cases.', 'commentary_wrong': 'Both. Real cases.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A father sued his son\'s school district because?', 'question': 'Reason?', 'answers': {'A': 'His son was given a 99 instead of 100 on a test', 'B': 'His son got a B+ instead of A-', 'C': 'His son had too much homework', 'D': 'All three from different parents'}, 'correct': 'D', 'explanation': 'Helicopter parent lawsuits over grades are common and almost always lose. But they happen.', 'commentary_correct': 'Correct! All three. Real lawsuits.', 'commentary_wrong': 'All three. Helicopter parents.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued Domino\'s Pizza because?', 'question': 'Why?', 'answers': {'A': 'The website wasn\'t accessible to blind users (ADA case)', 'B': 'The pizza was too hot', 'C': 'The delivery driver was rude', 'D': 'The Domino\'s logo offended his religion'}, 'correct': 'A', 'explanation': 'Robles v. Domino\'s 2019. Supreme Court ruled in favor of accessibility. Websites must be ADA-compliant. Major ruling.', 'commentary_correct': 'Correct! ADA accessibility. Won.', 'commentary_wrong': 'ADA accessibility. Robles v. Domino\'s.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A woman won a lawsuit over a hair dryer because?', 'question': 'For what?', 'answers': {'A': 'The label didn\'t say not to use it in the shower', 'B': 'It overheated', 'C': 'It electrocuted her', 'D': 'Both A and the warning labels changed industry-wide'}, 'correct': 'D', 'explanation': 'Real 1980s case. Manufacturers added "DO NOT USE IN SHOWER" labels. Mostly because of this kind of suit.', 'commentary_correct': 'Correct! Label warning.', 'commentary_wrong': 'Label warning. Why your hair dryer has labels.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued his neighbor over what plant?', 'question': 'Plant?', 'answers': {'A': 'A tree that grew over his fence', 'B': 'A hedge blocking his view', 'C': 'Both — these neighbor suits are extremely common', 'D': 'A garden gnome'}, 'correct': 'C', 'explanation': 'Neighbor disputes over trees and hedges are among the most common civil court matters. Sometimes worth $1000s in legal fees over fruit.', 'commentary_correct': 'Correct! Both. Common.', 'commentary_wrong': 'Both. Common suits.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued Pearson Education over?', 'question': 'For what?', 'answers': {'A': 'A textbook misspelled his name', 'B': 'A textbook said his hometown was the wrong state', 'C': 'A textbook called him a "minor figure"', 'D': 'Both A and B from different cases'}, 'correct': 'D', 'explanation': 'Multiple textbook lawsuits over minor errors. Usually settled quietly.', 'commentary_correct': 'Correct! Both. Real.', 'commentary_wrong': 'Both. Textbook suits.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A woman tried to sue Microsoft because?', 'question': 'For what?', 'answers': {'A': 'Windows 10 auto-updated and erased her work', 'B': 'Clippy was annoying', 'C': 'Blue screen of death gave her seizures', 'D': 'Both A in real cases and others ruled in plaintiffs\' favor'}, 'correct': 'D', 'explanation': 'Multiple Win10 auto-update lawsuits. One small business owner won ~$10K in 2016.', 'commentary_correct': 'Correct! Real win.', 'commentary_wrong': 'Real win. Won settlement.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued his airline because?', 'question': 'Why?', 'answers': {'A': 'They served warm beer', 'B': 'The seat was too small', 'C': 'The film was too sad', 'D': 'All — real cases, varying outcomes'}, 'correct': 'D', 'explanation': 'Airlines get sued for everything. Warm beer, sad in-flight movies, seat-size discrimination — all real cases.', 'commentary_correct': 'Correct! All three. Real.', 'commentary_wrong': 'All three. Airlines get sued.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A class-action lawsuit against a cereal company in 2009 was about?', 'question': 'About what?', 'answers': {'A': '"Crunchberries" weren\'t real berries', 'B': 'Cereal box smaller than expected', 'C': 'Cereal too sweet', 'D': 'Both A and B from different suits'}, 'correct': 'A', 'explanation': 'Cap\'n Crunch Crunchberry lawsuit 2009. Judge dismissed: "No reasonable consumer believes crunchberries are real fruit."', 'commentary_correct': 'Correct! Crunchberries.', 'commentary_wrong': 'Crunchberries. Real case.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man sued a fast-food restaurant because?', 'question': 'Why?', 'answers': {'A': 'The mascot scared him', 'B': 'A McDonald\'s coupon expired in his pocket', 'C': 'The toy in a Happy Meal was missing', 'D': 'Both A and C are real cases'}, 'correct': 'D', 'explanation': 'Mascot intimidation suits (Burger King King, etc.) and missing Happy Meal toys — both happened.', 'commentary_correct': 'Correct! Both. Mascot suits exist.', 'commentary_wrong': 'Both. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A woman won $50,000 from a cell phone company because?', 'question': 'Why?', 'answers': {'A': 'Her phone exploded in her purse', 'B': 'Auto-correct ruined her relationship', 'C': 'Her ringtone was annoying', 'D': 'The 4G connection wasn\'t fast enough'}, 'correct': 'A', 'explanation': 'Galaxy Note 7 cases led to multiple settlements. Some over $50K. Samsung had to recall worldwide.', 'commentary_correct': 'Correct! Exploding phone.', 'commentary_wrong': 'Exploding Note 7.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A passenger sued an airline because the flight delay caused her to?', 'question': 'Caused what?', 'answers': {'A': 'Miss her own funeral she was attending', 'B': 'Miss her wedding', 'C': 'Both A and B have happened to different people', 'D': 'A bad meal at her destination'}, 'correct': 'C', 'explanation': 'Both — wedding miss and funeral miss — have been real cases. Airlines usually settle.', 'commentary_correct': 'Correct! Both. Real cases.', 'commentary_wrong': 'Both. Real cases.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Dumbest Lawsuits Ever Won', 'setup': 'A man tried to trademark the phrase "Linsanity" (about Jeremy Lin) before?', 'question': 'Before whom?', 'answers': {'A': 'Lin himself', 'B': 'Nike', 'C': 'The NBA', 'D': 'All of the above'}, 'correct': 'A', 'explanation': 'Andrew W. Slayton trademarked "Linsanity" in 2010 before Lin\'s breakout. Lin had to buy it from him. Real case.', 'commentary_correct': 'Correct! Slayton beat Lin to it.', 'commentary_wrong': 'Random guy. Beat Lin to TM.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # KILLED BY THEIR OWN INVENTIONS
    # ========================================================================
    {'category': 'Killed By Their Own Inventions', 'setup': 'Marie Curie discovered radium and polonium.', 'question': 'What killed her?', 'answers': {'A': 'Aplastic anemia from radiation exposure', 'B': 'A car crash', 'C': 'Plague', 'D': 'Tuberculosis'}, 'correct': 'A', 'explanation': '1934. Her own notebooks remain radioactive and are stored in lead boxes.', 'commentary_correct': 'Correct! Radiation.', 'commentary_wrong': 'Radiation. Her notebooks are still hot.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Henry Smolinski tried to invent what hybrid vehicle?', 'question': 'What invention?', 'answers': {'A': 'A flying Ford Pinto', 'B': 'A submarine motorcycle', 'C': 'An amphibious bus', 'D': 'A solar tank'}, 'correct': 'A', 'explanation': '1973. AVE Mizar — Ford Pinto with detachable wings. Crashed during test flight. Killed Smolinski and pilot.', 'commentary_correct': 'Correct! Flying Pinto.', 'commentary_wrong': 'Flying Pinto. Killed him.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Cowper Phipps Coles invented a new type of?', 'question': 'New type of what?', 'answers': {'A': 'Warship turret', 'B': 'Submarine', 'C': 'Cannon', 'D': 'Lifeboat'}, 'correct': 'A', 'explanation': '1870. HMS Captain. Coles\'s low-freeboard turret ship. Capsized in storm. Coles died with 480 others.', 'commentary_correct': 'Correct! Turret ship.', 'commentary_wrong': 'Turret ship that capsized.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Franz Reichelt invented what kind of suit?', 'question': 'What suit?', 'answers': {'A': 'A parachute suit', 'B': 'A diving suit', 'C': 'A fireproof suit', 'D': 'A flying suit with wings'}, 'correct': 'A', 'explanation': '1912. Jumped off the Eiffel Tower to test his parachute coat. It didn\'t work. Captured on film.', 'commentary_correct': 'Correct! Parachute suit.', 'commentary_wrong': 'Parachute suit. Off the Eiffel Tower.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Thomas Midgley Jr. invented leaded gasoline AND CFCs. What killed him?', 'question': 'How did he go?', 'answers': {'A': 'Strangled by his own polio-recovery rope-and-pulley system', 'B': 'Lead poisoning', 'C': 'Ozone depletion', 'D': 'Mercury exposure'}, 'correct': 'A', 'explanation': '1944. Midgley designed a pulley system to help him out of bed after polio. He got tangled in his ropes and was strangled. Truly cursed inventor.', 'commentary_correct': 'Correct! His own pulley.', 'commentary_wrong': 'His own pulley system.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Horace Lawson Hunley built what military first?', 'question': 'First what?', 'answers': {'A': 'Submarine to sink an enemy ship in combat', 'B': 'Steam-powered tank', 'C': 'Machine gun', 'D': 'Aircraft carrier'}, 'correct': 'A', 'explanation': 'CSS Hunley. First combat submarine. Sank twice in trials (killing Hunley) before successfully attacking in 1864 — then sinking again.', 'commentary_correct': 'Correct! Submarine.', 'commentary_wrong': 'Submarine. Sank multiple times.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Otto Lilienthal was the "Gliding King" of?', 'question': 'When was he killed?', 'answers': {'A': '1896, in a glider crash', 'B': '1910', 'C': '1903', 'D': '1880'}, 'correct': 'A', 'explanation': 'August 1896. Lilienthal\'s glider stalled at 50 feet. Broke his neck. Last words: "Small sacrifices must be made."', 'commentary_correct': 'Correct! 1896.', 'commentary_wrong': '1896 glider crash.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Jean-François de Rozier was the first?', 'question': 'First what?', 'answers': {'A': 'Person to fly in a balloon', 'B': 'Person killed in an air crash', 'C': 'Both A and B', 'D': 'Person to ride a steam train'}, 'correct': 'C', 'explanation': 'Rozière balloon (hot air + hydrogen). Crashed and burned 1785 attempting English Channel crossing. First air crash death.', 'commentary_correct': 'Correct! Both firsts.', 'commentary_wrong': 'Both. First flight + first crash.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Karel Soucek invented what daredevil container?', 'question': 'What container?', 'answers': {'A': 'A barrel for going over Niagara Falls', 'B': 'A car for jumping the Grand Canyon', 'C': 'A submarine for trench dives', 'D': 'A rocket pack'}, 'correct': 'A', 'explanation': '1985. Soucek\'s second barrel stunt — dropped from the Houston Astrodome ceiling. Missed the water tank. Died.', 'commentary_correct': 'Correct! Barrel. Missed the tank.', 'commentary_wrong': 'Barrel. Missed the water.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'William Bullock invented the?', 'question': 'Invented what?', 'answers': {'A': 'Rotary printing press', 'B': 'Telegraph', 'C': 'Lawnmower', 'D': 'Telephone'}, 'correct': 'A', 'explanation': 'Rotary printing press. 1867 his leg got caught in his own press. Gangrene. Died during the amputation.', 'commentary_correct': 'Correct! Printing press.', 'commentary_wrong': 'Printing press caught his leg.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Wan Hu of China (legendary) attached gunpowder rockets to?', 'question': 'To what?', 'answers': {'A': 'A chair (to fly)', 'B': 'A boat', 'C': 'A horse', 'D': 'His own back'}, 'correct': 'A', 'explanation': 'Legendary 16th-century. 47 fireworks rockets to a chair. Lit them all. Disappeared in smoke. May be apocryphal.', 'commentary_correct': 'Correct! Rocket chair.', 'commentary_wrong': 'Rocket chair. Disappeared.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Henry Winstanley built the first?', 'question': 'What did he build?', 'answers': {'A': 'Eddystone Lighthouse', 'B': 'London Bridge', 'C': 'Tower of London', 'D': 'Big Ben'}, 'correct': 'A', 'explanation': '1703. Winstanley was inside his Eddystone Lighthouse during the Great Storm. Storm destroyed both man and lighthouse.', 'commentary_correct': 'Correct! Eddystone Lighthouse.', 'commentary_wrong': 'Lighthouse. The Great Storm got it.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Aurel Vlaicu was a Romanian?', 'question': 'Romanian what?', 'answers': {'A': 'Airplane designer/test pilot', 'B': 'Submarine designer', 'C': 'Tank inventor', 'D': 'Telephone pioneer'}, 'correct': 'A', 'explanation': '1913. Vlaicu II crashed during a Carpathian crossing attempt. Died at 30.', 'commentary_correct': 'Correct! Airplane.', 'commentary_wrong': 'Airplane. Test flight.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Valerian Abakovsky invented what futuristic train?', 'question': 'What kind?', 'answers': {'A': 'A propeller-driven railcar (Aerowagon)', 'B': 'A magnetic levitation train', 'C': 'A nuclear-powered train', 'D': 'A solar train'}, 'correct': 'A', 'explanation': '1921. Aerowagon — train with airplane propeller. Crashed at 90 mph during demo. Abakovsky and 5 others died.', 'commentary_correct': 'Correct! Aerowagon.', 'commentary_wrong': 'Aerowagon. Crashed.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Sieur Freminet invented an early?', 'question': 'Early what?', 'answers': {'A': 'Underwater breathing apparatus', 'B': 'Steam engine', 'C': 'Gunpowder', 'D': 'Telegraph'}, 'correct': 'A', 'explanation': '1772. Designed a re-breather. Used it in trial. Couldn\'t purify own exhalations. Suffocated underwater.', 'commentary_correct': 'Correct! Breathing apparatus.', 'commentary_wrong': 'Re-breather. Didn\'t work.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Max Valier was a German pioneer of what?', 'question': 'Of what?', 'answers': {'A': 'Rocket propulsion', 'B': 'Jet engines', 'C': 'Submarines', 'D': 'Tank design'}, 'correct': 'A', 'explanation': '1930. Liquid-fueled rocket engine exploded on bench test. Shrapnel killed him.', 'commentary_correct': 'Correct! Rockets.', 'commentary_wrong': 'Rocket explosion.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Cleopatra famously tested poisons on prisoners and was supposedly killed by?', 'question': 'Killed by?', 'answers': {'A': 'Self-poisoning via asp bite (disputed)', 'B': 'A sword', 'C': 'Drowning', 'D': 'Natural causes'}, 'correct': 'A', 'explanation': '30 BC. Traditional story: asp bite. Modern historians suggest poison cocktail she\'d researched herself.', 'commentary_correct': 'Correct! Asp / self-poisoning.', 'commentary_wrong': 'Self-poisoning.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Marvin Heemeyer built a tank-armored bulldozer to?', 'question': 'To do what?', 'answers': {'A': 'Destroy his town\'s buildings in revenge', 'B': 'Clear his land', 'C': 'Compete in tractor pulls', 'D': 'Mine coal'}, 'correct': 'A', 'explanation': '2004. Heemeyer modified bulldozer (Killdozer) with welded steel and concrete armor. Destroyed 13 Granby, CO buildings. Suicided.', 'commentary_correct': 'Correct! Killdozer.', 'commentary_wrong': 'Killdozer. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Sylvester Roper invented the steam-powered?', 'question': 'Steam-powered what?', 'answers': {'A': 'Motorcycle', 'B': 'Sailboat', 'C': 'Bicycle that gave him a heart attack', 'D': 'Both A and possibly C'}, 'correct': 'D', 'explanation': '1896. Roper\'s steam motorcycle. He died on it; ambiguous whether crash or heart attack came first.', 'commentary_correct': 'Correct! Steam motorcycle.', 'commentary_wrong': 'Steam motorcycle.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Killed By Their Own Inventions', 'setup': 'Donald Campbell tried to break his own water-speed record in?', 'question': 'In what boat?', 'answers': {'A': 'Bluebird K7', 'B': 'Spirit of Australia', 'C': 'Miss Britain III', 'D': 'Rolls-Royce II'}, 'correct': 'A', 'explanation': '1967. Bluebird K7 jet boat flipped at 300+ mph on Coniston Water. Body recovered in 2001.', 'commentary_correct': 'Correct! Bluebird K7.', 'commentary_wrong': 'Bluebird K7.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # OLYMPIC SCANDALS
    # ========================================================================
    {'category': 'Olympic Scandals', 'setup': 'In 1994, an ice skater\'s rival was attacked.', 'question': 'Who was attacked?', 'answers': {'A': 'Nancy Kerrigan', 'B': 'Tonya Harding', 'C': 'Surya Bonaly', 'D': 'Oksana Baiul'}, 'correct': 'A', 'explanation': 'Kerrigan kneecapped by hitmen tied to Harding\'s ex-husband. Harding pleaded guilty to conspiracy.', 'commentary_correct': 'Correct! Kerrigan. The kneecapping.', 'commentary_wrong': 'Kerrigan. The kneecap heard \'round the world.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'In 1988, Ben Johnson was stripped of his Olympic gold for?', 'question': 'Stripped for?', 'answers': {'A': 'Stanozolol (steroid)', 'B': 'EPO', 'C': 'Caffeine', 'D': 'Marijuana'}, 'correct': 'A', 'explanation': 'Seoul 1988 100m. Johnson tested positive for stanozolol. Stripped within 3 days.', 'commentary_correct': 'Correct! Stanozolol.', 'commentary_wrong': 'Stanozolol. Career over.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Marion Jones won 5 Olympic medals in 2000, then?', 'question': 'Then what?', 'answers': {'A': 'Admitted doping and surrendered all 5', 'B': 'Retired peacefully', 'C': 'Became a coach', 'D': 'Won 5 more in 2004'}, 'correct': 'A', 'explanation': '2007. Jones admitted using PEDs. Surrendered Olympic medals. Sentenced to 6 months prison.', 'commentary_correct': 'Correct! All 5.', 'commentary_wrong': 'All 5 medals gone.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': '2002 Salt Lake bid scandal involved?', 'question': 'What scandal?', 'answers': {'A': 'IOC members took bribes from Salt Lake City', 'B': 'Athletes were doped en masse', 'C': 'Stadium collapsed', 'D': 'Mascot was offensive'}, 'correct': 'A', 'explanation': 'Bid committee gave IOC members gifts/cash/college tuition. 10 IOC members expelled.', 'commentary_correct': 'Correct! Bribery.', 'commentary_wrong': 'Bribery scandal.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Russian state-sponsored doping was exposed in?', 'question': 'When?', 'answers': {'A': '2015 (McLaren Report)', 'B': '2010', 'C': '2020', 'D': '1980'}, 'correct': 'A', 'explanation': '2015-2016. Whistleblower Grigory Rodchenkov exposed state lab. Documentary Icarus. Russia banned from many events.', 'commentary_correct': 'Correct! 2015 McLaren Report.', 'commentary_wrong': '2015. McLaren Report.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'In 1976, a Soviet fencer was disqualified for?', 'question': 'For what?', 'answers': {'A': 'Wired epee that registered fake hits', 'B': 'Bribing referees', 'C': 'Wearing a mask', 'D': 'Stealing equipment'}, 'correct': 'A', 'explanation': 'Boris Onishchenko, Soviet pentathlete. Hid a switch in his epee to register hits without touching. Banned for life.', 'commentary_correct': 'Correct! Wired epee.', 'commentary_wrong': 'Wired epee. Banned for life.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': '1976 East German swimming team won 11 of 13 women\'s events. Decades later?', 'question': 'Decades later?', 'answers': {'A': 'Doctors confirmed systematic state doping', 'B': 'Records were left intact', 'C': 'Athletes denied any wrongdoing', 'D': 'Coaches received medals retroactively'}, 'correct': 'A', 'explanation': 'Documents revealed systematic state-sponsored steroid program. Some swimmers had testosterone-driven changes that persisted.', 'commentary_correct': 'Correct! State doping confirmed.', 'commentary_wrong': 'State doping. Systematic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'At 2002 Salt Lake City, pairs figure skating had what scandal?', 'question': 'Scandal?', 'answers': {'A': 'French judge admitted vote-trading; both Russian and Canadian pairs awarded gold', 'B': 'A skater bribed judges with money', 'C': 'A skating coach was a spy', 'D': 'The ice was sabotaged'}, 'correct': 'A', 'explanation': 'Marie-Reine Le Gougne admitted bias. Russians + Canadians both got gold. Skating judging system overhauled.', 'commentary_correct': 'Correct! Vote-trading.', 'commentary_wrong': 'Vote-trading. Two golds awarded.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Larry Nassar was the team doctor for which sport?', 'question': 'Sport?', 'answers': {'A': 'USA Gymnastics', 'B': 'USA Swimming', 'C': 'USA Wrestling', 'D': 'USA Figure Skating'}, 'correct': 'A', 'explanation': 'Nassar sexually abused hundreds of gymnasts over decades. Sentenced to 60+ years. Major reform of US gymnastics.', 'commentary_correct': 'Correct! Gymnastics.', 'commentary_wrong': 'Gymnastics. Nassar.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Hassiba Boulmerka was an Algerian Olympic champion who received what after winning?', 'question': 'What followed her victory?', 'answers': {'A': 'Death threats from religious extremists', 'B': 'A movie deal', 'C': 'A book contract', 'D': 'A diplomatic post'}, 'correct': 'A', 'explanation': '1992 1500m gold. Extremists in Algeria threatened her over wearing shorts. She had to train abroad.', 'commentary_correct': 'Correct! Death threats.', 'commentary_wrong': 'Death threats.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Soviet weightlifter Vasily Alekseyev set 80 world records but never failed a doping test because?', 'question': 'Why?', 'answers': {'A': 'Testing wasn\'t sophisticated enough at the time', 'B': 'He was clean', 'C': 'He bribed officials', 'D': 'He had a medical exemption'}, 'correct': 'A', 'explanation': 'Testing in the 1970s couldn\'t detect many compounds in use. Soviet weightlifting was openly using steroids.', 'commentary_correct': 'Correct! Testing was primitive.', 'commentary_wrong': 'Primitive testing.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': '1992 Spanish basketball player\'s real claim was?', 'question': 'Claim was?', 'answers': {'A': 'They were "intellectually disabled" — many weren\'t, but Spain still won gold', 'B': 'They were all under 18 when they weren\'t', 'C': 'They were medical workers', 'D': 'They were robots'}, 'correct': 'A', 'explanation': '2000 Sydney Paralympics. Spanish ID basketball team — most weren\'t disabled. Gold rescinded. Scandal.', 'commentary_correct': 'Correct! Paralympic fraud.', 'commentary_wrong': 'Paralympic fraud.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': '2008 Beijing — Chinese gymnasts were accused of?', 'question': 'Accused of what?', 'answers': {'A': 'Being underage (younger than the 16 minimum)', 'B': 'Doping', 'C': 'Match-fixing', 'D': 'Faking injuries'}, 'correct': 'A', 'explanation': 'Multiple Chinese gymnasts (He Kexin, Yang Yilin) had birthdate inconsistencies. Investigation found nothing conclusive.', 'commentary_correct': 'Correct! Underage allegations.', 'commentary_wrong': 'Underage allegations.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'In 2012, Olympic badminton had what unprecedented scandal?', 'question': 'Scandal?', 'answers': {'A': '8 players disqualified for trying to LOSE to get better matchups', 'B': 'Doping', 'C': 'Shuttlecock tampering', 'D': 'Fake ID'}, 'correct': 'A', 'explanation': 'London 2012. 8 women\'s doubles players tried to lose to manipulate brackets. Disqualified.', 'commentary_correct': 'Correct! Trying to LOSE.', 'commentary_wrong': 'Trying to lose. Disqualified.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Madeline Manning had her 1968 Olympic gold delayed because of?', 'question': 'Because?', 'answers': {'A': 'No reason — she got it', 'B': 'A protest', 'C': 'A failed drug test (later cleared)', 'D': 'A timing dispute'}, 'correct': 'A', 'explanation': 'Trick question; Manning won 800m clean in 1968. No scandal. Asked to confirm baseline.', 'commentary_correct': 'Correct! No issue.', 'commentary_wrong': 'No issue. Clean win.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Caster Semenya has had Olympic medals affected by?', 'question': 'By what controversy?', 'answers': {'A': 'Testosterone levels above World Athletics thresholds', 'B': 'Doping', 'C': 'Wrong category', 'D': 'Wrong country'}, 'correct': 'A', 'explanation': 'Naturally high testosterone. New rules force hormone suppression. Semenya refused, lost eligibility. Court cases ongoing.', 'commentary_correct': 'Correct! Testosterone rules.', 'commentary_wrong': 'Testosterone. Controversial.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'The 1972 Munich Olympics is remembered for?', 'question': 'Why?', 'answers': {'A': 'A tragic terrorist attack on Israeli athletes', 'B': 'A great basketball game', 'C': 'The first commercial Olympics', 'D': 'A new track surface'}, 'correct': 'A', 'explanation': '11 Israeli team members killed by Black September. Games continued. Mossad later pursued perpetrators.', 'commentary_correct': 'Correct! Munich tragedy.', 'commentary_wrong': 'Munich. Tragedy.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': '1980 Moscow Olympics was boycotted by what country?', 'question': 'Boycotting country?', 'answers': {'A': 'USA (over Soviet invasion of Afghanistan)', 'B': 'France', 'C': 'Japan', 'D': 'Iran'}, 'correct': 'A', 'explanation': 'Jimmy Carter led 65-nation boycott. Soviets retaliated with own boycott in 1984.', 'commentary_correct': 'Correct! USA.', 'commentary_wrong': 'USA boycott.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'Boxer Roy Jones Jr. was robbed at Seoul 1988 by?', 'question': 'Robbed how?', 'answers': {'A': 'Korean judges (controversial 3-2 split decision against him)', 'B': 'Equipment theft', 'C': 'Coaching change', 'D': 'A pre-fight cancellation'}, 'correct': 'A', 'explanation': '1988 final. Jones landed 86 punches to opponent\'s 32. Lost 3-2. International outrage. Computer scoring later introduced.', 'commentary_correct': 'Correct! 86-32, still lost.', 'commentary_wrong': '86-32. Still lost.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Olympic Scandals', 'setup': 'IOC has refused to investigate Olympic Russia banning regardless of?', 'question': 'Of what?', 'answers': {'A': 'McLaren Report and Rodchenkov whistleblower testimony', 'B': 'WADA test results', 'C': 'Athlete protests', 'D': 'All — they\'ve been criticized for inaction'}, 'correct': 'D', 'explanation': 'IOC slow to fully ban Russia. ROC (Russian Olympic Committee) under neutral flag is one workaround. Critics call it insufficient.', 'commentary_correct': 'Correct! All. Slow IOC.', 'commentary_wrong': 'All. IOC criticism.', 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # HISTORICAL HOAXES
    # ========================================================================
    {'category': 'Historical Hoaxes', 'setup': 'The Cardiff Giant (1869) was a fake what?', 'question': 'Fake what?', 'answers': {'A': 'A 10-foot fossilized "ancient man"', 'B': 'A dinosaur skeleton', 'C': 'An alien body', 'D': 'A mummy'}, 'correct': 'A', 'explanation': 'Tobacconist George Hull carved a "giant" from gypsum, buried it. Charged admission. P.T. Barnum tried to buy it.', 'commentary_correct': 'Correct! Cardiff Giant.', 'commentary_wrong': 'Cardiff Giant.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'Piltdown Man (1912-1953) was claimed to be?', 'question': 'Claimed as?', 'answers': {'A': 'Missing-link human evolution fossil', 'B': 'Atlantis evidence', 'C': 'A new dinosaur species', 'D': 'A unicorn'}, 'correct': 'A', 'explanation': 'Charles Dawson\'s "discovery" was a modern human skull + orangutan jaw. Fooled science 40+ years. Exposed by fluorine testing.', 'commentary_correct': 'Correct! Missing link hoax.', 'commentary_wrong': 'Missing link hoax.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Hitler Diaries (1983) were sold to which magazine?', 'question': 'Magazine?', 'answers': {'A': 'Stern (Germany)', 'B': 'Time', 'C': 'Life', 'D': 'Der Spiegel'}, 'correct': 'A', 'explanation': 'Stern paid $4M for fake diaries by Konrad Kujau. Exposed by paper-fiber analysis (paper was post-WWII).', 'commentary_correct': 'Correct! Stern.', 'commentary_wrong': 'Stern. $4M wasted.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Berners Street Hoax (1810) involved what?', 'question': 'What was the prank?', 'answers': {'A': 'Theodore Hook tricked thousands of tradespeople to deliver goods to one house', 'B': 'A fake funeral', 'C': 'A spy ring', 'D': 'A counterfeit currency operation'}, 'correct': 'A', 'explanation': 'Theodore Hook made a bet. Sent fake messages to ~4000 tradesmen to deliver goods to 54 Berners Street. Chaos.', 'commentary_correct': 'Correct! 4000 deliveries.', 'commentary_wrong': '4000 deliveries.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Cottingley Fairies (1917) were photos by?', 'question': 'Photographer?', 'answers': {'A': 'Two young cousins (Elsie + Frances)', 'B': 'A professional photographer', 'C': 'A spirit medium', 'D': 'Arthur Conan Doyle (he was hoaxed by them)'}, 'correct': 'A', 'explanation': 'Cousins photographed paper-cutout fairies. Sir Arthur Conan Doyle published as real. Admitted hoax in 1980s.', 'commentary_correct': 'Correct! Two cousins.', 'commentary_wrong': 'Two cousins.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Great Moon Hoax (1835) was a series of?', 'question': 'What kind of fake?', 'answers': {'A': 'NY Sun articles describing life on the moon (with bat-people)', 'B': 'Fake constellation maps', 'C': 'Forged comet sightings', 'D': 'Manufactured moon rocks'}, 'correct': 'A', 'explanation': 'NY Sun published 6 articles claiming Sir John Herschel saw moon life via telescope. Boosted circulation. Never retracted.', 'commentary_correct': 'Correct! Moon bat-people.', 'commentary_wrong': 'Moon bat-people. NY Sun.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Donation of Constantine (8th century) was a forged document granting?', 'question': 'Granting what?', 'answers': {'A': 'Authority over the Western Empire to the Pope', 'B': 'Land to Constantinople', 'C': 'Citizenship to Romans', 'D': 'Bread to the army'}, 'correct': 'A', 'explanation': '8th-century forgery used by Popes to justify temporal power. Exposed by Lorenzo Valla in 1440. One of history\'s most consequential forgeries.', 'commentary_correct': 'Correct! Donation of Constantine.', 'commentary_wrong': 'Pope power forgery.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The "Sokal Affair" (1996) was when a physicist?', 'question': 'What did Sokal do?', 'answers': {'A': 'Published a deliberately absurd paper in a postmodern journal', 'B': 'Faked a Nobel Prize', 'C': 'Claimed cold fusion worked', 'D': 'Plagiarized Einstein'}, 'correct': 'A', 'explanation': 'Alan Sokal submitted nonsense paper to Social Text. Got published. Revealed it was a hoax. Famous academic prank.', 'commentary_correct': 'Correct! Sokal affair.', 'commentary_wrong': 'Sokal affair. Iconic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The "Protocols of the Elders of Zion" was a forged?', 'question': 'Forged what?', 'answers': {'A': 'Antisemitic propaganda text', 'B': 'Trade agreement', 'C': 'Religious gospel', 'D': 'Historical chronicle'}, 'correct': 'A', 'explanation': 'Late 1800s Russian forgery. Hugely damaging — used by Nazis and antisemites. Definitively debunked as forgery.', 'commentary_correct': 'Correct! Antisemitic forgery.', 'commentary_wrong': 'Antisemitic forgery. Debunked.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Voynich Manuscript is a?', 'question': 'What is it?', 'answers': {'A': '15th-century book in an unreadable script (possibly hoax)', 'B': 'A 19th-century forgery', 'C': 'A modern hoax', 'D': 'A definitively real ancient text'}, 'correct': 'A', 'explanation': 'Genuine medieval book; script remains undeciphered. Some scholars argue it\'s a meaningless hoax from the period.', 'commentary_correct': 'Correct! Voynich.', 'commentary_wrong': 'Voynich Manuscript.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'In 1938, Orson Welles\'s War of the Worlds radio broadcast?', 'question': 'What happened?', 'answers': {'A': 'Caused panic — listeners thought aliens were attacking', 'B': 'Was banned by FCC', 'C': 'Won an Emmy', 'D': 'Crashed radio stations'}, 'correct': 'A', 'explanation': 'Halloween Eve 1938. Realistic news-format alien invasion drama. Some listeners panicked. Real audience size disputed.', 'commentary_correct': 'Correct! Real panic.', 'commentary_wrong': 'Real panic.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Loch Ness Monster "surgeon\'s photo" (1934) was?', 'question': 'What was it really?', 'answers': {'A': 'A toy submarine with attached neck', 'B': 'A genuine creature', 'C': 'A floating log', 'D': 'A bird'}, 'correct': 'A', 'explanation': 'Christian Spurling confessed in 1994. Hoax orchestrated by Marmaduke Wetherell. Plastic neck on toy sub.', 'commentary_correct': 'Correct! Toy sub.', 'commentary_wrong': 'Toy submarine.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Bigfoot "Patterson-Gimlin Film" (1967) is?', 'question': 'Status?', 'answers': {'A': 'Still debated; most experts say man in costume', 'B': 'Definitively real', 'C': 'Confessed hoax 1990s', 'D': 'Lost media'}, 'correct': 'A', 'explanation': 'Bob Heironimus claimed to wear the suit. No definitive proof either way. Believers and skeptics dig in.', 'commentary_correct': 'Correct! Still debated.', 'commentary_wrong': 'Still debated.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'Anastasia Manahan claimed for decades to be?', 'question': 'Claimed to be?', 'answers': {'A': 'The surviving Russian Grand Duchess Anastasia', 'B': 'Anna Frank', 'C': 'Lost Princess Diana child', 'D': 'A Tudor princess'}, 'correct': 'A', 'explanation': 'Anna Anderson. Famously claimed to be Anastasia from 1920s. DNA in 1994 proved she was Polish factory worker.', 'commentary_correct': 'Correct! Anna Anderson.', 'commentary_wrong': 'Anna Anderson. DNA proved.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Tasaday people (Philippines, 1971) were claimed to be?', 'question': 'Claimed to be?', 'answers': {'A': 'An uncontacted Stone Age tribe', 'B': 'Aliens', 'C': 'Lost American GIs', 'D': 'A new species'}, 'correct': 'A', 'explanation': 'Philippine government claimed to have "discovered" stone-age tribe in 1971. Later investigations: hoax, with locals paid to play roles.', 'commentary_correct': 'Correct! Tasaday hoax.', 'commentary_wrong': 'Tasaday.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': '"The Hitler Diary of Eva Braun" appeared in?', 'question': 'When did this hoax appear?', 'answers': {'A': '1983 (related to the Stern Hitler Diaries hoax)', 'B': '1970', 'C': '2010', 'D': '1945'}, 'correct': 'A', 'explanation': 'Related forgery during the Stern Hitler Diaries period. Konrad Kujau forged many.', 'commentary_correct': 'Correct! 1983.', 'commentary_wrong': '1983. Related to Stern.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Vinland Map (claimed Norse map of America pre-Columbus) was?', 'question': 'Status?', 'answers': {'A': 'Declared forgery in 2021', 'B': 'Definitively real', 'C': 'Lost', 'D': 'Burned'}, 'correct': 'A', 'explanation': 'Yale\'s 2021 analysis confirmed modern ink (post-1923 titanium). After decades of debate.', 'commentary_correct': 'Correct! Forgery confirmed 2021.', 'commentary_wrong': 'Forgery. 2021.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The "Spaghetti Tree" hoax (1957) was?', 'question': 'What was it?', 'answers': {'A': 'A BBC April Fool showing pasta "harvested" from trees', 'B': 'A real agricultural attempt', 'C': 'A film prop', 'D': 'A genetic experiment'}, 'correct': 'A', 'explanation': 'April 1, 1957 Panorama segment. Hundreds called BBC asking how to grow spaghetti trees.', 'commentary_correct': 'Correct! BBC April Fool.', 'commentary_wrong': 'BBC April Fool 1957.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'Operation Mincemeat (WWII) was a successful Allied hoax involving?', 'question': 'Involving?', 'answers': {'A': 'A corpse with fake documents to mislead Nazis', 'B': 'Fake aircraft', 'C': 'Wooden tanks', 'D': 'Cardboard ships'}, 'correct': 'A', 'explanation': '1943. British dropped corpse with fake invasion plans into Spanish waters. Misled Nazis about Sicily invasion. Real and key to D-Day deception.', 'commentary_correct': 'Correct! Corpse hoax.', 'commentary_wrong': 'Corpse hoax. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Hoaxes', 'setup': 'The Crop Circles started as a serious paranormal mystery, but?', 'question': 'What revealed?', 'answers': {'A': 'Two British men confessed in 1991 to creating them with planks', 'B': 'They\'re actually aliens', 'C': 'Wind makes them', 'D': 'They\'re art installations'}, 'correct': 'A', 'explanation': 'Doug Bower and Dave Chorley admitted in 1991 to creating UK crop circles since 1978. Used planks and rope. Started a global phenomenon.', 'commentary_correct': 'Correct! Two guys with planks.', 'commentary_wrong': 'Two guys with planks.', 'difficulty': 'medium', 'time_limit': 15},

    # ========================================================================
    # ROYAL FAMILY EMBARRASSMENTS
    # ========================================================================
    {'category': 'Royal Family Embarrassments', 'setup': 'A 1993 leaked phone call between Prince Charles and Camilla included?', 'question': 'Featured what?', 'answers': {'A': 'Charles wishing to be reincarnated as a tampon', 'B': 'Discussion of Diana', 'C': 'A song', 'D': 'Both A and B'}, 'correct': 'A', 'explanation': '"Camillagate." Leaked 1989 phone call. Charles\'s comment shocked the world. Tabloid feast.', 'commentary_correct': 'Correct! The tampon comment.', 'commentary_wrong': 'The tampon comment.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Prince Andrew\'s 2019 BBC Newsnight interview was about?', 'question': 'About what?', 'answers': {'A': 'His friendship with Jeffrey Epstein', 'B': 'A children\'s charity', 'C': 'Brexit', 'D': 'A horse race'}, 'correct': 'A', 'explanation': 'Disastrous attempt to explain Epstein ties. "Pizza Express in Woking" alibi. Settled civil case in 2022.', 'commentary_correct': 'Correct! Epstein.', 'commentary_wrong': 'Epstein. The Pizza Express defense.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Henry VIII had how many wives?', 'question': 'How many?', 'answers': {'A': 'Six', 'B': 'Four', 'C': 'Two', 'D': 'Twelve'}, 'correct': 'A', 'explanation': 'Six wives. Two beheaded, one died in childbirth, one died of natural causes, two survived him. Mnemonic: "divorced, beheaded, died, divorced, beheaded, survived."', 'commentary_correct': 'Correct! Six.', 'commentary_wrong': 'Six. Famously.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Prince William\'s most embarrassing 2008 moment was?', 'question': 'What happened?', 'answers': {'A': 'He used an RAF helicopter to fly to a friend\'s stag party', 'B': 'He fell at a polo match', 'C': 'He was photographed asleep', 'D': 'He wore a kilt incorrectly'}, 'correct': 'A', 'explanation': '2008 — flew RAF helicopter to bachelor party. Public outcry over use of military resources. Apologized.', 'commentary_correct': 'Correct! RAF helicopter.', 'commentary_wrong': 'RAF helicopter to stag.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Prince Harry\'s 2005 Nazi costume incident was at?', 'question': 'At what event?', 'answers': {'A': 'A "colonial and native" themed party', 'B': 'A school dance', 'C': 'A military ceremony', 'D': 'A movie premiere'}, 'correct': 'A', 'explanation': 'Harry wore swastika armband to friend\'s fancy dress party 2005. Public outrage. Issued apology.', 'commentary_correct': 'Correct! Nazi costume.', 'commentary_wrong': 'Nazi costume. 2005.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'King George IV\'s 1820 attempt to divorce Queen Caroline turned into?', 'question': 'Turned into what?', 'answers': {'A': 'A public trial that backfired and made her popular', 'B': 'A war with Italy', 'C': 'A peaceful divorce', 'D': 'A quiet exile'}, 'correct': 'A', 'explanation': 'Trial of Queen Caroline. Bill of Pains tried to remove her. Public rallied to her side. Bill withdrawn. She died soon after.', 'commentary_correct': 'Correct! Backfired trial.', 'commentary_wrong': 'Backfired trial.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Princess Diana\'s 1995 Panorama interview admitted?', 'question': 'Admitted what?', 'answers': {'A': 'Affair with James Hewitt; "three of us in this marriage"', 'B': 'Cocaine use', 'C': 'A secret child', 'D': 'A divorce filing'}, 'correct': 'A', 'explanation': 'Bashir Panorama interview. "There were three of us in this marriage." The Camilla reference. Interview later found to have been obtained by deception.', 'commentary_correct': 'Correct! "Three of us."', 'commentary_wrong': '"Three of us in this marriage."', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Edward VIII abdicated in 1936 to marry?', 'question': 'To marry?', 'answers': {'A': 'A twice-divorced American (Wallis Simpson)', 'B': 'A French actress', 'C': 'A Russian princess', 'D': 'A maid'}, 'correct': 'A', 'explanation': 'Wallis Simpson. Caused the abdication crisis. Brother George VI became king. Edward became Duke of Windsor.', 'commentary_correct': 'Correct! Wallis Simpson.', 'commentary_wrong': 'Wallis Simpson. Abdication.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Princess Margaret was famous for what unroyal habits?', 'question': 'For what?', 'answers': {'A': 'Cigarettes, parties, and drinking', 'B': 'Bridge tournaments', 'C': 'Knitting', 'D': 'Marathons'}, 'correct': 'A', 'explanation': 'Wild party princess. Caribbean affairs. Famous for chain-smoking and drinking. Subject of The Crown stories.', 'commentary_correct': 'Correct! Wild Princess.', 'commentary_wrong': 'Wild Princess.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'King James VI/I (1566-1625) had a peculiar habit involving?', 'question': 'Habit?', 'answers': {'A': 'Refusing to bathe', 'B': 'Wearing gloves while eating', 'C': 'Hating tobacco vehemently', 'D': 'All of the above'}, 'correct': 'D', 'explanation': 'James I hated bathing (called it dangerous), wore gloves to avoid germs, wrote "Counterblaste to Tobacco." Disliked many things.', 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Catherine the Great\'s lovers included approximately how many over her lifetime?', 'question': 'Number?', 'answers': {'A': '12 documented', 'B': '50+', 'C': '0', 'D': '4'}, 'correct': 'A', 'explanation': '12 documented over 30 years. The "horse" legend is a fabrication by detractors. Genuine record is fascinating but more normal.', 'commentary_correct': 'Correct! 12.', 'commentary_wrong': '12. Horse story is fake.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'In 2020, Prince Harry and Meghan made what announcement?', 'question': 'Announcement?', 'answers': {'A': 'Stepping back from royal duties ("Megxit")', 'B': 'Moving to a tropical island', 'C': 'Both stepping back and moving to LA', 'D': 'Quitting the family entirely'}, 'correct': 'C', 'explanation': 'January 2020 — stepped back as senior royals. Eventually moved to California. Oprah interview followed in 2021.', 'commentary_correct': 'Correct! Megxit + LA.', 'commentary_wrong': 'Megxit. To LA.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'The future George IV was famous in his time for being?', 'question': 'For?', 'answers': {'A': 'Extremely obese and unfashionable', 'B': 'Skinny and elegant', 'C': 'Athletic and fit', 'D': 'Mostly absent'}, 'correct': 'A', 'explanation': 'Beau Brummell\'s comments about Prince Regent\'s weight ended their friendship. Caricatures of George IV were merciless.', 'commentary_correct': 'Correct! Obese.', 'commentary_wrong': 'Obese. Heavy regent.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Prince Philip\'s famous gaffes included what notable one in China (1986)?', 'question': 'Said what?', 'answers': {'A': 'Called Chinese students "slitty-eyed"', 'B': 'Insulted the Great Wall', 'C': 'Refused tea', 'D': 'Asked for English food'}, 'correct': 'A', 'explanation': 'Said "If you stay here much longer, you\'ll all be slitty-eyed" to British students in China. Reported worldwide. Major diplomatic embarrassment.', 'commentary_correct': 'Correct! Said the quiet part loud.', 'commentary_wrong': 'A gaffe heard worldwide.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Princess Anne in 1974 survived what?', 'question': 'Survived?', 'answers': {'A': 'A kidnap attempt', 'B': 'A car crash', 'C': 'A plane crash', 'D': 'A horse fall'}, 'correct': 'A', 'explanation': '1974 Pall Mall. Ian Ball tried to kidnap her. She famously said "Not bloody likely!" Driver and protection officer wounded.', 'commentary_correct': 'Correct! "Not bloody likely!"', 'commentary_wrong': '"Not bloody likely!"', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Queen Victoria refused to acknowledge what for 9 years after her husband\'s death?', 'question': 'Refused to do what?', 'answers': {'A': 'Public appearances', 'B': 'Wear color', 'C': 'Speak in parliament', 'D': 'All of the above'}, 'correct': 'D', 'explanation': 'After Albert\'s death 1861, Victoria withdrew. Wore black for life. Public appearances rare. Republican movement grew during this period.', 'commentary_correct': 'Correct! All. The Widow of Windsor.', 'commentary_wrong': 'All. The Widow of Windsor.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'In 2012, photos of which royal sunbathing topless leaked?', 'question': 'Who?', 'answers': {'A': 'Kate Middleton', 'B': 'Meghan Markle', 'C': 'Camilla', 'D': 'Princess Eugenie'}, 'correct': 'A', 'explanation': '2012 French magazine published photos. Royals sued and won damages.', 'commentary_correct': 'Correct! Kate.', 'commentary_wrong': 'Kate. French paparazzi.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Prince Charles\'s correspondence with politicians (the "black spider memos") revealed?', 'question': 'Revealed?', 'answers': {'A': 'He lobbied ministers on personal interests', 'B': 'He was a Soviet spy', 'C': 'He had a code name', 'D': 'He was abolishing parliament'}, 'correct': 'A', 'explanation': 'Released 2015. Showed Charles writing to ministers about herbal medicine, architecture, etc. Critics called it constitutional overstep.', 'commentary_correct': 'Correct! Lobbied ministers.', 'commentary_wrong': 'Lobbied ministers.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Caligula (Roman emperor) tried to make whom a senator?', 'question': 'Made whom senator?', 'answers': {'A': 'His horse, Incitatus', 'B': 'His sister', 'C': 'A slave', 'D': 'A goose'}, 'correct': 'A', 'explanation': 'Suetonius reports Caligula tried to make his horse Incitatus consul. Senate disagreed.', 'commentary_correct': 'Correct! The horse.', 'commentary_wrong': 'The horse.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Royal Family Embarrassments', 'setup': 'Tsar Nicholas II\'s family treated their hemophiliac son with what unusual figure?', 'question': 'Who treated him?', 'answers': {'A': 'Rasputin', 'B': 'Tolstoy', 'C': 'Dostoevsky', 'D': 'Lenin'}, 'correct': 'A', 'explanation': 'Rasputin\'s influence over the Romanovs through son Alexei\'s hemophilia treatment was a major factor in Russian Revolution.', 'commentary_correct': 'Correct! Rasputin.', 'commentary_wrong': 'Rasputin.', 'difficulty': 'medium', 'time_limit': 15},

    # ========================================================================
    # REALITY TV ATROCITIES
    # ========================================================================
    {'category': 'Reality TV Atrocities', 'setup': 'In a 2009 Bachelor finale, Jason Mesnick proposed to Melissa, then?', 'question': 'Then what?', 'answers': {'A': 'Dumped her on live TV and picked his runner-up', 'B': 'Eloped', 'C': 'Disappeared', 'D': 'Asked for a refund'}, 'correct': 'A', 'explanation': 'Real moment. Proposed at finale. Live "After the Final Rose" episode, dumped Melissa, picked Molly. Bachelor Nation freaked.', 'commentary_correct': 'Correct! Dumped live.', 'commentary_wrong': 'Dumped live.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Survivor: Pearl Islands (2003) had what tribal council mishap?', 'question': 'What happened?', 'answers': {'A': 'Lill cried so much, no one could vote', 'B': 'A snake bit a contestant on camera', 'C': 'The fire wouldn\'t start', 'D': 'A tribal totem fell on Jeff Probst'}, 'correct': 'B', 'explanation': 'Real snake bites have happened on Survivor. Many other production mishaps too.', 'commentary_correct': 'Correct! Snake bite.', 'commentary_wrong': 'Snake bite. Real.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Big Brother season 1 had a contestant?', 'question': 'What happened?', 'answers': {'A': 'Quit after one night', 'B': 'Was removed for fighting', 'C': 'Pulled a knife on a housemate', 'D': 'Did all three across various seasons'}, 'correct': 'C', 'explanation': 'Big Brother US season 9 (2008). Contestant pulled a knife. Removed. Real.', 'commentary_correct': 'Correct! Knife.', 'commentary_wrong': 'Knife pulling. Real.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The Real World (1992-) is credited with what?', 'question': 'Credited with what?', 'answers': {'A': 'Inventing modern reality TV format', 'B': 'Funding MTV', 'C': 'Both', 'D': 'Being the first scripted "reality" show'}, 'correct': 'C', 'explanation': 'Both. The Real World pioneered the modern reality format that birthed every subsequent reality show.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Ground zero.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The Bachelor franchise has produced how many successful marriages?', 'question': 'Approximate?', 'answers': {'A': '~10 (out of 40+ seasons combined)', 'B': '20', 'C': '0', 'D': '5'}, 'correct': 'A', 'explanation': 'Out of 50+ combined Bachelor/Bachelorette seasons, only ~10 have produced lasting marriages. Roughly 80% break up.', 'commentary_correct': 'Correct! ~10 out of 50+.', 'commentary_wrong': '~10. Mostly fail.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'A 2008 reality show was cancelled mid-shoot when contestants?', 'question': 'When what?', 'answers': {'A': 'Discovered they were on the show "Joe Schmo 2" (not what they thought)', 'B': 'Quit en masse', 'C': 'Were arrested', 'D': 'Got stranded for real'}, 'correct': 'A', 'explanation': 'Joe Schmo seasons all have a single real contestant. Has been done multiple times.', 'commentary_correct': 'Correct! Schmo style.', 'commentary_wrong': 'Schmo style.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The Apprentice (US) had how many seasons before Trump\'s political career took over?', 'question': 'How many?', 'answers': {'A': '15 (including Celebrity Apprentice)', 'B': '5', 'C': '20', 'D': '3'}, 'correct': 'A', 'explanation': '15 total seasons through 2015. Various celebrities. Trump\'s political ascent ended his TV career.', 'commentary_correct': 'Correct! 15.', 'commentary_wrong': '15. Then politics.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Real Housewives of New Jersey had a famous 2009 incident with?', 'question': 'Featuring what?', 'answers': {'A': 'Teresa Giudice flipping a table', 'B': 'A horse fight', 'C': 'A car chase', 'D': 'A food fight'}, 'correct': 'A', 'explanation': '"You\'re engaged? PROSTITUTION WHORE!" Table flip became iconic. Real.', 'commentary_correct': 'Correct! Table flip.', 'commentary_wrong': 'Table flip.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Naked Attraction (UK, 2016-) is a dating show where?', 'question': 'What\'s the gimmick?', 'answers': {'A': 'Contestants are nude from the start', 'B': 'No talking allowed', 'C': 'Held in a sauna', 'D': 'Both A and B'}, 'correct': 'A', 'explanation': 'Channel 4. Contestants reveal their bodies in stages. Picker chooses without faces visible. Extremely controversial.', 'commentary_correct': 'Correct! Nude.', 'commentary_wrong': 'Nude. Controversial.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Hell\'s Kitchen has Gordon Ramsay yell at contestants for?', 'question': 'For what?', 'answers': {'A': 'Risotto being undercooked or overcooked', 'B': 'Lamb sauce being missing', 'C': 'Both A and B famously', 'D': 'A different specific dish each season'}, 'correct': 'C', 'explanation': 'Risotto and lamb sauce are recurring Ramsay obsessions. "WHERE\'S THE LAMB SAUCE?!" memes.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Lamb sauce!', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The Real World: New York (1992) cast member died of?', 'question': 'How?', 'answers': {'A': 'AIDS (Pedro Zamora, 1994)', 'B': 'Car accident', 'C': 'Drug overdose', 'D': 'Murder'}, 'correct': 'A', 'explanation': 'Pedro Zamora openly gay HIV+ contestant. Died in 1994 at 22. Educated millions about HIV/AIDS.', 'commentary_correct': 'Correct! Pedro Zamora.', 'commentary_wrong': 'Pedro Zamora.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Married at First Sight pairs strangers who?', 'question': 'Who do what?', 'answers': {'A': 'Marry at first meeting', 'B': 'Decide whether to stay married after 8 weeks', 'C': 'Both', 'D': 'Get fake-married only'}, 'correct': 'C', 'explanation': 'Real legal marriages. 8 weeks together, then decide to stay or divorce. ~30% success rate. Real divorces follow.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real marriages.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Toddlers & Tiaras was criticized for?', 'question': 'For what?', 'answers': {'A': 'Sexualizing children', 'B': 'Promoting eating disorders', 'C': 'Both A and B', 'D': 'Boring content'}, 'correct': 'C', 'explanation': 'Multiple ethics scandals. The series ended in 2016 after years of criticism.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Cheaters (the show) follows a private investigator who?', 'question': 'Who does what?', 'answers': {'A': 'Catches cheating partners on hidden camera, then confronts them', 'B': 'Helps couples reconcile', 'C': 'Resolves divorce cases', 'D': 'Both A and producing TV gold'}, 'correct': 'D', 'explanation': 'Joey Greco was famously stabbed during a confrontation in 2003 (some say staged). Real or fake confrontations.', 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real chaos.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'A Reality TV "wedding finale" was upset when?', 'question': 'What happened?', 'answers': {'A': 'Bride\'s "boyfriend" turned out to be a hired actor', 'B': 'Groom didn\'t show', 'C': 'Cake fell over', 'D': 'All three across various shows'}, 'correct': 'D', 'explanation': 'Reality TV weddings constantly produce drama. Hired-actor reveals, groom no-shows, all real.', 'commentary_correct': 'Correct! All three.', 'commentary_wrong': 'All three. Reality TV chaos.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The TV show 90 Day Fiancé follows what real-world process?', 'question': 'What process?', 'answers': {'A': 'K-1 visa marriage applications', 'B': 'Naturalization', 'C': 'Adoption', 'D': 'Citizenship tests'}, 'correct': 'A', 'explanation': 'K-1 visa requires marriage within 90 days. Multiple spin-offs and seasons. Real visa drama.', 'commentary_correct': 'Correct! K-1 visa.', 'commentary_wrong': 'K-1 visa.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'A 2010 Bachelorette contestant\'s real-world job was?', 'question': 'Was what?', 'answers': {'A': 'Multiple Bachelor contestants have been "models" or "personal trainers" exclusively', 'B': 'Doctors', 'C': 'Engineers', 'D': 'Teachers'}, 'correct': 'A', 'explanation': 'Bachelor contestants are statistically heavy on "models," "trainers," and "fitness coaches" — somewhat unrealistic distribution.', 'commentary_correct': 'Correct! Models/trainers.', 'commentary_wrong': 'Models/trainers.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'The Mole was a reality show where?', 'question': 'What\'s the twist?', 'answers': {'A': 'One contestant secretly works to sabotage the others', 'B': 'A literal mole appears', 'C': 'Everyone is the mole', 'D': 'The host is the mole'}, 'correct': 'A', 'explanation': 'A contestant is the "mole" working with producers to sabotage challenges. Others try to identify them.', 'commentary_correct': 'Correct! Hidden saboteur.', 'commentary_wrong': 'Hidden saboteur.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Wife Swap (UK/US) routinely paired families to?', 'question': 'To do what?', 'answers': {'A': 'Maximum cultural clash (e.g., vegan + hunter)', 'B': 'Build understanding', 'C': 'Resolve real disputes', 'D': 'Promote harmony'}, 'correct': 'A', 'explanation': 'Producers selected for maximum drama. Vegan paired with hunter family, etc. Fights guaranteed.', 'commentary_correct': 'Correct! Max clash.', 'commentary_wrong': 'Max clash.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Reality TV Atrocities', 'setup': 'Jersey Shore featured the catchphrase "GTL" meaning?', 'question': 'Meaning?', 'answers': {'A': 'Gym, Tan, Laundry', 'B': 'Get the Lottery', 'C': 'Going to Lunch', 'D': 'Grand Theft Largo'}, 'correct': 'A', 'explanation': 'The Situation\'s daily routine. Became cultural shorthand for the Jersey Shore lifestyle.', 'commentary_correct': 'Correct! Gym Tan Laundry.', 'commentary_wrong': 'Gym Tan Laundry.', 'difficulty': 'easy', 'time_limit': 15},
]


def seed_v4_batch1b():
    """Insert v4 batch 1b questions. Idempotent."""
    ph = get_placeholder()
    added = 0
    skipped = 0
    for q in V4_BATCH1B_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            print(f"[v4-b1b] category '{q['category']}' missing; skipping")
            skipped += 1
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (
                cat['id'], q['question'], q.get('setup', '') or '',
                q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                q['correct'], q.get('difficulty', 'medium'), q.get('time_limit', 15),
                q.get('explanation', ''),
                q.get('commentary_correct', ''), q.get('commentary_wrong', ''),
            ))
            added += 1
        except Exception as e:
            print(f"[v4-b1b] insert error: {e}")
    print(f"✅ v4 batch1b added {added} new questions ({skipped} skipped, {len(V4_BATCH1B_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch1b()
