"""v4 unified question pack — YDKJ-style content for the 4 reference
categories (rewritten from scratch) + 37 new themed categories.

Single file by design. Easier to grow, easier to spot-check coverage, and
the seeder is idempotent (INSERT OR IGNORE on the question_text unique
index). Future batches just append to V4_QUESTIONS.

Content rule: every entry has setup, multiple-choice answers with absurd
distractors where appropriate, explanation, host_commentary_correct,
host_commentary_wrong. All entries are factual or grounded in real events.
No tragedy that doesn't pass the bar-night test.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_QUESTIONS = [
    # ========================================================================
    # POP CULTURE SMACKDOWN — 20 YDKJ replacements for the dropped OpenTDB rows
    # ========================================================================
    {'category': 'Pop Culture Smackdown', 'setup': 'In 1985 a movie studio greenlit a sequel only because the original\'s star insisted.', 'question': 'Which sequel?', 'answers': {'A': 'Grease 2', 'B': 'Speed 2', 'C': 'Caddyshack II', 'D': 'Jaws: The Revenge'}, 'correct': 'A', 'explanation': 'Grease 2 was greenlit on the strength of Grease 1. Maxwell Caulfield never recovered.', 'commentary_correct': "Correct! Grease 2. The 'Cool Rider' incident.", 'commentary_wrong': 'Grease 2. Maxwell Caulfield has been working it off for 40 years.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'A 1992 cola was advertised as transparent and was discontinued in 18 months.', 'question': 'Which beverage?', 'answers': {'A': 'Crystal Pepsi', 'B': 'Tab Clear', 'C': 'Clear Coke', 'D': 'Both A and B'}, 'correct': 'D', 'explanation': 'Both Crystal Pepsi and Tab Clear were doomed transparent-cola attempts.', 'commentary_correct': 'Correct! Both. \'90s saw a clear-soda massacre.', 'commentary_wrong': 'Both A and B. Clear sodas tasted like marketing.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'In 1996, Macarena spent 14 weeks at #1.', 'question': 'Who recorded it?', 'answers': {'A': 'Los del Río', 'B': 'Ricky Martin', 'C': 'Enrique Iglesias', 'D': 'Selena Gomez (she wasn\'t born yet)'}, 'correct': 'A', 'explanation': 'Two middle-aged Spanish guys. The world made them rich.', 'commentary_correct': 'Correct! Los del Río. They got the last laugh.', 'commentary_wrong': "Los del Río. Two guys, one dance, 14 weeks at #1.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'A 2008 reality dating show had what unique premise?', 'question': 'What was the gimmick?', 'answers': {'A': 'Contestants stayed in a haunted house', 'B': 'Contestants didn\'t know they were on a show (Joe Schmo)', 'C': 'Contestants were all named Steve', 'D': 'Contestants competed against a horse'}, 'correct': 'B', 'explanation': "The Joe Schmo Show. Only one real contestant. Everyone else was an actor.", 'commentary_correct': "Correct! Joe Schmo. The most meta show possible.", 'commentary_wrong': "Joe Schmo. One real guy, everyone else acting.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'The first viral YouTube video was uploaded in 2005.', 'question': 'What did it show?', 'answers': {'A': 'A guy at the zoo (Me at the zoo)', 'B': 'A cat playing piano', 'C': 'Charlie biting his brother\'s finger', 'D': 'A dancing baby'}, 'correct': 'A', 'explanation': "'Me at the zoo' by co-founder Jawed Karim. 19 seconds. Elephants.", 'commentary_correct': "Correct! Me at the zoo. The original.", 'commentary_wrong': 'Me at the zoo. Jawed Karim. 19 seconds of elephants.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'A 2019 Game of Thrones episode famously featured what production blunder?', 'question': 'What got left in the shot?', 'answers': {'A': 'A Starbucks cup', 'B': 'A water bottle', 'C': 'A boom mic', 'D': 'Both A and B (different episodes)'}, 'correct': 'D', 'explanation': "Starbucks cup in S8E4, water bottle in S8E6. Final season chaos.", 'commentary_correct': "Correct! Both. Final-season HBO.", 'commentary_wrong': "Both. Starbucks and water bottle, two episodes apart.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'In 1997 the album Be Here Now sold 425,000 copies in three days.', 'question': 'Which band?', 'answers': {'A': 'Oasis', 'B': 'Blur', 'C': 'Pulp', 'D': 'Radiohead'}, 'correct': 'A', 'explanation': "Oasis. The peak of Britpop. Then they fought for 20 years.", 'commentary_correct': "Correct! Oasis. Peak Britpop.", 'commentary_wrong': "Oasis. 425K in 3 days. Then the Gallagher brothers happened.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "Friends, the sitcom, originally pitched what unused title?", 'question': "Which working title?", 'answers': {'A': "Insomnia Café", 'B': "Six of One", 'C': "Friends Like Us", 'D': "All of the above"}, 'correct': 'D', 'explanation': "All three were pre-production titles. 'Friends' was the last call.", 'commentary_correct': "Correct! All three. NBC waited until the last week.", 'commentary_wrong': "All three. They almost called it Insomnia Café.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "Britney Spears performed at the 2001 VMAs with what live animal?", 'question': 'Which creature?', 'answers': {'A': 'A python', 'B': 'A tiger', 'C': 'A horse', 'D': 'A parrot'}, 'correct': 'A', 'explanation': "Yellow albino python named Banana. PETA hated it.", 'commentary_correct': "Correct! Banana the python.", 'commentary_wrong': "A python. Albino. Named Banana.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "A Tom Cruise movie was rejected from filming at what Catholic site?", 'question': 'Where?', 'answers': {'A': 'The Vatican', 'B': 'A New York cathedral (for The Mummy)', 'C': 'Westminster Abbey', 'D': "Notre-Dame"}, 'correct': 'A', 'explanation': "Vatican said no to filming Mission Impossible 3 inside.", 'commentary_correct': "Correct! Vatican. They said no to Tom.", 'commentary_wrong': "Vatican. Said no to Tom Cruise filming there.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "Sony's 'Concussion' (2015) was famously edited to do what?", 'question': "What was changed?", 'answers': {'A': "Softened to avoid NFL legal action", 'B': "Re-cast lead actor mid-production", 'C': "Removed all real player names", 'D': "Both A and C"}, 'correct': 'A', 'explanation': "Internal emails revealed edits to avoid NFL lawsuit. Real and well-documented.", 'commentary_correct': "Correct! Softened. NFL had leverage.", 'commentary_wrong': "Softened. NFL pressured Sony.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "A 2012 superhero movie was the first to gross $1B for its studio.", 'question': "Which?", 'answers': {'A': "The Avengers", 'B': "The Dark Knight Rises", 'C': "Iron Man 3", 'D': "Spider-Man"}, 'correct': 'A', 'explanation': "Marvel's The Avengers. The MCU strategy paid off.", 'commentary_correct': "Correct! Avengers. The MCU detonated.", 'commentary_wrong': "Avengers. First $1B for Marvel.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "The world's first feature-length animated film (1937) was about?", 'question': 'About what?', 'answers': {'A': "Snow White and the Seven Dwarfs", 'B': "Pinocchio", 'C': "Fantasia", 'D': "Mickey Mouse"}, 'correct': 'A', 'explanation': "Walt Disney bet the company on Snow White. It paid off massively.", 'commentary_correct': "Correct! Snow White. Bet the company. Won.", 'commentary_wrong': "Snow White. 1937. Walt bet everything.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "MTV's first music video in 1981 was what song?", 'question': 'Which song?', 'answers': {'A': "'Video Killed the Radio Star' — The Buggles", 'B': "'Money for Nothing' — Dire Straits", 'C': "'Take On Me' — a-ha", 'D': "'Thriller' — Michael Jackson"}, 'correct': 'A', 'explanation': 'Buggles. Famously ironic. MTV picked it on purpose.', 'commentary_correct': "Correct! Video Killed the Radio Star. On purpose.", 'commentary_wrong': "Video Killed the Radio Star. MTV's first.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'In 1989 the movie The Wizard was a 90-minute commercial for what?', 'question': "For what product?", 'answers': {'A': "Power Glove (Nintendo)", 'B': "Atari Lynx", 'C': "Sega Game Gear", 'D': "Coleco Adam"}, 'correct': 'A', 'explanation': 'The Wizard was a feature-length Power Glove ad with Fred Savage attached.', 'commentary_correct': 'Correct! Power Glove. Now you know what the 80s were.', 'commentary_wrong': 'Power Glove. 90-minute ad. Fred Savage.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'A 1997 album was recorded by a band wearing nothing but tube socks.', 'question': "Which band?", 'answers': {'A': "Red Hot Chili Peppers", 'B': "Smash Mouth", 'C': "Korn", 'D': "Limp Bizkit"}, 'correct': 'A', 'explanation': "Chili Peppers, repeat offenders. Sock-only photo shoots a tradition.", 'commentary_correct': "Correct! Chili Peppers. Sock tradition.", 'commentary_wrong': "Chili Peppers. Tube socks. A choice.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "A 2010 Twilight movie made how much during opening weekend?", 'question': 'Approximate gross?', 'answers': {'A': "$50M", 'B': "$140M", 'C': "$280M", 'D': "$10M"}, 'correct': 'B', 'explanation': "Eclipse opened to ~$157M domestic. Werewolf girls were a market.", 'commentary_correct': "Correct! ~$140M. Werewolves > vampires.", 'commentary_wrong': "~$140M. Twilight money was real.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "The most-watched TV finale in US history (1983) was for?", 'question': "Which show?", 'answers': {'A': "M*A*S*H", 'B': "Cheers", 'C': "Seinfeld", 'D': "Friends"}, 'correct': 'A', 'explanation': "M*A*S*H finale. 105M viewers. Half the US.", 'commentary_correct': "Correct! M*A*S*H. Half the country watched.", 'commentary_wrong': "M*A*S*H. 105M viewers. Other shows wish.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': 'A 2017 horror film hit $250M on a $4.5M budget.', 'question': 'Which film?', 'answers': {'A': 'Get Out', 'B': 'It', 'C': 'A Quiet Place', 'D': "The Conjuring 2"}, 'correct': 'A', 'explanation': "Get Out. Jordan Peele's debut. Best return-on-investment of the decade.", 'commentary_correct': "Correct! Get Out. ROI king.", 'commentary_wrong': "Get Out. Best ROI of the decade.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pop Culture Smackdown', 'setup': "A 1995 movie's prop budget included one item that cost more than the entire crew's salary.", 'question': "Which prop?", 'answers': {'A': 'A real Renaissance painting (for Heat)', 'B': "Tom Cruise's haircut maintenance (Mission Impossible)", 'C': "The chocolate river (Charlie)", 'D': "Trick question — never happened"}, 'correct': 'C', 'explanation': "Willy Wonka's chocolate river (1971 actually): 150,000 gallons of fake chocolate.", 'commentary_correct': "Correct! Chocolate river. Spoiled in days.", 'commentary_wrong': "Chocolate river. Wonka. Spoiled fast.", 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # GENERAL KNOWLEDGE — 20 YDKJ replacements
    # ========================================================================
    {'category': 'General Knowledge', 'setup': "The Eiffel Tower was supposed to be torn down after how many years?", 'question': 'How long?', 'answers': {'A': '20 years', 'B': '50 years', 'C': '100 years', 'D': 'Never — always permanent'}, 'correct': 'A', 'explanation': "Built for the 1889 World's Fair, scheduled to be demolished in 1909. Saved by radio antennae.", 'commentary_correct': "Correct! 20 years. Saved by radio.", 'commentary_wrong': "20 years. Then the army wanted it for radio.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Honey has been found in tombs and is still edible.", 'question': 'How old can edible tomb honey be?', 'answers': {'A': '100 years', 'B': '1,000 years', 'C': '3,000+ years', 'D': 'Honey rots like everything else'}, 'correct': 'C', 'explanation': "Egyptian tombs. Honey from 3000 BC found edible. It's a sealed acidic environment.", 'commentary_correct': "Correct! 3000+ years. Honey is immortal.", 'commentary_wrong': "3000+ years. Honey lasts forever in sealed jars.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The shortest war in history was between Britain and Zanzibar in 1896.", 'question': 'How long did it last?', 'answers': {'A': '38 minutes', 'B': '2 hours', 'C': '1 day', 'D': '1 week'}, 'correct': 'A', 'explanation': "Anglo-Zanzibar War. Britain bombarded the palace. Sultan surrendered in 38 minutes.", 'commentary_correct': "Correct! 38 minutes. Shortest war ever.", 'commentary_wrong': "38 minutes. Hardly a war. More of a lunch break.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "A US state once banned the sale of margarine that was colored to look like butter.", 'question': 'Which state?', 'answers': {'A': 'Wisconsin', 'B': 'New York', 'C': 'Texas', 'D': 'California'}, 'correct': 'A', 'explanation': "Wisconsin. Dairy state. Yellow margarine was illegal until 1967.", 'commentary_correct': "Correct! Wisconsin. Big Butter.", 'commentary_wrong': "Wisconsin. Big Butter ran politics.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The world's largest desert is technically...", 'question': "Which desert?", 'answers': {'A': 'The Sahara', 'B': 'Antarctica', 'C': 'The Gobi', 'D': 'The Arctic tundra'}, 'correct': 'B', 'explanation': "Antarctica is the largest desert (deserts are defined by low precipitation, not heat).", 'commentary_correct': "Correct! Antarctica. Desert = low precipitation.", 'commentary_wrong': "Antarctica. It's a desert. Surprise.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Cleopatra lived closer in time to the iPhone than to which?", 'question': "Which?", 'answers': {'A': "The building of the Great Pyramid", 'B': "Julius Caesar", 'C': "The Roman Empire", 'D': "Mark Antony"}, 'correct': 'A', 'explanation': "Cleopatra lived ~30 BC. The Pyramid was built ~2500 BC. iPhone in 2007. Pyramid is older by 500 years.", 'commentary_correct': "Correct! The Pyramid. Older than Cleo.", 'commentary_wrong': "The Pyramid. Cleo lived closer to iPhones than pyramids.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The Wright Brothers' first flight in 1903 lasted approximately?", 'question': 'How long?', 'answers': {'A': '12 seconds', 'B': '2 minutes', 'C': '10 minutes', 'D': '1 hour'}, 'correct': 'A', 'explanation': "12 seconds. 120 feet. December 17, 1903, Kitty Hawk.", 'commentary_correct': "Correct! 12 seconds. 120 feet.", 'commentary_wrong': "12 seconds. The whole flight.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "A common dolphin species can do what unique behavior?", 'question': "What do dolphins do?", 'answers': {'A': "Recognize themselves in mirrors", 'B': "Use names (signature whistles)", 'C': "Pass tools through generations", 'D': "All of the above"}, 'correct': 'D', 'explanation': "Dolphins are extraordinary. All three behaviors documented in research.", 'commentary_correct': "Correct! All three. Dolphins are smart.", 'commentary_wrong': "All three. Dolphins are genuinely smart.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "How many feet of intestines does an average human have?", 'question': "Approximately?", 'answers': {'A': '5 feet', 'B': '15 feet', 'C': '25 feet', 'D': '50 feet'}, 'correct': 'C', 'explanation': "About 25 feet of intestines. Small (~20 ft) + large (~5 ft). Long way for snacks.", 'commentary_correct': "Correct! ~25 feet. Coiled inside you right now.", 'commentary_wrong': "25 feet. You contain a small parade.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "A bunch of bananas growing together is called a what?", 'question': "What is it?", 'answers': {'A': 'A hand', 'B': 'A fist', 'C': 'A boat', 'D': 'A flock'}, 'correct': 'A', 'explanation': "A 'hand' of bananas. Individual bananas are 'fingers.' True.", 'commentary_correct': "Correct! A hand. Fingers are individual bananas.", 'commentary_wrong': "A hand. And the bananas are fingers.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The Coca-Cola formula change of 1985 lasted how long before reverting?", 'question': "How long?", 'answers': {'A': '79 days', 'B': '6 months', 'C': '2 years', 'D': '5 years'}, 'correct': 'A', 'explanation': "New Coke launched April 23, 1985. Original Coke returned July 11, 1985. 79 days.", 'commentary_correct': "Correct! 79 days. The biggest marketing flop in food history.", 'commentary_wrong': "79 days. Famous flop.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "A passenger pigeon could fly how fast?", 'question': "Top speed?", 'answers': {'A': '15 mph', 'B': '30 mph', 'C': '60 mph', 'D': '100 mph'}, 'correct': 'C', 'explanation': "60-65 mph. Flocks of millions. Hunted to extinction by 1914.", 'commentary_correct': "Correct! 60 mph. Hunted to oblivion.", 'commentary_wrong': "60 mph. Sadly extinct since 1914.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Norway's flag contains the flags of how many other countries?", 'question': "How many?", 'answers': {'A': "5", 'B': "6", 'C': "7", 'D': "8"}, 'correct': 'B', 'explanation': "Norway's flag contains: Finland, France, Indonesia, Netherlands, Poland, Thailand (rotated/cropped).", 'commentary_correct': "Correct! 6 flags hidden in Norway's flag.", 'commentary_wrong': "6 flags. Norway is a flag-within-flag.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Iceland has no army. What it has instead is what?", 'question': "What's their defense?", 'answers': {'A': "A coast guard", 'B': "A volunteer militia", 'C': "Treaty with NATO", 'D': "Both A and C"}, 'correct': 'D', 'explanation': "Iceland: coast guard + NATO membership. No standing army since WWII.", 'commentary_correct': "Correct! Coast guard + NATO. No army.", 'commentary_wrong': "Coast guard + NATO. No army for decades.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Octopuses have how many hearts?", 'question': "How many?", 'answers': {'A': '1', 'B': '2', 'C': '3', 'D': '5'}, 'correct': 'C', 'explanation': "Three hearts. Two pump to gills, one to body. They also have blue blood.", 'commentary_correct': "Correct! 3. Plus blue blood.", 'commentary_wrong': "3 hearts. And blue blood. Aliens.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The longest place name on Earth is in?", 'question': "Where?", 'answers': {'A': 'New Zealand', 'B': 'Wales', 'C': 'Thailand', 'D': 'All three claim the title in different categories'}, 'correct': 'D', 'explanation': "Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu (NZ), Llanfair... (Wales), Bangkok's full ceremonial name (Thailand) all compete.", 'commentary_correct': "Correct! All three. Different categories.", 'commentary_wrong': "All three. Different categories.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "Scotland's national animal is the?", 'question': "Which animal?", 'answers': {'A': 'Unicorn', 'B': 'Lion', 'C': 'Eagle', 'D': 'Highland cow'}, 'correct': 'A', 'explanation': "Unicorn. Official since the 1300s. England has the lion; Scotland chose differently.", 'commentary_correct': "Correct! Unicorn. Real official symbol.", 'commentary_wrong': "The unicorn. Officially.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "A bolt of lightning is hotter than the surface of the sun by approximately?", 'question': "How much hotter?", 'answers': {'A': "Same temp", 'B': "2x hotter", 'C': "5x hotter", 'D': "10x hotter (sun ~5,500°C, lightning ~30,000°C)"}, 'correct': 'D', 'explanation': "Sun's surface ~5,500°C. Lightning ~30,000°C briefly. ~5x hotter.", 'commentary_correct': "Correct! 5x. Lightning is intense.", 'commentary_wrong': "~5x hotter. Lightning is the briefest plasma.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "How many bones do you have at birth vs as an adult?", 'question': "Approximate?", 'answers': {'A': "Same (~206)", 'B': "Born with ~300, fuse to ~206", 'C': "Born with ~100, grow to ~206", 'D': "Born with ~206, lose to ~150"}, 'correct': 'B', 'explanation': "Babies: ~300 bones. They fuse during development to ~206 adult bones.", 'commentary_correct': "Correct! 300 fusing to 206.", 'commentary_wrong': "300 → 206. They fuse.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'General Knowledge', 'setup': "The world's largest active volcano is?", 'question': "Which one?", 'answers': {'A': 'Mauna Loa, Hawaii', 'B': 'Mount Etna, Italy', 'C': 'Yellowstone caldera', 'D': 'Krakatoa'}, 'correct': 'A', 'explanation': "Mauna Loa by volume — 18,000 cubic miles of rock. Yellowstone supervolcano is technically bigger but considered dormant active.", 'commentary_correct': "Correct! Mauna Loa.", 'commentary_wrong': "Mauna Loa. By volume.", 'difficulty': 'medium', 'time_limit': 15},

    # ========================================================================
    # MATH & SCIENCE FACTS — 20 YDKJ replacements
    # ========================================================================
    {'category': 'Math & Science Facts', 'setup': "A solar mass takes how long to be expelled by the sun as light?", 'question': "How much sun mass per second is lost?", 'answers': {'A': "1 ton", 'B': "1,000 tons", 'C': "4 million tons", 'D': "1 atom"}, 'correct': 'C', 'explanation': "Sun loses ~4 million tons of mass per SECOND as light (E=mc^2). Still has 5 billion years left.", 'commentary_correct': "Correct! 4 million tons per second. Mass→light.", 'commentary_wrong': "4 million tons/sec. The sun loses a lot.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The chance of rolling 5 sixes in a row with one die is approximately?", 'question': "Odds?", 'answers': {'A': "1 in 100", 'B': "1 in 1,000", 'C': "1 in 7,776", 'D': "1 in 1,000,000"}, 'correct': 'C', 'explanation': "6^5 = 7,776. About 1 in 7,800. Roll long enough; you'll hit it.", 'commentary_correct': "Correct! 1 in 7,776.", 'commentary_wrong': "1 in 7,776. Math.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "If you put a typical apple in space, it would?", 'question': "What happens?", 'answers': {'A': "Freeze instantly", 'B': "Boil away in seconds", 'C': "Stay intact for years", 'D': "Sublimate slowly"}, 'correct': 'D', 'explanation': "No air = no boiling pressure threshold. Water sublimates directly from solid/liquid to vapor. Apple dries up.", 'commentary_correct': "Correct! Sublimates. Slow vacuum-drying.", 'commentary_wrong': "Sublimates. The apple dries up.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "How many atoms in a typical human body?", 'question': "Atom count?", 'answers': {'A': "~10^20", 'B': "~10^27", 'C': "~10^15", 'D': "~10^50"}, 'correct': 'B', 'explanation': "About 7 octillion atoms. ~7 × 10^27.", 'commentary_correct': "Correct! ~10^27. Octillions of you.", 'commentary_wrong': "~10^27. Big number.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The smallest organism that can replicate is?", 'question': "What is it?", 'answers': {'A': "Viruses (questionably alive)", 'B': "Bacteria", 'C': "Mycoplasma", 'D': "Viroids"}, 'correct': 'D', 'explanation': "Viroids: short single-stranded RNA. Smaller than viruses. They replicate. Just barely 'alive.'", 'commentary_correct': "Correct! Viroids. Smaller than viruses.", 'commentary_wrong': "Viroids. Tiny.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "If you started at Earth's equator and walked due east, you'd cross?", 'question': "How many time zones?", 'answers': {'A': "12", 'B': "24", 'C': "0 (you'd hit a wall)", 'D': "26 (some zones offset by 30 min)"}, 'correct': 'D', 'explanation': "24 hour zones + 2 extra (Newfoundland, Nepal, India offsets). 26 total.", 'commentary_correct': "Correct! 26. Some 30-min offsets.", 'commentary_wrong': "26. Newfoundland is weird.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The decimal expansion of pi has been calculated to how many digits?", 'question': "Approximate latest?", 'answers': {'A': "1 million", 'B': "100 billion", 'C': "100 trillion", 'D': "Trick — pi is rational"}, 'correct': 'C', 'explanation': "As of 2022, pi calculated to 100 trillion digits. Pi is irrational and transcendental.", 'commentary_correct': "Correct! 100 trillion.", 'commentary_wrong': "100 trillion. As of 2022.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The Milky Way galaxy contains how many stars?", 'question': "Approximate?", 'answers': {'A': "1 billion", 'B': "100 billion to 400 billion", 'C': "1 trillion", 'D': "1 quadrillion"}, 'correct': 'B', 'explanation': "Estimates range 100-400 billion. Hard to count for obvious reasons.", 'commentary_correct': "Correct! 100-400 billion.", 'commentary_wrong': "100-400 billion. Big range, big galaxy.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The tardigrade (water bear) can survive what?", 'question': "What can it survive?", 'answers': {'A': "Vacuum of space", 'B': "Boiling temperatures", 'C': "Radiation 1,000x human-lethal dose", 'D': "All of the above"}, 'correct': 'D', 'explanation': "Tardigrades. The toughest animals known. Survive space, heat, radiation, dehydration for decades.", 'commentary_correct': "Correct! All. They're indestructible.", 'commentary_wrong': "All. Tardigrades are tough.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Antimatter is so reactive that meeting matter causes?", 'question': "What happens?", 'answers': {'A': "Mass-to-energy conversion (E=mc²)", 'B': "Color change", 'C': "Sound", 'D': "Nothing visible"}, 'correct': 'A', 'explanation': "Particle-antiparticle annihilation. Releases energy = mass × c². 1g of antimatter could power NYC for hours.", 'commentary_correct': "Correct! Annihilation = energy. E=mc².", 'commentary_wrong': "Annihilation. Big energy.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "A 'mole' in chemistry equals how many particles?", 'question': "Avogadro's number is?", 'answers': {'A': "~6 × 10^23", 'B': "~10^10", 'C': "~10^50", 'D': "1 million"}, 'correct': 'A', 'explanation': "Avogadro's number: 6.022 × 10^23. Particles per mole. Why chemistry exists as a science.", 'commentary_correct': "Correct! 6 × 10^23. Avogadro.", 'commentary_wrong': "6×10^23. Avogadro number.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Light from the Sun takes how long to reach Earth?", 'question': "How long?", 'answers': {'A': "Instantly", 'B': "About 8 minutes", 'C': "About 1 hour", 'D': "About 1 day"}, 'correct': 'B', 'explanation': "~8 minutes 20 seconds. Light from the sun you see now LEFT the sun 8 min ago.", 'commentary_correct': "Correct! ~8 minutes. You're seeing the past.", 'commentary_wrong': "8 minutes. Past-sun.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The deepest part of the ocean (Challenger Deep) is approximately?", 'question': "How deep?", 'answers': {'A': "1 km", 'B': "11 km", 'C': "50 km", 'D': "100 km"}, 'correct': 'B', 'explanation': "~10.9 km. Mariana Trench. Mt. Everest is ~8.8 km tall. Everest could fit upside-down.", 'commentary_correct': "Correct! ~11 km. Everest would drown.", 'commentary_wrong': "~11 km. Everest fits.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "The Coriolis effect determines water-rotation in toilets?", 'question': "True?", 'answers': {'A': "Yes — north/south hemispheres", 'B': "No — it's plumbing geometry", 'C': "Only at the equator", 'D': "Only in Australia"}, 'correct': 'B', 'explanation': "Coriolis is too weak at toilet scale. Direction depends on the bowl's design, not hemisphere. Myth busted.", 'commentary_correct': "Correct! Plumbing, not Coriolis.", 'commentary_wrong': "Plumbing. The myth lives on, but no.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Diamond is the hardest natural substance. What's the hardest synthetic?", 'question': "Which?", 'answers': {'A': "Diamond (still the same)", 'B': "Boron nitride (wurtzite, ~58% harder than diamond)", 'C': "Steel", 'D': "Tungsten"}, 'correct': 'B', 'explanation': "Wurtzite boron nitride: theoretically 58% harder than diamond. Real samples are limited.", 'commentary_correct': "Correct! Wurtzite BN. Harder than diamond.", 'commentary_wrong': "Wurtzite boron nitride.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Heat causes metals to do what?", 'question': "What happens?", 'answers': {'A': "Shrink", 'B': "Expand", 'C': "Change color permanently", 'D': "Nothing"}, 'correct': 'B', 'explanation': "Thermal expansion. Why railroad tracks have gaps. Why bridges have expansion joints.", 'commentary_correct': "Correct! Expand. Hence rail gaps.", 'commentary_wrong': "Expand. Bridges need it.", 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "A 'googol' is what number?", 'question': "How big?", 'answers': {'A': "10^100", 'B': "10^10", 'C': "10^20", 'D': "10^1000"}, 'correct': 'A', 'explanation': "10^100. Bigger than estimated atoms in observable universe (~10^80). Google named after it.", 'commentary_correct': "Correct! 10^100.", 'commentary_wrong': "10^100. Google's namesake.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "DNA in one human cell, if stretched out, is approximately?", 'question': "How long?", 'answers': {'A': "2 meters", 'B': "1 cm", 'C': "100 km", 'D': "Microscopic, can't measure"}, 'correct': 'A', 'explanation': "~2 meters. Coiled into a nucleus 6 micrometers across. Tight packing.", 'commentary_correct': "Correct! 2 meters per cell.", 'commentary_wrong': "2 meters. Coiled tightly.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Black holes leak energy via Hawking radiation. They eventually?", 'question': "What happens?", 'answers': {'A': "Evaporate completely", 'B': "Get bigger forever", 'C': "Implode", 'D': "Convert to white holes"}, 'correct': 'A', 'explanation': "Hawking radiation slowly drains mass. Tiny black holes evaporate fast. Stellar black holes take longer than the universe's current age.", 'commentary_correct': "Correct! Evaporate eventually.", 'commentary_wrong': "Evaporate. Hawking radiation.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Math & Science Facts', 'setup': "Bananas are slightly radioactive. The 'banana equivalent dose' measures?", 'question': "What does it measure?", 'answers': {'A': "Radiation in everyday context", 'B': "Banana ripeness", 'C': "Potassium content", 'D': "Calories per banana"}, 'correct': 'A', 'explanation': "BED: Banana Equivalent Dose. Used to put radiation exposure in perspective. One banana = ~0.1 microsieverts.", 'commentary_correct': "Correct! Radiation. Bananas are slightly radioactive (K-40).", 'commentary_wrong': "Radiation. Bananas are mildly radioactive.", 'difficulty': 'hard', 'time_limit': 15},

    # ========================================================================
    # HISTORICAL DUMBASSERY — 20 YDKJ replacements
    # ========================================================================
    {'category': 'Historical Dumbassery', 'setup': "In 1929 the Soviet Union outlawed Sundays.", 'question': "What replaced the week?", 'answers': {'A': "A 5-day week with rotating off-days", 'B': "A 10-day week", 'C': "Working every day", 'D': "Sundays at random"}, 'correct': 'A', 'explanation': "Nepreryvka: 5-day week. Workers had rotating off-days to keep factories running 24/7. Reverted by 1940.", 'commentary_correct': "Correct! 5-day weeks. Stalin tried.", 'commentary_wrong': "5-day weeks. Rotating off-days.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "In the 1500s, Pope Gregory XIII decided 10 days didn't exist.", 'question': "What happened?", 'answers': {'A': "The Gregorian calendar reform skipped Oct 5-14, 1582", 'B': "He invented daylight savings", 'C': "He cancelled Christmas", 'D': "Nothing happened"}, 'correct': 'A', 'explanation': "Calendar reform. To fix Julian calendar drift, the Pope deleted 10 days. People went to bed Oct 4, woke up Oct 15.", 'commentary_correct': "Correct! Deleted 10 days.", 'commentary_wrong': "Deleted 10 days. Calendar correction.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "In 1547, Henry VIII died from what indirect cause?", 'question': "How did he go?", 'answers': {'A': "Obesity-related complications", 'B': "Beheading", 'C': "Plague", 'D': "Fell off a horse"}, 'correct': 'A', 'explanation': "Morbidly obese, leg ulcer, diabetes. Couldn't get out of bed in the end.", 'commentary_correct': "Correct! Obesity. Couldn't escape his own bed.", 'commentary_wrong': "Obesity. Big king, bigger problems.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "The Dutch Tulip Mania (1637) peaked when one rare tulip bulb cost?", 'question': "Equivalent of?", 'answers': {'A': "A modest sword", 'B': "A loaf of bread", 'C': "A canal house in Amsterdam", 'D': "A small village"}, 'correct': 'C', 'explanation': "Real economic bubble. Rare bulbs sold for the price of an Amsterdam canal house. Then collapsed.", 'commentary_correct': "Correct! A canal house. The OG bubble.", 'commentary_wrong': "Canal house. Bubble economics 101.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "King Charles VI of France (1380-1422) believed he was?", 'question': "Believed himself to be what?", 'answers': {'A': "Made of glass", 'B': "A wolf", 'C': "A fish", 'D': "Both A and B"}, 'correct': 'A', 'explanation': "'Glass delusion.' Common medieval mental disorder. Charles believed he was made of glass and would shatter.", 'commentary_correct': "Correct! Made of glass.", 'commentary_wrong': "Made of glass. Real condition.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "The Great Emu War (1932) was fought by the Australian government against?", 'question': "Against whom?", 'answers': {'A': "Emus", 'B': "Kangaroos", 'C': "Other Australians", 'D': "British colonists"}, 'correct': 'A', 'explanation': "Real war. Australian military deployed against emus in WWI veteran farmland. Emus won.", 'commentary_correct': "Correct! Emus. They won.", 'commentary_wrong': "Emus. Australia lost to flightless birds.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Caligula (Roman emperor, AD 37-41) once declared war on?", 'question': "Against whom?", 'answers': {'A': "The Mediterranean Sea (made soldiers stab it)", 'B': "Mars (the god of war)", 'C': "His own horse", 'D': "Both A and B"}, 'correct': 'A', 'explanation': "Caligula ordered legionaries to stab the sea and collect seashells as 'spoils of war.' Also tried to make his horse a senator.", 'commentary_correct': "Correct! The sea. With swords.", 'commentary_wrong': "The sea. Sword vs water.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "In 1844 the entire US Cabinet was killed in one accident.", 'question': "What happened?", 'answers': {'A': "Cannon explosion on USS Princeton", 'B': "Building fire", 'C': "Ship sank", 'D': "Yellow fever outbreak"}, 'correct': 'A', 'explanation': "USS Princeton's 'Peacemaker' cannon exploded during a demo. Killed Sec of State, Sec of Navy, several others.", 'commentary_correct': "Correct! Cannon explosion.", 'commentary_wrong': "Cannon. USS Princeton 1844.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Catherine the Great died in 1796 from?", 'question': "How did she go?", 'answers': {'A': "Stroke on the toilet", 'B': "Heart attack at a ball", 'C': "Poisoning by her son", 'D': "Sword wound in battle"}, 'correct': 'A', 'explanation': "Stroke. On the chamber pot. The 'died on a horse' rumor is a much-later fabrication by detractors.", 'commentary_correct': "Correct! Toilet stroke.", 'commentary_wrong': "Stroke on the toilet. The horse story is fake.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "The 1932 dust storms in the US Plains were caused by?", 'question': "What caused them?", 'answers': {'A': "Drought + over-plowing destroyed prairie grass", 'B': "Volcanic eruption", 'C': "Nuclear testing", 'D': "Mass deforestation"}, 'correct': 'A', 'explanation': "The Dust Bowl. Government promoted plowing prairie for wheat. Drought hit. Topsoil blew east to NYC.", 'commentary_correct': "Correct! Drought + plowing.", 'commentary_wrong': "Drought + plowing. Dust Bowl.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Nikola Tesla died with how much money?", 'question': "How much?", 'answers': {'A': "Millions", 'B': "Bankrupt, owing hotel debts", 'C': "Just under $1M", 'D': "Negative — debt only"}, 'correct': 'B', 'explanation': "Tesla died nearly bankrupt in a New York hotel. The Hotel New Yorker covered his costs.", 'commentary_correct': "Correct! Broke. Hotel covered his bills.", 'commentary_wrong': "Broke. Hotel paid for him.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "In 1858 the 'Great Stink' caused Parliament to relocate.", 'question': "What was the stink?", 'answers': {'A': "Thames River, full of sewage", 'B': "A nearby tannery", 'C': "Burning whale oil", 'D': "Garbage dump"}, 'correct': 'A', 'explanation': "Thames was raw sewage. Summer heat made London Parliament chambers unusable. Sewerage system built after.", 'commentary_correct': "Correct! The Thames.", 'commentary_wrong': "The Thames. Sewage. Awful summer.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "The Soviet Union once tried to grow corn in?", 'question': "Where?", 'answers': {'A': "Siberia", 'B': "The Arctic", 'C': "Above the tree line", 'D': "All — Khrushchev's corn campaign"}, 'correct': 'D', 'explanation': "Khrushchev's 'Corn Campaign' planted corn everywhere, including places it couldn't grow. Massive crop failures.", 'commentary_correct': "Correct! All. Corn everywhere.", 'commentary_wrong': "All. Khrushchev loved corn.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "The Maginot Line, France's 1930s defense, was bypassed because?", 'question': "Why didn't it work?", 'answers': {'A': "Germany attacked through Belgium instead", 'B': "It was made of wood", 'C': "Germans flew over it", 'D': "France gave up before fighting"}, 'correct': 'A', 'explanation': "Maginot Line covered France's German border. Germany invaded through Belgium (around the line) in 1940.", 'commentary_correct': "Correct! Through Belgium.", 'commentary_wrong': "Through Belgium. Line bypassed.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Roman emperor Diocletian (244-311 AD) retired to?", 'question': "Where?", 'answers': {'A': "A cabbage farm", 'B': "A palace in Split", 'C': "Both — he grew cabbages at his retirement palace", 'D': "Anywhere but Rome"}, 'correct': 'C', 'explanation': "Diocletian famously retired to grow cabbages at his palace in Split, Croatia. When asked to return to politics, he refused.", 'commentary_correct': "Correct! Cabbage palace.", 'commentary_wrong': "Both. Cabbage. Palace.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Lord Byron's daughter (Ada Lovelace) is credited as the first what?", 'question': "First what?", 'answers': {'A': "Computer programmer", 'B': "Female novelist", 'C': "Suffragette", 'D': "Female mathematician"}, 'correct': 'A', 'explanation': "Ada wrote algorithms for Babbage's Analytical Engine in 1843. Considered the first computer programmer.", 'commentary_correct': "Correct! First programmer.", 'commentary_wrong': "First programmer. Byron's daughter.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "President Calvin Coolidge had what unusual pet at the White House?", 'question': "Which animal?", 'answers': {'A': "A pet raccoon", 'B': "A bobcat", 'C': "A hippopotamus", 'D': "Both A and B (Coolidge had many)"}, 'correct': 'D', 'explanation': "Coolidge had a raccoon (Rebecca), a wallaby, a bobcat, and many others. He was a wild-animal president.", 'commentary_correct': "Correct! Both. He had many.", 'commentary_wrong': "Both. Coolidge collected.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Theodore Roosevelt's solution to a Brazilian tribe being too friendly was?", 'question': "What did Teddy do?", 'answers': {'A': "Wrote a book about them", 'B': "Hunted with them on his 1913-14 expedition", 'C': "Brought them to the US", 'D': "Made them honorary Rough Riders"}, 'correct': 'B', 'explanation': "Teddy's 1913-14 'River of Doubt' expedition. Survived only because friendly indigenous people helped him.", 'commentary_correct': "Correct! Hunted with them.", 'commentary_wrong': "Hunted with them. River of Doubt.", 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "In 1518, hundreds of Strasbourg residents danced for days. Many?", 'question': "What happened to them?", 'answers': {'A': "Died of exhaustion or heart attacks", 'B': "Got tired and went home", 'C': "Levitated", 'D': "Became famous performers"}, 'correct': 'A', 'explanation': "Mass psychogenic illness. ~400 people danced uncontrollably. Some died. Cause still debated (ergot? mass hysteria?).", 'commentary_correct': "Correct! Some died dancing.", 'commentary_wrong': "Died dancing. Real epidemic.", 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Historical Dumbassery', 'setup': "Christopher Columbus thought he had landed in?", 'question': "Where did he think he was?", 'answers': {'A': "India / East Asia", 'B': "Africa", 'C': "Australia", 'D': "A new continent (correctly)"}, 'correct': 'A', 'explanation': "Until his death, Columbus insisted he'd reached Asia. Native peoples got named 'Indians' because of his confusion.", 'commentary_correct': "Correct! India. He died wrong.", 'commentary_wrong': "India. Hence 'Indians.'", 'difficulty': 'easy', 'time_limit': 15},
]


def seed_v4_pack():
    """Insert v4 question pack. Idempotent via INSERT OR IGNORE."""
    ph = get_placeholder()
    added = 0
    skipped = 0
    for q in V4_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            print(f"[v4] category '{q['category']}' missing; skipping")
            skipped += 1
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (
                cat['id'], q['question'], q.get('setup', '') or '',
                q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                q['correct'], q.get('difficulty', 'medium'), q.get('time_limit', 15),
                q.get('explanation', ''),
                q.get('commentary_correct', ''), q.get('commentary_wrong', ''),
            ))
            added += 1
        except Exception as e:
            print(f"[v4] insert error: {e}")
    print(f"✅ v4 pack added {added} new questions ({skipped} skipped, {len(V4_QUESTIONS)} total in pack)")


if __name__ == '__main__':
    seed_v4_pack()
