"""v4 batch 2c — 5 more batch-2 categories. 100 questions.
Streaming Service Disasters, Bad Hair Decisions in History, Wedding Day
Catastrophes, Sports Mascot Brawls, Pranks That Went Too Far.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH2C_QUESTIONS = [
    # STREAMING SERVICE DISASTERS
    {'category': 'Streaming Service Disasters', 'setup': "Quibi launched in April 2020 and shut down in?", 'question': "When?", 'answers': {'A': "December 2020 — 6 months", 'B': "2022", 'C': "Still operating", 'D': "2024"}, 'correct': 'A', 'explanation': "Jeffrey Katzenberg's $1.75B short-form mobile streaming service. Killed in 6 months. Bad timing (pandemic killed commute viewing).", 'commentary_correct': 'Correct! 6 months.', 'commentary_wrong': '6 months.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Google Stadia game streaming launched in 2019 and shut down in?", 'question': "Shut down?", 'answers': {'A': "January 2023", 'B': "2020", 'C': "Still active", 'D': "2025"}, 'correct': 'A', 'explanation': "Stadia killed January 2023. Google refunded all purchases. Major embarrassment.", 'commentary_correct': 'Correct! Jan 2023.', 'commentary_wrong': 'Jan 2023.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "HBO Max rebranded to just 'Max' in?", 'question': "When?", 'answers': {'A': "May 2023", 'B': "2020", 'C': "2024", 'D': "Never"}, 'correct': 'A', 'explanation': "Warner Bros. Discovery rebranded May 2023. Removed 'HBO' from name. Confused subscribers.", 'commentary_correct': 'Correct! May 2023.', 'commentary_wrong': 'May 2023.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Netflix lost about how many subscribers in Q1 2022 (first quarterly drop in 10+ years)?", 'question': "Approximate?", 'answers': {'A': "~200,000", 'B': "1 million", 'C': "5 million", 'D': "10 million"}, 'correct': 'A', 'explanation': "First subscriber loss in a decade. Stock dropped 35% in one day. Triggered password-sharing crackdown.", 'commentary_correct': 'Correct! ~200K.', 'commentary_wrong': '~200K.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Apple TV+ launched in 2019 with how many original shows?", 'question': "How many?", 'answers': {'A': "9 originals + a Friends documentary", 'B': "100+", 'C': "5", 'D': "30"}, 'correct': 'A', 'explanation': "Started with very little content. Has slowly built up. Major spending on Coda, Ted Lasso, etc.", 'commentary_correct': 'Correct! 9.', 'commentary_wrong': '9 to start.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Peacock's launch ad slot during NBC Olympics was complicated by?", 'question': "Complicated by?", 'answers': {'A': "COVID delaying the 2020 Olympics", 'B': "A power outage", 'C': "Both", 'D': "Bad press"}, 'correct': 'A', 'explanation': "Peacock launched July 2020. Olympics delayed to 2021. Lost the launch tie-in.", 'commentary_correct': 'Correct! COVID delay.', 'commentary_wrong': 'COVID timing.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Disney+ Star Wars: The Acolyte (2024) was canceled after?", 'question': "After how many seasons?", 'answers': {'A': "One season — poorly received", 'B': "Three seasons", 'C': "Still active", 'D': "Two"}, 'correct': 'A', 'explanation': "Acolyte was canceled after season 1. Mixed reception, expensive production.", 'commentary_correct': 'Correct! One season.', 'commentary_wrong': 'One season.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "CNN+ launched in March 2022 and was killed in?", 'question': "When?", 'answers': {'A': "April 2022 — one month later", 'B': "2023", 'C': "2024", 'D': "Still alive"}, 'correct': 'A', 'explanation': "CNN+ closed after one month. WB-Discovery merger killed it. Reportedly cost $300M.", 'commentary_correct': 'Correct! 1 month.', 'commentary_wrong': '1 month.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Disney+'s Don't Let Me Down (CGI Mufasa) was?", 'question': "Was what?", 'answers': {'A': "Mufasa: The Lion King (2024), prequel to live-action remake", 'B': "A horror reboot", 'C': "Animated", 'D': "Both A and was a sequel"}, 'correct': 'A', 'explanation': "Mufasa: The Lion King 2024. Prequel to 2019 remake. Mixed reception.", 'commentary_correct': 'Correct! Mufasa prequel.', 'commentary_wrong': 'Mufasa prequel.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Spotify's biggest controversy is?", 'question': "Biggest?", 'answers': {'A': "Joe Rogan COVID misinformation outrage 2022", 'B': "Bad UI", 'C': "Higher prices", 'D': "Both A and artist payment issues"}, 'correct': 'D', 'explanation': "Multiple controversies — Joe Rogan $200M deal + COVID misinfo + artists protesting per-stream payments.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Hulu was founded by which trio?", 'question': "Originally owned by?", 'answers': {'A': "NBC, News Corp, ABC", 'B': "Netflix", 'C': "Apple", 'D': "Sony"}, 'correct': 'A', 'explanation': "Originally NBC + News Corp + ABC (later Disney). Now wholly owned by Disney.", 'commentary_correct': 'Correct! Big 3.', 'commentary_wrong': 'NBC, News Corp, ABC.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Netflix DVD service shut down in?", 'question': "When?", 'answers': {'A': "September 2023", 'B': "2010", 'C': "Still active", 'D': "2020"}, 'correct': 'A', 'explanation': "After 25 years of mailing DVDs. Netflix's original business. Officially ended September 29, 2023.", 'commentary_correct': 'Correct! 2023.', 'commentary_wrong': '2023. RIP DVDs.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "MoviePass collapsed because?", 'question': "Collapse?", 'answers': {'A': "Unsustainable $9.95/month for unlimited movies model", 'B': "Founder fraud", 'C': "Both — and CEO went to prison", 'D': "Theater chains banned it"}, 'correct': 'C', 'explanation': "Spent $32 per subscriber against $9.95 revenue. Founder Ted Farnsworth indicted for fraud. CEO Mitch Lowe charged.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Fraud + losses.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Tidal's 2015 launch was promoted by?", 'question': "Launched by?", 'answers': {'A': "Jay-Z and a press conference with 16 artists", 'B': "Beyoncé alone", 'C': "Spotify partnership", 'D': "Apple"}, 'correct': 'A', 'explanation': "Jay-Z bought Tidal 2015. Launched with Beyoncé, Madonna, Daft Punk etc. Slow growth. Sold to Square 2021.", 'commentary_correct': 'Correct! Jay-Z.', 'commentary_wrong': 'Jay-Z launch.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Discovery+ launched in 2021 to compete with?", 'question': "Compete with what era?", 'answers': {'A': "Streaming wars", 'B': "Cable TV", 'C': "Movie theaters", 'D': "All of the above"}, 'correct': 'A', 'explanation': "Launched January 2021. Merged into Max in 2023 after WB-Discovery deal.", 'commentary_correct': 'Correct! Streaming wars.', 'commentary_wrong': 'Streaming wars.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Pluto TV (free ad-supported streaming) is owned by?", 'question': "Owned by?", 'answers': {'A': "Paramount Global", 'B': "Disney", 'C': "Netflix", 'D': "Amazon"}, 'correct': 'A', 'explanation': "Viacom acquired Pluto TV 2019 for $340M. Now Paramount Global. Free streaming.", 'commentary_correct': 'Correct! Paramount.', 'commentary_wrong': 'Paramount.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Vine (Twitter's 6-second video service) shut down in?", 'question': "When?", 'answers': {'A': "January 2017", 'B': "2020", 'C': "2015", 'D': "Still operating"}, 'correct': 'A', 'explanation': "Twitter killed Vine January 2017. Logan Paul, Lele Pons etc came from Vine. Spawned TikTok-style format.", 'commentary_correct': 'Correct! 2017.', 'commentary_wrong': '2017. RIP.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "What did Twitch ban in 2018?", 'question': "Banned?", 'answers': {'A': "Real-time poker streams", 'B': "Crypto gambling sites — slots/dice streams (partial bans)", 'C': "Both", 'D': "Music"}, 'correct': 'B', 'explanation': "Twitch has done multiple gambling-related bans 2022. Crypto-casino streamers became flashpoint.", 'commentary_correct': 'Correct! Crypto gambling.', 'commentary_wrong': 'Crypto gambling.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "YouTube TV faced major outage during?", 'question': "When?", 'answers': {'A': "October 2021 World Series game", 'B': "Super Bowl 2020", 'C': "Both — outages are common during major events", 'D': "Olympics"}, 'correct': 'A', 'explanation': "Multiple major-event outages. World Series 2021 was particularly bad. YouTube credited users.", 'commentary_correct': 'Correct! World Series.', 'commentary_wrong': 'World Series outage.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Streaming Service Disasters', 'setup': "Twitter (X) Spaces feature was famously crashed by?", 'question': "Crashed by?", 'answers': {'A': "Ron DeSantis presidential campaign launch (2023)", 'B': "Elon Musk alone", 'C': "Both — same event", 'D': "A specific high traffic event"}, 'correct': 'C', 'explanation': "DeSantis launch on X Spaces with Elon crashed Twitter. Embarrassing for both.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Famous launch fail.', 'difficulty': 'medium', 'time_limit': 15},

    # BAD HAIR DECISIONS IN HISTORY
    {'category': 'Bad Hair Decisions in History', 'setup': "Donald Trump's hair is famous for?", 'question': "Famous for?", 'answers': {'A': "Combover", 'B': "Distinctive yellow-orange color", 'C': "Both A and B and constant debate over authenticity", 'D': "Being unchanged for 40 years"}, 'correct': 'C', 'explanation': "Trump's hair is its own character. Combover + signature color. Authenticity debated.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The 'Karen' haircut became infamous in?", 'question': "When?", 'answers': {'A': "2018-2020 as a meme", 'B': "1980s", 'C': "1960s", 'D': "1995"}, 'correct': 'A', 'explanation': "Asymmetrical bob with chunky highlights. Hair archetype for entitled middle-aged white woman meme.", 'commentary_correct': 'Correct! Late 2010s.', 'commentary_wrong': 'Late 2010s.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Mohawk hairstyle origins are?", 'question': "Origins?", 'answers': {'A': "Mohawk (Iroquois) people pre-colonization", 'B': "1970s punk subculture", 'C': "Both — punks adopted it as cultural appropriation", 'D': "1950s greasers"}, 'correct': 'C', 'explanation': "Native American style adopted by punks in 70s. Cultural conversation continues.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The mullet's peak popularity was?", 'question': "Peak?", 'answers': {'A': "1980s-early 90s", 'B': "1970s", 'C': "2020s comeback", 'D': "Both A and C"}, 'correct': 'D', 'explanation': "Peak 80s. Returned in 2020s as ironic style. Billy Ray Cyrus pioneered modern mullet.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The 1980s big-hair look was achieved by?", 'question': "How?", 'answers': {'A': "Massive amounts of hairspray and teasing", 'B': "Natural", 'C': "Wigs", 'D': "All of the above"}, 'correct': 'A', 'explanation': "AquaNet hairspray sales hit historic peaks. CFCs in hairspray contributed to ozone hole. Real environmental cost.", 'commentary_correct': 'Correct! Hairspray + tease.', 'commentary_wrong': 'Hairspray + tease.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Bowl cuts were popularized by?", 'question': "Popularized by?", 'answers': {'A': "Multiple decades, but iconically the Beatles 1960s", 'B': "Jim Carrey", 'C': "1990s", 'D': "Always existed"}, 'correct': 'A', 'explanation': "Beatles' moptops 1960s. Returned in 1990s skater scene. Dumb and Dumber satirized it.", 'commentary_correct': 'Correct! Beatles era.', 'commentary_wrong': 'Beatles era.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Marie Antoinette's hair famously included?", 'question': "Included?", 'answers': {'A': "Ships and gardens built into the hairstyles", 'B': "Live birds", 'C': "Just powder", 'D': "Both A and animals would sometimes nest"}, 'correct': 'D', 'explanation': "Pouf hairstyles. Ships, garden scenes. Reports of mice and bird nests. Real fashion of late 1700s court.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Justin Bieber's 2009 swoop hair was?", 'question': "Was?", 'answers': {'A': "His signature look that defined late-2000s teen culture", 'B': "Insulted nationally", 'C': "Always disguising baldness", 'D': "Both A and copied widely"}, 'correct': 'D', 'explanation': "Iconic side-swept Bieber bangs. Hundreds of millions of dollars in barber appointments worldwide.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The 1985 Tina Turner 'Private Dancer' hair was?", 'question': "Was?", 'answers': {'A': "Massive bouffant + wigs", 'B': "Mostly her own hair", 'C': "Both — depends on era/photo", 'D': "Always a wig"}, 'correct': 'C', 'explanation': "Tina's hair evolved. Many wigs. Some real. Iconic regardless.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The 'Rachel' haircut (1995) was named for?", 'question': "Named for?", 'answers': {'A': "Jennifer Aniston's character in Friends", 'B': "Rachel from Bewitched", 'C': "Rachel from Suits", 'D': "Just a hairstylist named Rachel"}, 'correct': 'A', 'explanation': "Layered shag from Friends. Most-requested haircut of 90s. Aniston later said she hated it.", 'commentary_correct': 'Correct! Friends.', 'commentary_wrong': 'Friends. The Rachel.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Sinéad O'Connor's shaved head was a protest against?", 'question': "Against?", 'answers': {'A': "Music industry expectations for women", 'B': "Religious oppression", 'C': "Both — multiple statements", 'D': "Nothing — random choice"}, 'correct': 'C', 'explanation': "Refused industry pressure for sexier look. Multiple religious statements over career. Bald became her trademark.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Britney Spears' 2007 head-shave was at?", 'question': "Where?", 'answers': {'A': "Esther's Haircutting Studio, Tarzana CA", 'B': "Home", 'C': "A concert", 'D': "An airport"}, 'correct': 'A', 'explanation': "February 16, 2007. Esther's salon. She shaved her own head with their clippers. Paparazzi feeding frenzy.", 'commentary_correct': 'Correct! Esther\'s.', 'commentary_wrong': 'Esther\'s in Tarzana.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "ZZ Top members are known for?", 'question': "For?", 'answers': {'A': "Massive beards (except the drummer named Frank Beard)", 'B': "All sporting mullets", 'C': "Bald heads", 'D': "Tribal tattoos"}, 'correct': 'A', 'explanation': "The drummer ZZ Top — Frank Beard — is the only one without a beard. Real cosmic joke.", 'commentary_correct': 'Correct! Frank Beard, no beard.', 'commentary_wrong': 'Frank Beard. No beard.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Phil Spector's wig at his 2009 murder trial was?", 'question': "Was?", 'answers': {'A': "Frizzy, blonde, gigantic — courtroom mockery", 'B': "Subtle", 'C': "Black", 'D': "Both A and Spector reportedly insisted on it"}, 'correct': 'D', 'explanation': "Famous courtroom wig. Each day a different style. Mocked widely. Spector convicted.", 'commentary_correct': 'Correct! Massive wig.', 'commentary_wrong': 'Massive wig.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "What is the 'Boris Johnson hair' look?", 'question': "Look?", 'answers': {'A': "Deliberately mussed blonde mop", 'B': "A cult of personality marker", 'C': "Both — and reportedly intentional pre-press", 'D': "Just bedhead"}, 'correct': 'C', 'explanation': "BoJo would purposely tousle hair before TV appearances. Carefully crafted 'unfit' look.", 'commentary_correct': 'Correct! Intentional mess.', 'commentary_wrong': 'Intentional mess.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The 1980s 'big bangs' look was created by?", 'question': "Created by?", 'answers': {'A': "Crimping + teasing + serious hairspray", 'B': "Genetics", 'C': "Wigs only", 'D': "Both A and Aussie Hair products dominated the market"}, 'correct': 'A', 'explanation': "Hour-long ritual. Curling iron, crimping iron, teasing comb, AquaNet. The whole production.", 'commentary_correct': 'Correct! Crimp + tease.', 'commentary_wrong': 'Crimp + tease.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The Beatles' famous moptop was inspired by?", 'question': "Inspired by?", 'answers': {'A': "German rock band Astrid Kirchherr's style choices", 'B': "Just random choice", 'C': "Their barber", 'D': "Elvis"}, 'correct': 'A', 'explanation': "Photographer Astrid Kirchherr in Hamburg styled them. Replaced Elvis-era quiffs with the moptop. Revolution.", 'commentary_correct': 'Correct! Astrid Kirchherr.', 'commentary_wrong': 'Astrid Kirchherr. Hamburg.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "The man bun became viral in?", 'question': "When?", 'answers': {'A': "2014-2015 peak hipster era", 'B': "1970s", 'C': "2020", 'D': "Always existed"}, 'correct': 'A', 'explanation': "Peaked 2014-2015. Mocked endlessly. Declined since. Some celebrities still rock it.", 'commentary_correct': 'Correct! 2014-15.', 'commentary_wrong': '2014-15.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Comb-overs are designed to?", 'question': "Designed to?", 'answers': {'A': "Hide baldness using long side hair", 'B': "Be fashionable", 'C': "Both — but never fool anyone", 'D': "Mostly fail visually"}, 'correct': 'C', 'explanation': "Comb-overs are universally recognized failures. Studies show they fool no one. Yet persist.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Hair Decisions in History', 'setup': "Elvis Presley's pompadour required?", 'question': "Required?", 'answers': {'A': "Daily styling with pomade and combing", 'B': "Wigs only", 'C': "Both — though early career was real hair", 'D': "Constant trimming"}, 'correct': 'A', 'explanation': "Real hair, dyed black, daily pompadour. Set the male-rock-star template.", 'commentary_correct': 'Correct! Daily ritual.', 'commentary_wrong': 'Daily ritual.', 'difficulty': 'medium', 'time_limit': 15},

    # WEDDING DAY CATASTROPHES
    {'category': 'Wedding Day Catastrophes', 'setup': "The 1991 'Runaway Bride' case (Jennifer Wilbanks) involved?", 'question': "Involved?", 'answers': {'A': "Bride faked her own kidnapping to avoid wedding", 'B': "Got cold feet", 'C': "Both A and B — and went to Albuquerque", 'D': "Married someone else"}, 'correct': 'C', 'explanation': "April 2005 (not 1991). Wilbanks faked kidnapping, fled to Albuquerque. Found innocent of crime but charged with falsifying.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Fake kidnapping.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "A 2008 Reno-area wedding ended with the groom doing what?", 'question': "Doing?", 'answers': {'A': "Being shot by jilted ex-girlfriend at the altar", 'B': "Running away", 'C': "Both", 'D': "A heart attack"}, 'correct': 'A', 'explanation': "Multiple ex-attack wedding incidents documented. Real horror movie style. Charges followed.", 'commentary_correct': 'Correct! Shot by ex.', 'commentary_wrong': 'Shot by ex.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Wedding registry abuse is a famous theme in?", 'question': "Famous in?", 'answers': {'A': "Multiple TV shows have featured registry-fraud schemes", 'B': "Just one movie", 'C': "Nothing real", 'D': "Both A and there's a TV show called Wedding Crashers"}, 'correct': 'A', 'explanation': "Real wedding registries get scammed regularly. Stolen identity, fake returns. Common.", 'commentary_correct': 'Correct! Multiple shows.', 'commentary_wrong': 'Real scam.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Most expensive wedding ever was?", 'question': "Most expensive?", 'answers': {'A': "Mukesh Ambani's son's 2024 wedding — ~$600M+", 'B': "Princess Diana's", 'C': "Kim Kardashian's", 'D': "Prince Charles' first"}, 'correct': 'A', 'explanation': "Mumbai 2024. Anant Ambani wedding. Rihanna performed. Bieber performed. Beyoncé attended. Half a billion-plus.", 'commentary_correct': 'Correct! Ambani.', 'commentary_wrong': 'Ambani 2024.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Kim Kardashian and Kris Humphries' marriage lasted how long?", 'question': "How long?", 'answers': {'A': "72 days", 'B': "1 year", 'C': "5 years", 'D': "3 months"}, 'correct': 'A', 'explanation': "72 days. Filed for divorce October 2011 after marrying in August. Reality TV spectacle.", 'commentary_correct': 'Correct! 72 days.', 'commentary_wrong': '72 days.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Britney Spears' first marriage (2004) lasted?", 'question': "How long?", 'answers': {'A': "55 hours", 'B': "1 year", 'C': "5 days", 'D': "1 month"}, 'correct': 'A', 'explanation': "Las Vegas marriage to Jason Alexander. Annulled in 55 hours. Britney was on tour.", 'commentary_correct': 'Correct! 55 hours.', 'commentary_wrong': '55 hours.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Real wedding venue fires happen most often because of?", 'question': "Most common cause?", 'answers': {'A': "Sparklers and candles", 'B': "Electrical issues", 'C': "Cigarettes", 'D': "All of the above"}, 'correct': 'D', 'explanation': "Wedding venue fires happen multiple times yearly. Sparklers, candles, electrical all common.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Pamela Anderson's 1995 wedding to Tommy Lee happened after how long of dating?", 'question': "After?", 'answers': {'A': "96 hours of meeting", 'B': "1 year", 'C': "6 months", 'D': "2 weeks"}, 'correct': 'A', 'explanation': "Met, dated, married within 96 hours in Cancun. Marriage was tumultuous. Divorced 1998.", 'commentary_correct': 'Correct! 4 days.', 'commentary_wrong': '96 hours.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Famous wedding pranks gone wrong include?", 'question': "Include?", 'answers': {'A': "Mock 'objection' that was real", 'B': "Replacing rings with fakes that got eaten by ring bearer dog", 'C': "Both happen regularly", 'D': "Fake fainting that became real"}, 'correct': 'C', 'explanation': "Pet ring-eaters and confused objections are wedding lore. Real cases.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "A 2018 viral wedding fail showed a groom?", 'question': "Showed what?", 'answers': {'A': "Falling backward off a balcony at reception", 'B': "Drop the cake", 'C': "Run away mid-ceremony", 'D': "All have happened in viral wedding fail compilations"}, 'correct': 'D', 'explanation': "Wedding fail compilations are a YouTube genre. All three (and more) are documented.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All. Wedding compilation gold.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Wedding-related fraud cases sometimes involve?", 'question': "Involve?", 'answers': {'A': "Fake brides on Russian/Ukrainian marriage sites", 'B': "Visa fraud (green card weddings)", 'C': "Both — major federal investigations", 'D': "Bookkeeping fraud"}, 'correct': 'C', 'explanation': "International marriage scams + green card fraud are both major issues. Multiple federal cases yearly.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "A 2013 viral wedding ceremony was interrupted by?", 'question': "Interrupted by?", 'answers': {'A': "A literal bald eagle that wouldn't deliver the rings on cue", 'B': "An earthquake", 'C': "A lawn mower", 'D': "Both A and B happened in different incidents"}, 'correct': 'A', 'explanation': "Live-animal ring-bearer attempts often fail spectacularly. Eagle famously didn't cooperate.", 'commentary_correct': 'Correct! Eagle fail.', 'commentary_wrong': 'Eagle fail.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Prince William's 2011 wedding to Kate Middleton had?", 'question': "Had?", 'answers': {'A': "~24M US viewers + 2B+ worldwide", 'B': "Just British press", 'C': "Only invited guests as TV audience", 'D': "Both A and a hat that became a meme"}, 'correct': 'D', 'explanation': "Princess Beatrice's hat became infamous. 2B+ watched. Defining royal event.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. The hat.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Wedding dress disasters often include?", 'question': "Include?", 'answers': {'A': "Tearing during the dance", 'B': "Last-minute alteration failures", 'C': "Stains from food", 'D': "All happen frequently"}, 'correct': 'D', 'explanation': "All three are common. Brides have backup options. Wedding planners exist.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "What's the average cost of a US wedding in 2024?", 'question': "Approximate?", 'answers': {'A': "~$33,000", 'B': "~$10,000", 'C': "~$100,000", 'D': "~$5,000"}, 'correct': 'A', 'explanation': "TheKnot 2024 study: ~$33K. Up from $30K in 2022. Continues to rise.", 'commentary_correct': 'Correct! ~$33K.', 'commentary_wrong': '~$33K.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Wedding cake disasters in viral videos commonly involve?", 'question': "Commonly?", 'answers': {'A': "Cake collapse mid-cut", 'B': "Cake on floor", 'C': "Cake falling on bride/groom", 'D': "All three happen regularly in wedding fail comps"}, 'correct': 'D', 'explanation': "Cake disasters are perennial. Hot venues melt frosting. Heavy tiers collapse. Real.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "The shortest celebrity marriage was?", 'question': "Shortest?", 'answers': {'A': "Britney Spears (55 hours)", 'B': "Cher and Gregg Allman (9 days)", 'C': "Kim and Kris (72 days)", 'D': "Both A and B are commonly cited"}, 'correct': 'D', 'explanation': "Both Britney and Cher hold records for very short marriages. Cher publicly regretted hers.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "What's 'wedding crashing' in real life?", 'question': "What is it?", 'answers': {'A': "Showing up uninvited (movie premise was based on real practice)", 'B': "Just a movie", 'C': "Both", 'D': "An old British tradition"}, 'correct': 'C', 'explanation': "Real practice. Vince Vaughn/Owen Wilson movie inspired by it. Wedding planners look for crashers.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Family wedding fights become news regularly. Most common spark?", 'question': "Most common spark?", 'answers': {'A': "Seating chart disputes", 'B': "Cake serving", 'C': "Speech content", 'D': "All — fights at weddings are routine"}, 'correct': 'D', 'explanation': "Family weddings are emotional pressure cookers. All three are common spark.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All. Wedding stress.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Wedding Day Catastrophes', 'setup': "Object-to-marriage 'speak now' moments?", 'question': "Real frequency?", 'answers': {'A': "Almost never happen (myth from TV)", 'B': "Happen often", 'C': "Both A and the rare ones go viral", 'D': "Required by law"}, 'correct': 'C', 'explanation': "Almost never happens. When it does, viral guaranteed. Legal objection language is now optional in most ceremonies.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},

    # SPORTS MASCOT BRAWLS
    {'category': 'Sports Mascot Brawls', 'setup': "The Phillie Phanatic was sued by who?", 'question': "Sued by?", 'answers': {'A': "Tommy Lasorda (Dodgers manager) — Phanatic mocked him with an effigy", 'B': "MLB officially", 'C': "A fan", 'D': "Both A and others — the Phanatic gets sued a lot"}, 'correct': 'D', 'explanation': "Phanatic has been involved in many lawsuits over decades. Including Lasorda effigy incident and various fan injuries.", 'commentary_correct': 'Correct! Multiple suits.', 'commentary_wrong': 'Multiple suits.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The San Diego Chicken famously had what feud?", 'question': "Feud with?", 'answers': {'A': "Multiple other mascots in 'mascot wars'", 'B': "Pitchers who hated his antics", 'C': "Both", 'D': "Was best friends with everyone"}, 'correct': 'C', 'explanation': "SD Chicken (Ted Giannoulas) feuded with many mascots and players. Famous mascot-on-mascot fights.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The Wild Wing (Anaheim Ducks mascot) caught fire in?", 'question': "When?", 'answers': {'A': "1995 — during a pre-game stunt", 'B': "2010", 'C': "Never", 'D': "2005"}, 'correct': 'A', 'explanation': "Wild Wing attempted to jump through a flaming hoop. Costume caught fire. Real, on-camera.", 'commentary_correct': 'Correct! 1995.', 'commentary_wrong': '1995. Flame hoop fail.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "A 2016 viral video showed two mascots?", 'question': "Doing what?", 'answers': {'A': "Fighting at a minor league baseball game", 'B': "Hugging", 'C': "Both A and other incidents", 'D': "Singing"}, 'correct': 'C', 'explanation': "Mascot brawls at minor league games are nearly annual. Viral video content gold.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Brutus the Buckeye (Ohio State) is portrayed by?", 'question': "Portrayed by?", 'answers': {'A': "A student each year (multiple actors)", 'B': "One famous person for life", 'C': "Coaching staff", 'D': "Both A and identities kept secret"}, 'correct': 'D', 'explanation': "Multiple students share role. Identities kept secret to preserve mascot magic.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The Stanford Tree is not officially?", 'question': "Not officially?", 'answers': {'A': "An official mascot (Stanford has no official mascot since 1972)", 'B': "Allowed at games", 'C': "Both A and the Tree is unofficial-official", 'D': "A real tree"}, 'correct': 'C', 'explanation': "Stanford retired 'Indian' mascot 1972. Never adopted new one. The Tree is unofficial Band mascot.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Unofficial Tree.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Mr. Met is the longest-running MLB mascot. He debuted in?", 'question': "When?", 'answers': {'A': "1964", 'B': "1990", 'C': "1955", 'D': "1980"}, 'correct': 'A', 'explanation': "Mr. Met since 1964. Major League Baseball's first costumed mascot. Iconic baseball-head.", 'commentary_correct': 'Correct! 1964.', 'commentary_wrong': '1964.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Mr. Met gave fans the middle finger in?", 'question': "When?", 'answers': {'A': "2017", 'B': "2005", 'C': "1995", 'D': "Never happened"}, 'correct': 'A', 'explanation': "May 2017. Mr. Met flipped off fans. Caught on camera. Person inside replaced. Mascot lore.", 'commentary_correct': 'Correct! 2017.', 'commentary_wrong': '2017.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The Sacramento Kings mascot Slamson is?", 'question': "What animal?", 'answers': {'A': "A lion", 'B': "A bear", 'C': "A king", 'D': "An eagle"}, 'correct': 'A', 'explanation': "Slamson the Lion. NBA mascot. Multiple slam-dunk-trampoline stunts.", 'commentary_correct': 'Correct! Lion.', 'commentary_wrong': 'Lion.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Gritty (Philadelphia Flyers) was introduced in?", 'question': "When?", 'answers': {'A': "2018", 'B': "2010", 'C': "1995", 'D': "2020"}, 'correct': 'A', 'explanation': "September 2018. Instant viral sensation. Initially mocked as creepy. Embraced quickly. Cult icon.", 'commentary_correct': 'Correct! 2018.', 'commentary_wrong': '2018. Gritty arrived.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Sourdough Sam is the mascot of?", 'question': "Of which team?", 'answers': {'A': "San Francisco 49ers", 'B': "Oakland A's", 'C': "Golden State Warriors", 'D': "Stanford"}, 'correct': 'A', 'explanation': "Niners mascot since 1994. Gold prospector themed. Honors team name.", 'commentary_correct': 'Correct! 49ers.', 'commentary_wrong': '49ers.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "A 1999 mascot was injured during?", 'question': "Injured during?", 'answers': {'A': "Tumbling stunt at an NFL halftime show", 'B': "Bull-riding stunt", 'C': "Both A and B happened in different incidents", 'D': "A handshake"}, 'correct': 'C', 'explanation': "Multiple mascot stunt injuries. Including bull-riding fails (Houston Texans' bull) and gymnastics fails.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Bucky Badger (Wisconsin) is famous for?", 'question': "Famous for?", 'answers': {'A': "Doing push-ups for every Wisconsin score", 'B': "Riding a horse", 'C': "Both A and waving a giant pom-pom", 'D': "Just standing there"}, 'correct': 'C', 'explanation': "Push-ups since 1971. Number = the score after each TD. Long tradition.", 'commentary_correct': 'Correct! Push-ups.', 'commentary_wrong': 'Push-ups.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The youngest mascot performer can be hired at?", 'question': "Minimum age?", 'answers': {'A': "16 (most teams)", 'B': "21", 'C': "18", 'D': "Both A and labor laws vary"}, 'correct': 'D', 'explanation': "Most teams require 16-18 minimum. Labor laws differ. Some pro teams hire only adults.", 'commentary_correct': 'Correct! 16+.', 'commentary_wrong': '16+ usually.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The Aflac duck and Geico gecko are technically?", 'question': "Technically?", 'answers': {'A': "Insurance mascots, not sports — but appear in stadium ads", 'B': "Sports team mascots", 'C': "Both", 'D': "Mythical creatures"}, 'correct': 'A', 'explanation': "Insurance mascots. Stadium-adjacent through advertising deals. Lots of cross-pollination.", 'commentary_correct': 'Correct! Insurance.', 'commentary_wrong': 'Insurance mascots.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The original Stanford mascot was the?", 'question': "Was?", 'answers': {'A': "Indian (retired 1972)", 'B': "Cardinal", 'C': "Tree", 'D': "Bear"}, 'correct': 'A', 'explanation': "Stanford Indian until 1972. Replaced with no mascot. Tree is unofficial since 1975.", 'commentary_correct': 'Correct! Indian.', 'commentary_wrong': 'Indian.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Chief Wahoo (Cleveland baseball) was retired in?", 'question': "When?", 'answers': {'A': "2018", 'B': "1990", 'C': "2010", 'D': "Still used"}, 'correct': 'A', 'explanation': "Cleveland retired Chief Wahoo 2018. Renamed Guardians 2021. Long controversy.", 'commentary_correct': 'Correct! 2018.', 'commentary_wrong': '2018.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Hurricane Maddy (Tulane) is named after?", 'question': "Named after?", 'answers': {'A': "Hurricane Katrina (the team's resilience symbol)", 'B': "An owner's daughter", 'C': "A weather pattern", 'D': "Both A and the name pre-dated 2005"}, 'correct': 'A', 'explanation': "Maddy added post-Katrina to honor Tulane's resilience. Football comeback after 2005 storm.", 'commentary_correct': 'Correct! Post-Katrina.', 'commentary_wrong': 'Post-Katrina.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "Otto the Orange (Syracuse) is?", 'question': "What kind of mascot?", 'answers': {'A': "An anthropomorphic orange fruit", 'B': "A Saluki dog", 'C': "Otto means 'orange' in German", 'D': "Both A and named for its predecessor 'Otto'"}, 'correct': 'A', 'explanation': "Literal orange fruit with limbs. Predecessor was 'Saltine Warrior' (Native American), retired in 1978.", 'commentary_correct': 'Correct! An orange.', 'commentary_wrong': 'An orange.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Sports Mascot Brawls', 'setup': "The most expensive mascot suit is approximately?", 'question': "Approximate cost?", 'answers': {'A': "~$50,000 for top tier pro suits", 'B': "$1,000", 'C': "$1 million", 'D': "$10,000"}, 'correct': 'A', 'explanation': "Pro NBA/MLB mascot suits cost $30K-50K. Multiple copies needed. Maintenance budgets significant.", 'commentary_correct': 'Correct! ~$50K.', 'commentary_wrong': '~$50K.', 'difficulty': 'hard', 'time_limit': 15},

    # PRANKS THAT WENT TOO FAR
    {'category': 'Pranks That Went Too Far', 'setup': "A 2012 Australian radio prank involved calling whom?", 'question': "Called whom?", 'answers': {'A': "Kate Middleton's hospital room (Mel Greig + Michael Christian)", 'B': "The Queen", 'C': "Tony Abbott", 'D': "Both A and a nurse who took the call died by suicide"}, 'correct': 'D', 'explanation': "DJs pretended to be Queen Elizabeth. Nurse Jacintha Saldanha forwarded call. Took her own life days later.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Tragic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Logan Paul's 2018 'suicide forest' video?", 'question': "Was about?", 'answers': {'A': "Filming a body in Japan's Aokigahara forest", 'B': "His brother Jake", 'C': "A movie scene", 'D': "Both A and triggering massive YouTube cleanup"}, 'correct': 'D', 'explanation': "Logan Paul filmed body. Posted it. YouTube delayed action. Reformed Adsense policies after backlash.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Jeremy Meeks 'hot felon' became viral in?", 'question': "When?", 'answers': {'A': "2014 — Stockton PD shared his mugshot", 'B': "2010", 'C': "2018", 'D': "2020"}, 'correct': 'A', 'explanation': "Stockton PD posted his mugshot. Went viral. Modeling contracts followed. Real story.", 'commentary_correct': 'Correct! 2014.', 'commentary_wrong': '2014.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Mr. Beast videos have been criticized for?", 'question': "Criticized for?", 'answers': {'A': "Encouraging dangerous food challenges", 'B': "Worker conditions", 'C': "Both A and B in different controversies", 'D': "Squid Game IRL controversy"}, 'correct': 'C', 'explanation': "Mr. Beast has faced multiple controversies including extreme challenges and his MrBeast Burger venture's failures.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Ashton Kutcher's 'Punk'd' was on what network?", 'question': "Network?", 'answers': {'A': "MTV", 'B': "VH1", 'C': "Comedy Central", 'D': "Spike"}, 'correct': 'A', 'explanation': "MTV's Punk'd (2003-2007). Multiple celebrity pranks. Justin Timberlake crying episode is famous.", 'commentary_correct': 'Correct! MTV.', 'commentary_wrong': 'MTV.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "The Cash Cab driver Ben Bailey was technically?", 'question': "Technically?", 'answers': {'A': "Licensed NYC cab driver who could legally pick up fares", 'B': "Just an actor", 'C': "Both — and he had a special exemption", 'D': "A retired cab driver"}, 'correct': 'A', 'explanation': "Real cab license. Show was filmed with actual fares (mostly pre-arranged participants). Real lighting/effects.", 'commentary_correct': 'Correct! Real driver.', 'commentary_wrong': 'Real driver.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Tom Mabe pranks involve?", 'question': "Involve?", 'answers': {'A': "Pranking telemarketers and recording their reactions", 'B': "Door-to-door scams", 'C': "Both", 'D': "Strictly office pranks"}, 'correct': 'A', 'explanation': "Comedy career built on telemarketer pranks. Reverse-prank: he wastes their time entertainingly.", 'commentary_correct': 'Correct! Telemarketers.', 'commentary_wrong': 'Telemarketer pranks.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "A YouTube channel famous for swatting victims faced?", 'question': "Faced?", 'answers': {'A': "Federal charges and prison time", 'B': "Just YouTube bans", 'C': "Both A and B", 'D': "Nothing"}, 'correct': 'C', 'explanation': "Multiple high-profile swatting channels resulted in arrests. People have died from swatting calls (Andrew Finch, 2017).", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Real prison time.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Punk'd Justin Timberlake reportedly?", 'question': "Reportedly?", 'answers': {'A': "Cried thinking IRS had seized everything", 'B': "Laughed it off", 'C': "Both — he cried then laughed", 'D': "Walked out"}, 'correct': 'C', 'explanation': "Famous JT Punk'd episode. He cried when told he owed back taxes on private jet. Iconic.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "The Borat (Sacha Baron Cohen) Kazakhstan ambassador called?", 'question': "Called?", 'answers': {'A': "Borat 'a vulgar character'", 'B': "Sued Cohen", 'C': "Both A and embraced the tourism boost", 'D': "Banned Cohen from Kazakhstan"}, 'correct': 'C', 'explanation': "Kazakhstan initially upset. Later embraced as boost to international tourism. 'Very nice!' campaigns.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Howard Stern's pranks in the 90s included?", 'question': "Included?", 'answers': {'A': "On-air calls to celebrities pretending to be other celebrities", 'B': "Inviting strippers", 'C': "Both", 'D': "Just music interviews"}, 'correct': 'C', 'explanation': "Stern's morning show. Multiple legal issues. Career built on shocking content. FCC fines.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "The Snake Bite Prank (YouTuber Roman Atwood) caused?", 'question': "Caused?", 'answers': {'A': "Real ER visits", 'B': "Channel bans", 'C': "Both A and lawsuits from prank victims", 'D': "Multiple police callouts"}, 'correct': 'D', 'explanation': "Prank channels regularly cause real police involvement. Snake-related pranks have triggered emergency responses.", 'commentary_correct': 'Correct! Police callouts.', 'commentary_wrong': 'Police callouts.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Andrew Schulz's 2018 'Eminem prank' featured?", 'question': "Featured?", 'answers': {'A': "Schulz dressed as Eminem to confuse fans", 'B': "A failed eulogy", 'C': "Both A — but Eminem himself never weighed in", 'D': "A successful 1990s reunion"}, 'correct': 'A', 'explanation': "Andrew Schulz's pranks include impersonation bits. Schulz built career on edgy comedy.", 'commentary_correct': 'Correct! Eminem dress.', 'commentary_wrong': 'Eminem dress.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "PrankvsPrank couple drama in 2017 was?", 'question': "Was?", 'answers': {'A': "Genuine breakup played out partially on camera", 'B': "Staged for views", 'C': "Both — fans never knew which", 'D': "A scripted reality show"}, 'correct': 'C', 'explanation': "Jesse and Jeana eventually split. Audience never sure when pranks ended and real life began.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Tommy Lipnitsky 'fake homeless' YouTube prankster faced?", 'question': "Faced?", 'answers': {'A': "Backlash for monetizing fake homelessness", 'B': "YouTube demonetization", 'C': "Both", 'D': "A movie deal"}, 'correct': 'C', 'explanation': "Multiple YouTubers caught faking homelessness for views. Faced bans + community backlash.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Jackass cast member Ryan Dunn died in?", 'question': "When?", 'answers': {'A': "2011 car crash", 'B': "2005 stunt", 'C': "2020", 'D': "Hasn't died"}, 'correct': 'A', 'explanation': "Jackass star died in single-vehicle crash 2011. Drunk driving. Tragedy reframed his career.", 'commentary_correct': 'Correct! 2011.', 'commentary_wrong': '2011.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "The 'YG Boys' pranking elderly in airports led to?", 'question': "Led to?", 'answers': {'A': "Multiple lawsuits + airport bans", 'B': "Nothing — it was successful", 'C': "Channel bans", 'D': "All of the above"}, 'correct': 'D', 'explanation': "Airport prank channels have triggered multiple lawsuits and bans from major airports.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "A 2007 viral 'TV news prank' had a fake?", 'question': "Fake?", 'answers': {'A': "Reporter falling off ladder mid-broadcast", 'B': "Anchor passing out", 'C': "Both A and B happen frequently in compilations", 'D': "Weatherman fainting"}, 'correct': 'C', 'explanation': "TV news bloopers are a YouTube genre. Real and staged events compete for views.", 'commentary_correct': 'Correct! All.', 'commentary_wrong': 'All.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Snoop Dogg's pranks include?", 'question': "Include?", 'answers': {'A': "Multiple legal celebrity feuds", 'B': "Surprise concerts", 'C': "Both", 'D': "Skydiving with Eminem"}, 'correct': 'C', 'explanation': "Snoop's career includes feuds, pranks, and many surprise appearances. Mostly playful in recent years.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pranks That Went Too Far', 'setup': "Top Gear (UK) was canceled because of?", 'question': "Canceled because?", 'answers': {'A': "Jeremy Clarkson punching a producer", 'B': "Budget", 'C': "Ratings", 'D': "Both A and BBC ended his contract"}, 'correct': 'D', 'explanation': "Clarkson punched producer Oisin Tymon 2015. BBC ended his contract. Top Gear continued. He went to Amazon.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
]


def seed_v4_batch2c():
    ph = get_placeholder()
    added = 0
    for q in V4_BATCH2C_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (cat['id'], q['question'], q.get('setup','') or '',
                  q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                  q['correct'], q.get('difficulty','medium'), q.get('time_limit',15),
                  q.get('explanation',''), q.get('commentary_correct',''), q.get('commentary_wrong','')))
            added += 1
        except Exception as e:
            print(f"[v4-b2c] {e}")
    print(f"✅ v4 batch2c added {added} ({len(V4_BATCH2C_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch2c()
