"""v4 batch 2e — final 5 batch-2 categories. 100 questions.
Internet Hoaxes Exposed, Bad Album Covers, Stripper Heists & White-Collar Crime,
Pageant Mishaps, Bizarre Phobias.
"""
from trivia_database import execute_query, get_placeholder, get_category_by_name


V4_BATCH2E_QUESTIONS = [
    # INTERNET HOAXES EXPOSED
    {'category': 'Internet Hoaxes Exposed', 'setup': "Storm Area 51 in September 2019 was started as?", 'question': "Started as?", 'answers': {'A': "A Facebook joke event by Matty Roberts", 'B': "A serious militia movement", 'C': "Both A — but ~2 million people 'joined'", 'D': "A government psyop"}, 'correct': 'C', 'explanation': "Matty Roberts created Facebook event as joke June 2019. ~2M RSVPs. ~150 actually showed up. Nothing happened.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. Facebook joke.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The Momo Challenge was?", 'question': "Was?", 'answers': {'A': "A moral panic that turned out to be fake", 'B': "A real WhatsApp game", 'C': "Both A — and never actually killed anyone", 'D': "A horror movie marketing"}, 'correct': 'C', 'explanation': "Momo Challenge: 2018-2019 internet panic. No deaths actually linked. Sculpture by Keisuke Aiso. All clickbait.", 'commentary_correct': 'Correct! Hoax panic.', 'commentary_wrong': 'Hoax panic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Slender Man originated from?", 'question': "Originated from?", 'answers': {'A': "Eric Knudsen's 2009 Something Awful forum post", 'B': "Ancient folklore", 'C': "Both A — but is entirely fictional creation", 'D': "A Japanese ghost story"}, 'correct': 'C', 'explanation': "Created June 2009 for Photoshop contest on Something Awful. Inspired 2014 Waukesha stabbing of 12yo. Tragic.", 'commentary_correct': 'Correct! Eric Knudsen.', 'commentary_wrong': '2009 forum post.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The Bigfoot 'Patterson-Gimlin' 1967 film is?", 'question': "Is?", 'answers': {'A': "Most analyzed Bigfoot footage ever", 'B': "Confirmed hoax", 'C': "Disputed (some say man in suit)", 'D': "Both A and C"}, 'correct': 'D', 'explanation': "Patterson-Gimlin film Bluff Creek 1967. Disputed for decades. Bob Heironimus claimed to be the man in suit.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The Loch Ness Monster's 'Surgeon's Photo' (1934) was?", 'question': "Was?", 'answers': {'A': "Definitively a hoax with model on toy submarine", 'B': "Real photo", 'C': "Both A and B — confessed 1994", 'D': "A dolphin"}, 'correct': 'C', 'explanation': "1994 confession by stepson of original hoaxer. Toy submarine + plastic. 'Surgeon' was a cover identity.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Balloon Boy (2009) hoax was about?", 'question': "About?", 'answers': {'A': "Falcon Heene's family faked his disappearance in a balloon", 'B': "He was hiding in the attic", 'C': "Both A and B — and the kid said 'we did this for a show'", 'D': "Dad got prison"}, 'correct': 'C', 'explanation': "Richard and Mayumi Heene fake. Falcon was in attic. Said 'we did this for a show' on Larry King. Dad imprisoned.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. The Heenes.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'Plandemic' (2020) misinformation video was?", 'question': "Was?", 'answers': {'A': "Conspiracy doc about COVID misinformation", 'B': "Got billions of views before takedown", 'C': "Both A and B — by Mikki Willis", 'D': "Banned everywhere"}, 'correct': 'C', 'explanation': "Mikki Willis' Plandemic 2020. 8M views before takedown. Spread conspiracy theories. Notable misinformation case.", 'commentary_correct': 'Correct! Plandemic.', 'commentary_wrong': 'Plandemic.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'Tide Pod Challenge' was?", 'question': "Was?", 'answers': {'A': "Teens eating Tide laundry pods", 'B': "Real but exaggerated by media", 'C': "Both — actual cases were rare", 'D': "Pure media hoax"}, 'correct': 'C', 'explanation': "Tide Pod Challenge real but rare. Media frenzy made it seem epidemic. Poison Control did see surge.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'Bird Box Challenge' from Netflix's 2018 movie was?", 'question': "Was?", 'answers': {'A': "People doing things blindfolded — Netflix asked them to stop", 'B': "Just a meme", 'C': "Both", 'D': "A 5K race"}, 'correct': 'C', 'explanation': "Netflix actively tweeted asking people to stop the blindfold challenge after car crashes. Real safety concern.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Pizzagate (2016) was?", 'question': "Was?", 'answers': {'A': "False conspiracy about Comet Ping Pong + Clinton", 'B': "Led to a real shooting (Edgar Welch)", 'C': "Both A and B", 'D': "A pizza recipe controversy"}, 'correct': 'C', 'explanation': "Pizzagate conspiracy. Edgar Welch fired AR-15 in Comet Ping Pong DC. Convicted. Real damage from fake conspiracy.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'I am a 30 year old who hasn't watched TV' Reddit AMA was?", 'question': "Was?", 'answers': {'A': "A famous 'AMA' that turned out fake", 'B': "Real", 'C': "Both", 'D': "Standard Reddit fare"}, 'correct': 'A', 'explanation': "Multiple viral AMAs revealed as fake. Reddit's verification process improved over years.", 'commentary_correct': 'Correct! Fake AMA.', 'commentary_wrong': 'Fake AMA.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'tide ad' deepfake of Obama was?", 'question': "Was?", 'answers': {'A': "BuzzFeed's 2018 demo of how deepfakes work", 'B': "Real propaganda", 'C': "Both A — Jordan Peele voicing Obama", 'D': "Made by Russia"}, 'correct': 'C', 'explanation': "BuzzFeed/Jordan Peele demo of deepfake tech. Obama saying things he never said. Educational warning.", 'commentary_correct': 'Correct! BuzzFeed demo.', 'commentary_wrong': 'BuzzFeed demo.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Manti Te'o catfish in 2012 involved?", 'question': "Involved?", 'answers': {'A': "Fake girlfriend invented online — never existed", 'B': "Hacked Twitter", 'C': "Both", 'D': "Death of family member"}, 'correct': 'A', 'explanation': "Notre Dame football star. 'Girlfriend' Lennay Kekua never existed. Catfished by Ronaiah Tuiasosopo.", 'commentary_correct': 'Correct! Catfish.', 'commentary_wrong': 'Famous catfish case.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The Cottingley Fairies (1917-1920) photos were?", 'question': "Were?", 'answers': {'A': "Schoolgirls' cardboard cutouts", 'B': "Believed real for decades", 'C': "Both A and B — until 1980s confession", 'D': "Painted"}, 'correct': 'C', 'explanation': "Elsie and Frances. 1917 photos in England. Cardboard fairies on stick. Confessed decades later. Doyle was fooled.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Wikipedia's most famous hoax article was?", 'question': "Was?", 'answers': {'A': "Bicholim Conflict — fake war for 6+ years", 'B': "Famous people's death dates", 'C': "Both A and B happen regularly", 'D': "Color of the sky"}, 'correct': 'A', 'explanation': "Bicholim Conflict article on Wikipedia 2007-2012. Entirely fabricated. Lasted 6 years before discovery.", 'commentary_correct': 'Correct! Bicholim.', 'commentary_wrong': 'Bicholim Conflict.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'cinnamon challenge' was?", 'question': "Was?", 'answers': {'A': "Eating spoonful of cinnamon — actually dangerous", 'B': "Cinnamon causes choking + lung damage", 'C': "Both A and B", 'D': "Just a meme"}, 'correct': 'C', 'explanation': "Cinnamon Challenge real. Caused real ER visits and lung damage. Choking hazard. Multiple medical warnings.", 'commentary_correct': 'Correct! Dangerous fad.', 'commentary_wrong': 'Both. Real harm.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'gallon-of-milk' challenge was?", 'question': "Was?", 'answers': {'A': "Drinking a gallon of milk in an hour — most people vomit", 'B': "Easy challenge", 'C': "Both A and B", 'D': "Cheese making"}, 'correct': 'A', 'explanation': "Stomach can't hold a gallon. Vomit guaranteed. Frat hazing tradition. Real challenge with predictable results.", 'commentary_correct': 'Correct! Gallon vomit.', 'commentary_wrong': 'Gallon vomit.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The Texas Sharpshooter (NL Caesars 2011 hoax) was?", 'question': "Was?", 'answers': {'A': "Fake tax-evasion sting that fooled NBC", 'B': "Pure hoax", 'C': "Both A and B — major news embarrassment", 'D': "Was actually real"}, 'correct': 'C', 'explanation': "Multiple sting-style hoaxes have fooled news media. NBC + others had to retract. Famous embarrassments.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "The 'Sasquatch DNA test' on Russian Caucasus in 2014 turned out to be?", 'question': "Turned out?", 'answers': {'A': "Bear DNA + human contamination", 'B': "Definitive proof", 'C': "Both A — also Brian Sykes 2014", 'D': "Sheep DNA"}, 'correct': 'C', 'explanation': "Oxford geneticist Brian Sykes 2014 study. 'Bigfoot' samples were bears, dogs, raccoons. No Sasquatch.", 'commentary_correct': 'Correct! Bears.', 'commentary_wrong': 'Bears and contamination.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Internet Hoaxes Exposed', 'setup': "Anna Sorokin/Anna Delvey was?", 'question': "Was?", 'answers': {'A': "Fake heiress who scammed NYC elite ~$275K", 'B': "Real heiress", 'C': "Both A and B", 'D': "Netflix made show called Inventing Anna"}, 'correct': 'D', 'explanation': "Sorokin convicted of grand larceny 2019. $275K from banks/hotels. Inventing Anna 2022. Now influencer.", 'commentary_correct': 'Correct! Anna Delvey.', 'commentary_wrong': 'Anna Delvey.', 'difficulty': 'easy', 'time_limit': 15},

    # BAD ALBUM COVERS
    {'category': 'Bad Album Covers', 'setup': "Mariah Carey's 1991 'Emotions' cover is?", 'question': "Is?", 'answers': {'A': "Mariah with curly hair in extreme close-up — widely mocked", 'B': "An iconic cover", 'C': "Both A and B", 'D': "Re-released later"}, 'correct': 'C', 'explanation': "Mariah Carey's Emotions cover (1991). Tightly cropped face. Mocked at time but career-defining.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "The Beatles' 'Yesterday and Today' (1966) had?", 'question': "Had?", 'answers': {'A': "Original 'butcher cover' with raw meat + dismembered dolls", 'B': "Just a normal cover", 'C': "Both A — recalled fast and replaced", 'D': "Black cover"}, 'correct': 'C', 'explanation': "Butcher cover June 1966. Recalled within days. Replaced with safer cover. Originals are collector's items.", 'commentary_correct': 'Correct! Butcher.', 'commentary_wrong': 'Butcher cover. Pulled.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Roger Dean's Yes album covers are famous for?", 'question': "Famous for?", 'answers': {'A': "Floating islands + dragons + iconic typography", 'B': "Bad reception", 'C': "Both A — Avatar lawsuit inspired by them (later settled)", 'D': "Realistic photography"}, 'correct': 'C', 'explanation': "Dean's Yes covers iconic. Avatar 2009 looked suspiciously like his work. Dean sued (lost). Legendary art.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Mac Davis's 1980 'Texas In My Rear View Mirror' cover is?", 'question': "Is?", 'answers': {'A': "Notoriously bad — frequently in worst-covers lists", 'B': "Beautifully designed", 'C': "Both", 'D': "Removed from streaming"}, 'correct': 'A', 'explanation': "Mac Davis. Texas In My Rear View Mirror. Considered one of worst country covers ever. Bad photo + bad design.", 'commentary_correct': 'Correct! Bad cover.', 'commentary_wrong': 'Bad cover.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Tipper Gore's PMRC (Parents Music Resource Center) was started over?", 'question': "Started over?", 'answers': {'A': "Prince's 'Darling Nikki' lyrics in 1985", 'B': "Album covers", 'C': "Both — 'Filthy Fifteen' list", 'D': "Rap music"}, 'correct': 'C', 'explanation': "Tipper Gore PMRC 1985. Filthy Fifteen included Prince, AC/DC, Madonna. Led to Parental Advisory stickers.", 'commentary_correct': 'Correct! Filthy Fifteen.', 'commentary_wrong': 'Filthy Fifteen.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Nirvana's 'Nevermind' cover (baby in pool) faced what 2021 lawsuit?", 'question': "Sued by?", 'answers': {'A': "The now-adult baby (Spencer Elden) for child porn", 'B': "Just a photoshoot dispute", 'C': "Both A — case was dismissed and refiled", 'D': "Photographer"}, 'correct': 'C', 'explanation': "Spencer Elden filed 2021 lawsuit. Dismissed, refiled. Federal courts. Case still ongoing.", 'commentary_correct': 'Correct! Elden suit.', 'commentary_wrong': 'Elden suit.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Pink Floyd's 'The Wall' was a?", 'question': "Was?", 'answers': {'A': "Famous album + 1982 movie", 'B': "Just an album", 'C': "Both A and B", 'D': "Just a movie"}, 'correct': 'C', 'explanation': "1979 album. 1982 movie (Bob Geldof starring). Iconic Gerald Scarfe artwork throughout.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Kanye West's 'My Beautiful Dark Twisted Fantasy' (2010) cover banned because?", 'question': "Banned because?", 'answers': {'A': "Painting of Kanye + winged woman", 'B': "Walmart refused it", 'C': "Both A and B", 'D': "Considered offensive"}, 'correct': 'B', 'explanation': "Walmart refused 2010 cover. George Condo painting deemed too risqué. Multiple alternate covers released.", 'commentary_correct': 'Correct! Walmart ban.', 'commentary_wrong': 'Walmart ban.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Andy Warhol's banana on the Velvet Underground & Nico cover?", 'question': "Was?", 'answers': {'A': "Original 1967 came with peel-away banana sticker", 'B': "Iconic art", 'C': "Both A and B", 'D': "Banana-flavored"}, 'correct': 'C', 'explanation': "Original copies had peel-away banana revealing pink banana underneath. Most peeled. Originals are collector's items.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Iron Butterfly's 'In-A-Gadda-Da-Vida' was?", 'question': "Was?", 'answers': {'A': "First-ever platinum album", 'B': "17-minute title track", 'C': "Both", 'D': "Considered legendary"}, 'correct': 'C', 'explanation': "1968 album. 17-minute title track. First platinum record awarded by RIAA. Bizarre cover with bug.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "The famous 'Spice World' (1997) Spice Girls album cover was shot?", 'question': "Shot?", 'answers': {'A': "In London on the streets", 'B': "In a studio", 'C': "Both", 'D': "Pink background"}, 'correct': 'A', 'explanation': "Spice World shot London streets. Each member in iconic outfits. Spawned Spice World movie + tour.", 'commentary_correct': 'Correct! London streets.', 'commentary_wrong': 'London streets.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Marilyn Manson's 1996 'Antichrist Superstar' cover faced?", 'question': "Faced?", 'answers': {'A': "Multiple banned-in-Walmart issues", 'B': "Sticker requirements", 'C': "Both A and B", 'D': "Tour cancellations"}, 'correct': 'C', 'explanation': "Manson albums regularly faced retailer pushback. Stickers, censorship, both. Career strategy of provocation.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "The Black Crowes' 'Amorica' (1994) cover was?", 'question': "Was?", 'answers': {'A': "Close-up of patriotic-print bikini bottom + pubic hair", 'B': "Just a flag", 'C': "Both A — Walmart pulled it", 'D': "Banned in 4 states"}, 'correct': 'C', 'explanation': "Amorica cover. American flag-patterned bikini + visible pubic hair. Walmart sticker required. Banned widely.", 'commentary_correct': 'Correct! Bikini.', 'commentary_wrong': 'Bikini cover.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Whitesnake's 1987 album included what infamous cover?", 'question': "Cover?", 'answers': {'A': "Snake-themed art + Tawny Kitaen content", 'B': "Plain text", 'C': "Both A — and 'Here I Go Again' video had iconic Tawny", 'D': "Black-and-white photo"}, 'correct': 'C', 'explanation': "Whitesnake 1987 album. Tawny Kitaen video work iconic. Album sold 8M+ copies. Hair-metal apex.", 'commentary_correct': 'Correct! Snake.', 'commentary_wrong': 'Snake/Tawny era.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Roxy Music's first album (1972) cover featured?", 'question': "Featured?", 'answers': {'A': "Model Kari-Ann Muller in vintage 50s style", 'B': "Bryan Ferry himself", 'C': "Both", 'D': "Roxy Music logo only"}, 'correct': 'A', 'explanation': "Roxy Music debut 1972. Model Kari-Ann Muller. Set design template for band's glamour aesthetic.", 'commentary_correct': 'Correct! Model cover.', 'commentary_wrong': 'Model cover.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Joy Division's 'Unknown Pleasures' (1979) cover became?", 'question': "Became?", 'answers': {'A': "Most plagiarized album cover ever (pulsar wave pattern)", 'B': "Forgotten", 'C': "Both A — Peter Saville designed it", 'D': "Removed from print"}, 'correct': 'C', 'explanation': "Peter Saville. Pulsar wave from astronomy book. Most-tattooed/most-printed-on-merch cover in rock history.", 'commentary_correct': 'Correct! Pulsar.', 'commentary_wrong': 'Pulsar cover.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "John Lennon's 'Two Virgins' (1968) cover was?", 'question': "Was?", 'answers': {'A': "Nude photos of John + Yoko", 'B': "Censored in brown paper bags", 'C': "Both A and B", 'D': "Just paintings"}, 'correct': 'C', 'explanation': "Two Virgins with John and Yoko nude on cover. Sold in plain brown wrapper. Most controversial album cover of 60s.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Hipgnosis (Pink Floyd's designers) most famous covers include?", 'question': "Famous for?", 'answers': {'A': "Dark Side of the Moon prism + Wish You Were Here", 'B': "Animal collaborations", 'C': "Both", 'D': "Just typography"}, 'correct': 'C', 'explanation': "Hipgnosis (Storm Thorgerson). Dark Side prism. Wish You Were Here handshake (one on fire). Iconic.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "The Strokes' 'Is This It' (2001) UK cover was?", 'question': "UK cover?", 'answers': {'A': "Latex-gloved hand on bare hip", 'B': "Replaced for US release with car crash photo", 'C': "Both A and B", 'D': "Beach scene"}, 'correct': 'C', 'explanation': "UK cover hand + hip. US release used Cherenkov radiation photo. Multiple regional variants.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bad Album Covers', 'setup': "Lady Gaga's 'ARTPOP' (2013) was a?", 'question': "Was?", 'answers': {'A': "Commercial flop (low sales)", 'B': "Critical disaster", 'C': "Both — Gaga had to rebrand approach", 'D': "Top-seller"}, 'correct': 'C', 'explanation': "ARTPOP underperformed expectations. Forced Gaga to pivot. Came back stronger with Joanne and Star Is Born.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},

    # STRIPPER HEISTS & WHITE-COLLAR CRIME
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "The Hustlers (2019) movie was based on?", 'question': "Based on?", 'answers': {'A': "Roselyn Keo + Samantha Barbash real strippers", 'B': "A Jessica Pressler article in New York Magazine", 'C': "Both A and B", 'D': "A novel"}, 'correct': 'C', 'explanation': "Real Roselyn Keo + Samantha Barbash drugged Wall Street guys, charged credit cards. 2015 case. JLo movie 2019.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Bernie Madoff's Ponzi scheme was approximately?", 'question': "Size?", 'answers': {'A': "~$65 billion (largest Ponzi in history)", 'B': "$100M", 'C': "$1 billion", 'D': "$10 trillion"}, 'correct': 'A', 'explanation': "$64.8B in fictitious balances. 4,800 client accounts. Largest Ponzi ever. Madoff died in prison 2021.", 'commentary_correct': 'Correct! $65B.', 'commentary_wrong': '$65 billion.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Elizabeth Holmes' Theranos fraud was?", 'question': "Was?", 'answers': {'A': "Fake blood-testing tech", 'B': "Convinced multiple billionaires of fraud", 'C': "Both A and B", 'D': "Used real samples"}, 'correct': 'C', 'explanation': "Theranos claimed proprietary blood tests. None worked. Fooled Murdoch + Walgreens + Boeing. Convicted 2022.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Enron's collapse in 2001 was driven by?", 'question': "Driven by?", 'answers': {'A': "Mark-to-market accounting fraud", 'B': "Off-balance-sheet SPEs", 'C': "Both A and B", 'D': "Energy market manipulation"}, 'correct': 'C', 'explanation': "Enron used MTM accounting + Special Purpose Entities to hide losses. Largest bankruptcy of its time.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "The 1990s S&L Crisis cost taxpayers approximately?", 'question': "Approximate?", 'answers': {'A': "$160 billion (incl. interest)", 'B': "$10 billion", 'C': "$1 trillion", 'D': "$50 million"}, 'correct': 'A', 'explanation': "Savings and Loan crisis 1980s-90s. ~1,000 institutions failed. Bailout cost $160B+. Pre-2008 financial disaster.", 'commentary_correct': 'Correct! $160B.', 'commentary_wrong': '$160B.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Jeffrey Epstein's accomplice Ghislaine Maxwell was convicted in?", 'question': "Convicted when?", 'answers': {'A': "December 2021 — sex trafficking + conspiracy", 'B': "Acquitted", 'C': "Both A and B", 'D': "2020"}, 'correct': 'A', 'explanation': "Maxwell convicted December 2021. 20-year sentence. Sex trafficking, conspiracy. Epstein co-conspirator.", 'commentary_correct': 'Correct! 2021.', 'commentary_wrong': '2021.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Anna Delvey/Sorokin's NYC scam targeted?", 'question': "Targeted?", 'answers': {'A': "Banks, hotels, friends — fake heiress story", 'B': "Just one bank", 'C': "Both A and B — $275K total", 'D': "A Ponzi scheme"}, 'correct': 'C', 'explanation': "Anna Sorokin/Delvey. Pretended to be German heiress. Defrauded $275K. Inventing Anna Netflix show 2022.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "WorldCom's 2002 fraud was approximately?", 'question': "Size?", 'answers': {'A': "$11 billion (largest accounting fraud at the time)", 'B': "$1 million", 'C': "$1 trillion", 'D': "$500 million"}, 'correct': 'A', 'explanation': "WorldCom inflated revenue by $11B. CEO Bernie Ebbers convicted. Pre-Enron, then Enron-then-WorldCom-then-Madoff escalating frauds.", 'commentary_correct': 'Correct! $11B.', 'commentary_wrong': '$11B.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Allen Stanford's Ponzi was approximately?", 'question': "Size?", 'answers': {'A': "$7 billion", 'B': "Just $50M", 'C': "$100 billion", 'D': "$1 million"}, 'correct': 'A', 'explanation': "Stanford International Bank. $7B Ponzi. Sentenced 110 years 2012. Second-largest US Ponzi.", 'commentary_correct': 'Correct! $7B.', 'commentary_wrong': '$7B.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Sam Bankman-Fried's FTX collapse involved?", 'question': "Involved?", 'answers': {'A': "Mixing customer funds with Alameda Research", 'B': "$8 billion in missing funds", 'C': "Both A and B", 'D': "Just bad business luck"}, 'correct': 'C', 'explanation': "FTX collapsed November 2022. SBF used customer funds. Convicted October 2023. Sentenced 25 years 2024.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "The 'Wolf of Wall Street' Jordan Belfort's actual crime was?", 'question': "Was?", 'answers': {'A': "Pump-and-dump stock fraud at Stratton Oakmont", 'B': "Insider trading", 'C': "Both A and B", 'D': "Tax evasion"}, 'correct': 'A', 'explanation': "Belfort founded Stratton Oakmont. Penny stock pump-and-dump. Defrauded ~$200M. Prison 22 months.", 'commentary_correct': 'Correct! Pump-and-dump.', 'commentary_wrong': 'Pump and dump.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Charles Ponzi's original scheme (1920) used?", 'question': "Used?", 'answers': {'A': "International postal reply coupons", 'B': "Stocks", 'C': "Both", 'D': "Banking"}, 'correct': 'A', 'explanation': "1920 Boston. Postal reply coupons arbitrage. Promised 50% return in 90 days. Last weeks: $250K/day. Imploded.", 'commentary_correct': 'Correct! Postal coupons.', 'commentary_wrong': 'Postal coupons.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Frank Abagnale (Catch Me If You Can) cashed?", 'question': "Cashed?", 'answers': {'A': "~$2.5 million in fake checks (his claim)", 'B': "Just dozens", 'C': "Both A and details disputed", 'D': "$100M"}, 'correct': 'C', 'explanation': "Abagnale's autobiography claims have been disputed by journalists. Real fraud yes, exact amounts uncertain.", 'commentary_correct': 'Correct! Disputed.', 'commentary_wrong': 'Disputed claims.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Tyco's CEO Dennis Kozlowski threw a famously lavish?", 'question': "Lavish?", 'answers': {'A': "$2M Roman-themed birthday for his wife in Sardinia", 'B': "Wedding", 'C': "Both A — vodka-pissing-David-statue ice sculpture", 'D': "Funeral"}, 'correct': 'C', 'explanation': "Kozlowski's 2001 Sardinia bash. $2M party for Karen Mayo Kozlowski. Ice statue of David urinating vodka. Optics nightmare.", 'commentary_correct': 'Correct! Sardinia.', 'commentary_wrong': 'Sardinia party.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Martha Stewart's 2004 prison sentence was for?", 'question': "Was for?", 'answers': {'A': "Lying to investigators about ImClone stock sale", 'B': "Insider trading", 'C': "Both — she was convicted of obstruction not trading", 'D': "Tax evasion"}, 'correct': 'C', 'explanation': "Convicted obstruction + lying. Not insider trading. Served 5 months. Came back stronger with Snoop friendship.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Trevor Milton (Nikola founder) was convicted of?", 'question': "Convicted of?", 'answers': {'A': "Fraud — Nikola truck videos rolling downhill were fake", 'B': "Real progress", 'C': "Both", 'D': "Tax fraud"}, 'correct': 'A', 'explanation': "Milton convicted 2022. Hindenburg Research revealed Nikola truck demo was rolling downhill. Promotional fraud.", 'commentary_correct': 'Correct! Nikola.', 'commentary_wrong': 'Nikola fraud.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Bernie Madoff's sons reported him because?", 'question': "Why?", 'answers': {'A': "Frank admission to them December 2008", 'B': "They suspected for years", 'C': "Both A and B", 'D': "An anonymous tip"}, 'correct': 'A', 'explanation': "Madoff confessed to sons Mark and Andrew Dec 10, 2008. They turned him in next day. Mark later died by suicide.", 'commentary_correct': 'Correct! Sons reported.', 'commentary_wrong': 'Sons reported.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "The 'Hot Yoga of Bikram' Choudhury fled to?", 'question': "Fled to?", 'answers': {'A': "Mexico to avoid $7M judgment + sex assault charges", 'B': "India", 'C': "Both A and B over time", 'D': "Brazil"}, 'correct': 'C', 'explanation': "Bikram Choudhury fled multiple jurisdictions. Sex assault allegations. $7M lawsuit. Still teaches abroad.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Wirecard's 2020 collapse involved?", 'question': "Involved?", 'answers': {'A': "$2 billion in missing money — auditors signed off", 'B': "FT investigation revealed fraud", 'C': "Both", 'D': "Just bad luck"}, 'correct': 'C', 'explanation': "German fintech Wirecard. FT exposed fraud. €1.9B in 'missing' Philippines bank accounts. EY took heavy heat for clean audits.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both. EY missed it.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Stripper Heists & White-Collar Crime', 'setup': "Allen Stanford was famous for?", 'question': "Famous for?", 'answers': {'A': "Tying his Ponzi to cricket sponsorship", 'B': "$7B fraud", 'C': "Both", 'D': "Just one investment"}, 'correct': 'C', 'explanation': "Stanford sponsored England-West Indies cricket. Knighted by Antigua. $7B Ponzi. Convicted 2012.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},

    # PAGEANT MISHAPS
    {'category': 'Pageant Mishaps', 'setup': "Steve Harvey announced the wrong Miss Universe winner in?", 'question': "Year?", 'answers': {'A': "2015 — said Miss Colombia, meant Miss Philippines", 'B': "2010", 'C': "2020", 'D': "1995"}, 'correct': 'A', 'explanation': "December 2015. Harvey crowned Miss Colombia. Realized error. Re-crowned Miss Philippines (Pia Wurtzbach). Cringe legend.", 'commentary_correct': 'Correct! 2015.', 'commentary_wrong': '2015.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss USA Olivia Culpo won Miss Universe in?", 'question': "Won when?", 'answers': {'A': "2012", 'B': "2008", 'C': "2015", 'D': "2018"}, 'correct': 'A', 'explanation': "Olivia Culpo Miss Universe 2012. Now influencer/actress. Married NFL player.", 'commentary_correct': 'Correct! 2012.', 'commentary_wrong': '2012.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Carrie Prejean (Miss USA 2009) became controversial because?", 'question': "Because?", 'answers': {'A': "Said she opposed same-sex marriage on stage", 'B': "Stripped on stage", 'C': "Both", 'D': "Bumped Donald Trump"}, 'correct': 'A', 'explanation': "Asked about gay marriage. Said she's opposed. Lost crown later. Conservative cause célèbre. Wrote book.", 'commentary_correct': 'Correct! Marriage answer.', 'commentary_wrong': 'Marriage answer.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss Teen USA 2007 'maps' answer was given by?", 'question': "By whom?", 'answers': {'A': "Caitlin Upton (Miss Teen South Carolina)", 'B': "Miss USA", 'C': "A judge", 'D': "Just a famous fail"}, 'correct': 'A', 'explanation': "Caitlin Upton's rambling answer about Americans unable to find places on maps. Became viral. Upton became cyberbullied.", 'commentary_correct': 'Correct! Caitlin Upton.', 'commentary_wrong': 'Caitlin Upton.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Vanessa Williams was the first Black Miss America in?", 'question': "When?", 'answers': {'A': "1983", 'B': "1968", 'C': "1995", 'D': "1978"}, 'correct': 'A', 'explanation': "Vanessa Williams Miss America 1984 (crowned September 1983). First Black winner. Resigned 1984 over Penthouse photos. Apologized to her 2015.", 'commentary_correct': 'Correct! 1983.', 'commentary_wrong': '1983.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Donald Trump owned the Miss Universe Organization until?", 'question': "Until?", 'answers': {'A': "2015 (sold to WME/IMG)", 'B': "Still owns it", 'C': "Sold in 2010", 'D': "Was never owner"}, 'correct': 'A', 'explanation': "Trump bought Miss Universe 1996. Sold 2015. Controversial Miss USA comments + boycotts during ownership.", 'commentary_correct': 'Correct! 2015.', 'commentary_wrong': '2015.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss America rebranded as 'Miss America 2.0' in 2018 by?", 'question': "Eliminated?", 'answers': {'A': "Swimsuit competition", 'B': "Evening gown", 'C': "Both A and B", 'D': "Talent"}, 'correct': 'A', 'explanation': "Miss America 2018 eliminated swimsuit competition. Massive controversy. Gretchen Carlson + Cara Mund issues.", 'commentary_correct': 'Correct! Swimsuit.', 'commentary_wrong': 'Swimsuit. Big change.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "JonBenét Ramsey was a?", 'question': "Was?", 'answers': {'A': "Child beauty pageant queen", 'B': "Murder victim Dec 1996", 'C': "Both", 'D': "Sister of a pageant queen"}, 'correct': 'C', 'explanation': "JonBenét was 6yo pageant winner. Murdered Christmas 1996 Boulder CO. Case still unsolved.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Toddlers & Tiaras (2009-2013) was on?", 'question': "On what network?", 'answers': {'A': "TLC", 'B': "MTV", 'C': "VH1", 'D': "Bravo"}, 'correct': 'A', 'explanation': "TLC. 2009-2013. Spawned Honey Boo Boo. Glorified/exposed child pageant culture. Massive ratings.", 'commentary_correct': 'Correct! TLC.', 'commentary_wrong': 'TLC.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Honey Boo Boo emerged from?", 'question': "Emerged from?", 'answers': {'A': "Toddlers & Tiaras", 'B': "Just family fame", 'C': "Both A and B", 'D': "Beauty pageant circuit"}, 'correct': 'A', 'explanation': "Alana 'Honey Boo Boo' Thompson appeared T&T 2012. Spinoff 'Here Comes Honey Boo Boo' became hit. Family later controversial.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss USA 2002 Shauntay Hinton was?", 'question': "Was?", 'answers': {'A': "First openly gay Miss USA winner", 'B': "Won then was disqualified", 'C': "Both A and B", 'D': "First African American"}, 'correct': 'C', 'explanation': "Shauntay Hinton Miss USA 2002. Multiple firsts/controversies. Crown returned/revoked over disputes.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "The 1957 Miss America Marilyn Van Derbur was famously?", 'question': "Was?", 'answers': {'A': "First Miss America to win Mrs. Plus 50+ later in life", 'B': "Disclosed childhood sexual abuse decades later", 'C': "Both A and B", 'D': "Forgotten"}, 'correct': 'B', 'explanation': "Marilyn Van Derbur Miss America 1957. Disclosed childhood incest 1991. Became advocate. Wrote book.", 'commentary_correct': 'Correct! Brave disclosure.', 'commentary_wrong': 'Brave disclosure.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Vanessa Williams' Penthouse photos in 1984 had been?", 'question': "Photos taken?", 'answers': {'A': "1982 — before her Miss America win", 'B': "After her crown", 'C': "Faked", 'D': "Both A and Penthouse stole/leaked them"}, 'correct': 'D', 'explanation': "Photos taken 1982 in test session, released by Penthouse 1984. Williams had not authorized. Eventually apologized to her 2015.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Andre Agassi married a Miss Universe winner. Which one?", 'question': "Married?", 'answers': {'A': "Brooke Shields (1997-99)", 'B': "Steffi Graf (still married)", 'C': "Both — Brooke first, Steffi second", 'D': "Mary Lou Retton"}, 'correct': 'C', 'explanation': "Agassi married Brooke Shields 1997, divorced 1999. Married Steffi Graf 2001 (still married). Shields was actress not pageant.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss Universe pageant viewership peaked in?", 'question': "Peak?", 'answers': {'A': "1980s (~30M+ US viewers)", 'B': "2020s", 'C': "1960s", 'D': "Always declining"}, 'correct': 'A', 'explanation': "Pageant ratings peaked 1970s-80s. Steep decline since. Now mostly streaming/cable.", 'commentary_correct': 'Correct! 1980s.', 'commentary_wrong': '1980s.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss Universe 1996 Alicia Machado was insulted by Trump for?", 'question': "Insulted for?", 'answers': {'A': "Gaining weight after winning", 'B': "Political comments", 'C': "Both A — Trump called her 'Miss Piggy'", 'D': "Marriage"}, 'correct': 'C', 'explanation': "Trump publicly insulted weight gain. 'Miss Piggy.' Returned in 2016 election. Hillary Clinton's debate attack on Trump.", 'commentary_correct': 'Correct! Miss Piggy.', 'commentary_wrong': 'Miss Piggy comments.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Cara Mund (Miss America 2018) wrote a viral letter in?", 'question': "Letter about?", 'answers': {'A': "Treatment by Miss America leadership (Gretchen Carlson era)", 'B': "Pageant abuses", 'C': "Both", 'D': "Defending Trump"}, 'correct': 'C', 'explanation': "August 2018 letter alleging treatment as bully+silencing+control. Major MA internal scandal. Carlson resigned 2019.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss Universe 1980 Shawn Weatherly was?", 'question': "Best known later for?", 'answers': {'A': "Baywatch — played Jill Riley", 'B': "Acting career after pageant", 'C': "Both A and B", 'D': "Politics"}, 'correct': 'C', 'explanation': "Shawn Weatherly Miss Universe 1980. Joined Baywatch. Career fit pageant-to-TV path common for winners.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss America Bess Myerson (1945) was famous for being?", 'question': "Famous for?", 'answers': {'A': "First Jewish Miss America", 'B': "First Jewish Miss America during WWII end", 'C': "Both — and faced anti-Semitism", 'D': "Multiple titles"}, 'correct': 'C', 'explanation': "Bess Myerson Miss America 1945. First Jewish winner. Faced anti-Semitism but became NYC commissioner. Pioneer.", 'commentary_correct': 'Correct! Both.', 'commentary_wrong': 'Both.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Pageant Mishaps', 'setup': "Miss Teen USA 2020 was canceled because?", 'question': "Canceled because?", 'answers': {'A': "COVID-19 pandemic", 'B': "Scandals", 'C': "Both", 'D': "Sponsor issues"}, 'correct': 'A', 'explanation': "2020 pandemic caused multiple pageant cancellations/postponements. Miss USA + Miss Teen USA both affected.", 'commentary_correct': 'Correct! COVID.', 'commentary_wrong': 'COVID.', 'difficulty': 'medium', 'time_limit': 15},

    # BIZARRE PHOBIAS
    {'category': 'Bizarre Phobias', 'setup': "Trypophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Clusters of small holes (lotus pod, honeycomb)", 'B': "Trains", 'C': "Triangles", 'D': "Trees"}, 'correct': 'A', 'explanation': "Fear of holes. Not officially in DSM. Strong online community. Aristotelian visual disgust response.", 'commentary_correct': 'Correct! Holes.', 'commentary_wrong': 'Holes.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Pogonophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Beards", 'B': "Knives", 'C': "Public speaking", 'D': "Phobias"}, 'correct': 'A', 'explanation': "Real phobia. Fear of beards/facial hair. Real cases documented. Some can't even watch bearded actors.", 'commentary_correct': 'Correct! Beards.', 'commentary_wrong': 'Beards.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Hippopotomonstrosesquippedaliophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Long words (literally — yes, the name is ironic)", 'B': "Hippos", 'C': "Monsters", 'D': "Sequels"}, 'correct': 'A', 'explanation': "Real phobia (sometimes called sesquipedalophobia). Fear of long words. Cruel naming joke by clinicians.", 'commentary_correct': 'Correct! Long words.', 'commentary_wrong': 'Long words.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Anatidaephobia is the fear that?", 'question': "Fear that?", 'answers': {'A': "Somewhere, a duck is watching you (Far Side joke turned real)", 'B': "Ducks attack", 'C': "Both — Gary Larson invented it", 'D': "Wet feathers"}, 'correct': 'C', 'explanation': "Gary Larson's Far Side cartoon coined the joke phobia. Some people genuinely report duck-watching anxiety.", 'commentary_correct': 'Correct! Duck watching.', 'commentary_wrong': 'Duck watching.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Phasmophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Ghosts", 'B': "Buttons", 'C': "Snakes", 'D': "The number 8"}, 'correct': 'A', 'explanation': "Fear of ghosts. Also a popular VR game. Real condition.", 'commentary_correct': 'Correct! Ghosts.', 'commentary_wrong': 'Ghosts.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Coulrophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Clowns", 'B': "Crowds", 'C': "Color", 'D': "Coke"}, 'correct': 'A', 'explanation': "Clown phobia. Affects ~7% of US adults. Pennywise, John Wayne Gacy, killer clown sightings all contribute.", 'commentary_correct': 'Correct! Clowns.', 'commentary_wrong': 'Clowns.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Nomophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Being without your phone (no mobile)", 'B': "Names", 'C': "Numbers", 'D': "Mall stores"}, 'correct': 'A', 'explanation': "Modern phobia. Fear of being without cell phone. Studies show 60%+ of young adults exhibit symptoms.", 'commentary_correct': 'Correct! No mobile.', 'commentary_wrong': 'No mobile phobia.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Triskaidekaphobia is fear of?", 'question': "Fear of?", 'answers': {'A': "The number 13", 'B': "Three things", 'C': "Triangles", 'D': "Thirteen people"}, 'correct': 'A', 'explanation': "Fear of 13. Many buildings skip floor 13. Friday the 13th common cultural trigger.", 'commentary_correct': 'Correct! 13.', 'commentary_wrong': 'The number 13.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Chrometophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Money", 'B': "Chrome (shiny metal)", 'C': "Color", 'D': "Christmas"}, 'correct': 'A', 'explanation': "Real phobia. Fear of money/wealth. Howard Hughes had related germ-phobia with cash specifically.", 'commentary_correct': 'Correct! Money.', 'commentary_wrong': 'Money.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Genuphobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Knees (own or others')", 'B': "Geneva", 'C': "Genes", 'D': "Giants"}, 'correct': 'A', 'explanation': "Real phobia. Fear of knees. Some can't wear shorts. Visual + tactile aversion.", 'commentary_correct': 'Correct! Knees.', 'commentary_wrong': 'Knees.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Globophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Balloons", 'B': "Globes", 'C': "Both A and B (different conditions)", 'D': "Glaciers"}, 'correct': 'A', 'explanation': "Balloon phobia. Pop = startle. Some can't attend kids' birthdays. Affects ~5% of children.", 'commentary_correct': 'Correct! Balloons.', 'commentary_wrong': 'Balloons.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Oprah Winfrey reportedly has phobia of?", 'question': "Phobia of?", 'answers': {'A': "Chewing gum", 'B': "Snakes", 'C': "Both — gum is the famous one", 'D': "Bald people"}, 'correct': 'C', 'explanation': "Oprah's gum aversion documented. Won't have it in studio. Childhood incident with grandmother's chewed gum.", 'commentary_correct': 'Correct! Gum.', 'commentary_wrong': 'Gum.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Steve Jobs reportedly had phobia of?", 'question': "Phobia of?", 'answers': {'A': "Buttons", 'B': "Lawyers", 'C': "Both — Apple products famously simple", 'D': "Steve Wozniak"}, 'correct': 'A', 'explanation': "Jobs koumpounophobia (button phobia) widely reported. Apple's interface designed minimal-button. iPhone's no-keys design.", 'commentary_correct': 'Correct! Buttons.', 'commentary_wrong': 'Buttons.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Nyctophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Darkness/night", 'B': "Niagara Falls", 'C': "Noises", 'D': "Naps"}, 'correct': 'A', 'explanation': "Fear of night/dark. Very common in children. ~10% of adults have it. Often resolves with age.", 'commentary_correct': 'Correct! Dark.', 'commentary_wrong': 'Darkness.', 'difficulty': 'easy', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Megan Fox famously has phobia of?", 'question': "Phobia of?", 'answers': {'A': "Paper, especially dry paper (xerophobia)", 'B': "Bugs", 'C': "Both — and dirty silverware in restaurants", 'D': "Loud noises"}, 'correct': 'C', 'explanation': "Megan Fox's documented phobias: dry paper, dirty restaurant cutlery, germs generally. Frequently mentioned in interviews.", 'commentary_correct': 'Correct! Paper + cutlery.', 'commentary_wrong': 'Paper + cutlery.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Selenophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "The moon", 'B': "Selenium", 'C': "Selfies", 'D': "Selena Gomez"}, 'correct': 'A', 'explanation': "Fear of moon. Lunar phobia. Rare. Some have werewolf-mythology cultural triggers. Others moonlight-specific.", 'commentary_correct': 'Correct! Moon.', 'commentary_wrong': 'Moon.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Pediophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Dolls (Annabelle, Chucky etc.)", 'B': "Children", 'C': "Pedestrians", 'D': "Feet"}, 'correct': 'A', 'explanation': "Doll phobia. Annabelle/Chucky pop-culture references reinforce. Distinct from pedophobia (children).", 'commentary_correct': 'Correct! Dolls.', 'commentary_wrong': 'Dolls.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Pteronophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Being tickled by feathers", 'B': "Pterodactyls", 'C': "Pens", 'D': "Both A and B (different conditions)"}, 'correct': 'A', 'explanation': "Real phobia. Fear of feather tickling specifically. Often childhood-trauma rooted.", 'commentary_correct': 'Correct! Feather tickle.', 'commentary_wrong': 'Feather tickling.', 'difficulty': 'hard', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Ailurophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "Cats", 'B': "Air", 'C': "Aliens", 'D': "Alleys"}, 'correct': 'A', 'explanation': "Cat phobia. ~5% of population. Napoleon famously feared cats. Also Hitler. Powerful figures + cat aversion meme.", 'commentary_correct': 'Correct! Cats.', 'commentary_wrong': 'Cats.', 'difficulty': 'medium', 'time_limit': 15},
    {'category': 'Bizarre Phobias', 'setup': "Xanthophobia is fear of?", 'question': "Fear of?", 'answers': {'A': "The color yellow", 'B': "Xanthippe (Socrates' wife)", 'C': "Saxophones", 'D': "X-rays"}, 'correct': 'A', 'explanation': "Fear of yellow. Rare. Can include avoiding yellow foods, signs, school buses. Real condition documented.", 'commentary_correct': 'Correct! Yellow.', 'commentary_wrong': 'Yellow color.', 'difficulty': 'medium', 'time_limit': 15},
]


def seed_v4_batch2e():
    ph = get_placeholder()
    added = 0
    for q in V4_BATCH2E_QUESTIONS:
        cat = get_category_by_name(q['category'])
        if not cat:
            continue
        try:
            execute_query(f'''
                INSERT OR IGNORE INTO trivia_questions
                (category_id, question_text, setup_text, answer_a, answer_b, answer_c, answer_d,
                 correct_answer, difficulty, time_limit, explanation,
                 host_commentary_correct, host_commentary_wrong)
                VALUES ({ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph}, {ph})
            ''', (cat['id'], q['question'], q.get('setup','') or '',
                  q['answers']['A'], q['answers']['B'], q['answers']['C'], q['answers']['D'],
                  q['correct'], q.get('difficulty','medium'), q.get('time_limit',15),
                  q.get('explanation',''), q.get('commentary_correct',''), q.get('commentary_wrong','')))
            added += 1
        except Exception as e:
            print(f"[v4-b2e] {e}")
    print(f"✅ v4 batch2e added {added} ({len(V4_BATCH2E_QUESTIONS)} in pack)")


if __name__ == '__main__':
    seed_v4_batch2e()
